osbuild/images

- .gitlab-ci.yml
- schutzbot/update_github_status.sh
- test/cases/diff-manifests.sh
The update_github_status script was trying to update the status on osbuild-composer.
> schutzbot: fix repo URL in update_github_status

- CONTRIBUTING.md
- HACKING.md
Strangely, neither of them was "osbulid".
> Fix a couple of osbuild typos

- .github/workflows/auto-merge-dependabot.yml
Let's see if this is a permissions issue.
> github: grant all perms to auto-merge-dependabot

- pkg/distro/rhel8/distro.go
- pkg/distro/rhel8/edge.go
- pkg/distro/rhel8/partition_tables.go
- pkg/distro/rhel9/distro.go
- pkg/distro/rhel9/edge.go
- Revert "distro: Disable BIOS boot for all the RHEL edge images"
- Revert "distro: remove unused BIOS partition from RHEL edge images"
> revert edge remove hybrid boot

- README.md
> README: update links to bug tracker and changelog

- pkg/manifest/anaconda_installer_iso_tree.go
- pkg/manifest/coi_iso_tree.go
- pkg/manifest/iso_rootfs.go
Fixes #226
See also https://github.com/osbuild/osbuild/pull/1409
> Use absolute paths in mkdir stage options

- pkg/image/ostree_archive.go
- pkg/manifest/ostree_encapsulate.go
- pkg/osbuild/ostree_encapsulate_stage.go
Add the ostree encapsulate stage and a pipeline for creating ostree native containers.
> Add org.osbuild.ostree.encapsulate stage

- test/scripts/upload-results
> Strip the PR prefix for a successful build *before* adding it to info

- pkg/cloud/awscloud/awscloud.go
Quick drive-by PR to make it possible to have upload progress.
Needed for https://github.com/osbuild/bootc-image-builder/pull/134
> awscloud: add new UploadFromReader()

- pkg/distro/fedora/package_sets.go
- pkg/distro/fedora/version.go
This was mentioned in passing somewhere. Let's have a version constant for RAWHIDE so we only have one place to update rawhidey things.
> fedora: version constant

- .github/workflows/pr_best_practices.yml
This adds our common PR best practices check action to this repository.
> ci: add a PR best practices check

- .github/workflows/update-bootc-image-builder.yml
> github: fix bib update workflow: check out sources first

- pkg/distro/rhel8/partition_tables.go
RHEL-8 EC2 x86_64 images support only BIOS boot until 8.9. The partition table used to reflect that. Since 8.9, the image gained /boot/efi partition and supports hybrid boot mode.
However, I recently noticed that RHEL-8 EC2 x86_64 images for older releases than 8.9 also contain the /boot/efi partition. It turns out, that https://github.com/osbuild/images/commit/7acf235f8349552b705232773ed429336e42e066 unintentionally introduced /boot/efi partition to all RHEL-8 x86_64 EC2 images, regardless of the minor release version.
Fix this issue by ensuring that RHEL-8 x86_64 EC2 images prior to 8.9 do not contain /boot/efi partition.
> Distro/rhel8: fix EC2 x86_64 RHEL < 8.9 partition table

- test/README.md
While writing up #594 I realised that the test docs are a bit outdated.  Updating them with new info.
> Update test/README with new info

- Schutzfile
and restore the repos to the f39 section, they were moved to the new f40 section on accident.
> Schutzfile: Bump the f40 osbuild commit

- pkg/manifest/raw_bootc.go
- pkg/manifest/raw_bootc_test.go
Currently creating a customization for the root user does not work because `/var/roothome` may not be avaialble in the image. This commit ensures it is created if needed just like we do for `/var/home`.
Closes https://github.com/osbuild/bootc-image-builder/issues/143
[edit: to (end-to-end) test I pointed https://github.com/osbuild/bootc-image-builder/pull/363 to this branch]
> manifest: ensure /var/roothome is available when needed

- .golangci.yml
- pkg/dnfjson/dnfjson.go
- pkg/dnfjson/dnfjson_test.go
- pkg/osbuild/osbuild-exec.go
adding context to help pin down possible errors
> Improve error descriptions

- .github/workflows/tests.yml
> Run unit tests also on c10s (COMPOSER-2161)

- README.md
> readme: update dicussion link

- .golangci.yml
> linter: exclude vendor/ directory

- tools/gen-manifests-diff
> tools: fix ppc64le typo

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
Use fedora:latest for devcontainer
Install project dependencies into devcontainer during build
Download all necessary go modules during devcontainer first run
> Update devcontainer configuration

- pkg/rhsm/secrets.go
Image builder CLI currently does not build RHEL images and errors out with missing subscription error. This patch extends RHSM secrets utility function to search for entitlement certificate in runtime directory and then falls back to regular directory.
When a RHEL container is executed via podman, it automatically mounts subscription files making them available for RHSM running in UBI containers so it can access Red Hat repositories. Images can leverage this and simply use the X509 entitlement cert to access RHEL bits on CDN automatically.
When this is merged:
```
/run/secrets/
/run/secrets/etc-pki-entitlement
/run/secrets/etc-pki-entitlement/941581227453314952-key.pem
/run/secrets/etc-pki-entitlement/941581227453314952.pem
/run/secrets/redhat.repo
/run/secrets/rhsm
/run/secrets/rhsm/ca …
```
> rhsm: support for podman secrets

- pkg/osbuild/udev_rules_stage.go
- pkg/osbuild/udev_rules_stage_test.go
When we move `ImageConfig` into YAML we will need support for the `UdevRulesStageOptions`.
This commit adds support for JSON/YAML unmarshaling.
This is split out from https://github.com/osbuild/images/pull/1462
> osbuild: add JSON/YAML unmarshal to UdevRulesStageOptions

- pkg/distro/defs/fedora/distro.yaml
- pkg/distro/defs/loader.go
- pkg/distro/defs/loader_test.go
- pkg/distro/defs/rhel-8/distro.yaml
- pkg/distro/fedora/distro.go
- pkg/distro/fedora/package_sets.go
- pkg/platform/yaml.go
- pkg/platform/yaml_test.go
This PR moves all image types into pure YAML.
> fedora: move all image types into pure YAML

- pkg/disk/filesystem.go
- pkg/image/bootc_disk.go
- pkg/image/bootc_disk_test.go
- pkg/osbuild/mkfs_stage.go
This is some follow ups from  review in https://github.com/osbuild/images/pull/1519
> Cleanup of new APIs (mkfs options and build container)

- pkg/image/bootc_disk.go
- pkg/manifest/build.go
When a build container is used it generally supposed to be "similar" to the deployed container. I.e. at least based on the same distro, etc. However it doesn't have to be exactly the same configuration. For example, the target container may list a custom kargs in the bootc install config, or custom composefs/fs-verity options in the ostree prepare-root.conf file.
To ensure that such customization in that target image is picked up we copy these files from the target container to the build container.
> image: If using a separate build container, copy bootc customization to it

- pkg/manifest/os_test.go
- pkg/manifest/subscription.go
- pkg/manifest/subscription_test.go
These hacks are no longer necessary.
> manifest: remove subscription hacks

- pkg/distro/defs/README.md
- pkg/distro/defs/fedora/distro.yaml
- pkg/distro/defs/loader.go
- pkg/distro/defs/loader_test.go
- pkg/distro/defs/rhel-10/distro.yaml
- pkg/distro/defs/rhel-8/distro.yaml
- pkg/distro/defs/rhel-9/distro.yaml
distro: add initial README.md for the YAML based image types
This comit adds some basic documentation for the YAML based
image types. It covers the minimal basics and needs expanding
but as Brian pointed out [0], we really should have something
here :)
Thanks to Brian for the suggestion.
[0] https://github.com/osbuild/images/pull/1608#discussion_r2165143539
---
distro: rename "merge" to "shallow_merge" in "conditions"
Based on the discussion in
https://github.com/osbuild/images/pull/1600#discussion_r2154092671
this commit renames "merge" to "shallow_merge" in the YAML to
make more clear that this is not doing a deep merge.
Thanks to Thozza for the suggestion.
---
distro: improve condition comments based on Brians feedback
This commit improve some conditions comments based on Brians …
> distro: small tweaks for the YAML based imagetypes

- cmd/osbuild-upload-oci/main.go
- pkg/upload/oci/upload.go
SSIA
In addition, make a few adjustments to make this more of a library code than the client code (logging and struct tags).
/jira-epic HMS-8802
JIRA: [HMS-9042](https://issues.redhat.com/browse/HMS-9042)
> pkg/upload/oci: sync code from osbuild-composer (HMS-9042)

- .github/workflows/tests.yml
Otherwise it sometimes fails or something.
> ci: update apt before installing packages
