osbuild/images

- pkg/osbuild/sysconfig_stage.go
Adds support for configuring `desktop` and `livesys` which is being added in this PR: https://github.com/osbuild/osbuild/pull/1345
> osbuild/sysconfig: `desktop` and `livesys`

- image-types/README.md
- pkg/distro/fedora/distro.go
- pkg/distro/fedora/distro_test.go
- pkg/distro/fedora/images.go
- pkg/distro/rhel8/distro.go
- pkg/distro/rhel8/distro_test.go
- pkg/distro/rhel8/edge.go
- pkg/distro/rhel8/package_sets.go
- pkg/distro/rhel9/distro.go
- pkg/distro/rhel9/distro_test.go
- pkg/distro/rhel9/edge.go
- pkg/distro/rhel9/package_sets.go
- test/cases/minimal-raw.sh
- test/data/ansible/check-minimal.yaml
- minimal-raw image type support for rhel8/9 cs8/9
- fedora already had this image type , just added xz compression stage.
- xz compression brings down the image size from ~3.96GB to  ~700MB.
- updated README.md under image-types/ folder.
- osbuild-composer PR : https://github.com/osbuild/osbuild-composer/pull/3518
> Imagetype: minimal-raw support for rhel8/9 with xz compression

- test/cases/generate-build-config
Check for image type skips in the filter_builds() function, otherwise if only SKIPS are left, the null build is not created.
> Test: fix skip builds

- .github/dependabot.yml
- Group all updates into one PR.
- Limit to one PR at a time (since they're grouped).
- Automatically rebase when needed.
> Group dependabot updates into one PR

- pkg/distro/distro_test_common/distro_test_common.go
- pkg/distro/rhel9/distro.go
- pkg/distro/rhel9/distro_test.go
- pkg/distro/rhel9/edge.go
- pkg/distro/rhel9/imagetype.go
- pkg/image/live.go
- pkg/image/ostree_raw.go
- pkg/manifest/vmdk.go
- test/cases/generate-build-config
- test/config-map.json
This adds the `edge-vsphere` image type for x86_64 and
aarch64. It is based on the `edge-raw-image` but produces
a .vmdk image in order to upload the artifact to vSphere.
This image has Ignition support.
This has been moved from [osbuild/osbuild-composer#3539](https://github.com/osbuild/osbuild-composer/pull/3539)
> Edge vsphere

- .github/dependabot.yml
Followup to #33.
The group requires a sub-object called 'patterns'.
See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
> dependabot: fix groups object format

- .github/workflows/auto-merge-dependabot.yml
If the tests pass, I don't see a reason why not to just merge them.
> github: auto-approve and auto-merge PRs from dependabot

- README.md
Empty out the README. This was the osbuild-composer README; gives us a clean base to start working on.
> readme: empty out

- .github/workflows/tests.yml
Enables actions to run when a merge_group even is triggered, which is used for merge queues.
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
The gitlab CI branch will be named the same as the github branch (`gh-readonly-queue/{base_branch}`), which is descriptive enough, so we don't need a special condition for it in the PR naming of the gitlab CI branch
https://github.com/osbuild/images/blob/2f38765b301f5197dbe3906c990dfffcf91f87ba/.github/workflows/trigger-gitlab.yml#L47-L53
> Run tests on merge_group event for merge queues

- .github/workflows/auto-merge-dependabot.yml
I accidentally left the condition from the example in the code. We actually don't need it, we are happy to merge whatever dependabot proposes.
Since the Dependabot metadata job is no longer needed, I removed it as well.
> github: Remove the bogus condition from the auto-merge job

- pkg/distro/fedora/images.go
Anaconda has implemented automatically starting the webui if the anaconda-webui package is installed. See:
https://github.com/rhinstaller/anaconda/pull/4871
Note: we still conditionally *install* the webui on Fedora 39.
> live-installer: remove kernel argument

- .gitlab-ci.yml
- cmd/build/main.go
- cmd/gen-manifests/main.go
- test/cases/build-image.sh
- test/cases/generate-build-config
- test/config-map.json
- test/configs/ostree-example.json
- test/configs/ostree.json
- tools/ci/push-container.sh
The biggest change for this PR is the change in the way we calculate the manifest ID for our test build cache.
Instead of hashing the manifest contents, use the last stage ID computed from osbuild --inspect.  This has the following advantages:
- It is not affected by formatting (indentation, newlines).
- It is not affected by content URLs when the content is the same.  For example, an ostree commit from a different URL will not affect the stage IDs if the content hash is the same.
This gets around an issue we were going to face when generating manifests from local ostree containers when the IP address or port of the local container changes.  It also lets us stop worrying about the exact format of the manifest file when comparing.
For now, the build config generator checks for both …
> test: Use last stage ID as manifest ID

- pkg/distro/fedora/images.go
- pkg/image/ostree_archive.go
- pkg/manifest/os.go
Disable the installation of weak dependencies in the OS pipeline by propagating it from the image types down.
> iot-commit: do not install weak dependencies

- internal/pathpolicy/policies.go
Allow writing to `/root` and subdirectories in file customizations. This is necessary to support building the KDE live image in a blueprints-defined way. This image wants to write GTK theme configuration into `/root`.
> pathpolicy: `/root` for `CustomFilesPolicy`

- pkg/container/resolver.go
- pkg/container/resolver_test.go
The output of the resolver can be inconsistent. This causes problems with the diff-manifest CI script because consecutive runs on the same code may have different outputs, causing a false manifest diff error from Schutzbot.
The tests was already sorting by Digest, so move that up into Finished() and remove the sort from the test. Now the results will always be in a consistent order.
> resolver: Always return results sorted by Digest

- .github/workflows/tests.yml
- .github/workflows/trigger-gitlab.yml
Run gitlab without waiting for the tests workflow to finish. The trigger-gitlab workflow now only depends on the GitLab workflow which just runs the gitlab helper.
> Run gitlab CI without waiting

- pkg/distro/test_distro/distro.go
Tests using this are all in osbuild-composer, this will be needed for some tests I am currently working on.
> test_distro: Return a 1GiB default size instead of 0

- test/generators/imgtestlib.py
Adds a clickable URL in the job log to the commit when an image configuration was built.
> Add URL to commit when printing build cache info

- internal/oscap/oscap.go
- pkg/blueprint/customizations.go
- pkg/blueprint/customizations_test.go
- pkg/distro/fedora/images.go
- pkg/distro/rhel8/images.go
- pkg/distro/rhel9/images.go
- pkg/manifest/os.go
- pkg/osbuild/oscap_autotailor_stage.go
- pkg/osbuild/oscap_autotailor_stage_test.go
- pkg/osbuild/oscap_remediation_stage.go
- test/config-map.json
- test/configs/all-with-oscap.json
This pull request adds autotailoring support for openscap customizations.
These customizations allow users to override specific OpenSCAP rules which
are passed to the autotailor stage which is responsible for creating the tailoring
file.
> OpenSCAP autotailoring stage

- test/cases/build-image.sh
- test/generators/check-build-coverage
- test/generators/generate-build-config
- test/generators/generate-ostree-build-config
- test/generators/imgtestlib.py
In addition to the build info, also store the manifest and the actual image by uploading the whole build directory to s3.
We should start using these images for further testing in other projects, like osbuild-composer and maybe to bring back image info in manifest-db without needing to rebuild every time.
This PR will cause a rebuild of all image types since the build cache directory structure is changing.
> Store images in S3 after building

- .github/workflows/auto-merge-dependabot.yml
I wonder if this is why the checks don't run on the merge queue when the github action is doing the merge.
> github: change the bot merge method to rebase

- pkg/distro/fedora/imagetype.go
- pkg/distro/rhel8/distro_test.go
- pkg/distro/rhel8/imagetype.go
- pkg/distro/rhel9/imagetype.go
- pkg/ostree/errors.go
- pkg/ostree/ostree.go
- pkg/ostree/ostree_test.go
If a ref to be resolved is already a checksum, just copy it to the checksum field and don't resolve.  This is only valid for parent refs.  Image refs that look like checksums will be caught by a new Validate() function.
Supporting checksums for parent refs means that users can specify a parent ostree commit that is not the head of a branch.
Resolves COMPOSER-1976
See also https://github.com/osbuild/osbuild-composer/issues/3107
> Support checksums for ostree parents when building ostree commits

- test/generators/imgtestlib.py
It seems the tests and the specifically the test case generators aren't as stable as I thought.  Some network flakiness can occur at times and they probably went unnoticed before due to the retries, making it look like it was all stable.
This reverts commit dd14277c09d257661441bf7c8297ba84bae56e29.
> Enable test retries (1 retrry)

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
There is no rpm for images, so we drop all rpm related bits. This also means we need to include the `gpgme-devel` dependency explicitly.
Update the container from f36 to f38.
> devcontainer: update to work for images

- test/generators/configure-generators
Using the 'needs' keyword [1], a job will start as soon as its dependency is done, without waiting for the whole previous stage to finish.  This means that build jobs will start as soon as the corresponding generate jobs are done (i.e. for the same distro-arch), ostree-generators will run as soon as the corresponding build jobs are done, and ostree-build jobs will run as soon as the corresponding ostree-generators are done.
This might speed up execution in cases where one generator job takes longer than usual, for whatever reason, and ends up not generating any builds, whereas another generator job finishes early and does generate builds.
[1] https://docs.gitlab.com/ee/ci/yaml/index.html#needs
> test: ignore stage ordering for distro-arch jobs

- .github/workflows/create-release.yml
- .github/workflows/create-tag.yml
Set up GH action to perform releases every Monday at 5 AM UTC. Use semantic versioning and bump only the minor version part of it.
> Set up weekly releases

- pkg/manifest/ostree_deployment.go
- pkg/osbuild/systemd_preset_stage.go
- pkg/osbuild/systemd_preset_stage_test.go
Extend the `OSTreeDeployment` pipeline implementation to enable / disable services also using systemd presets in case Ignition is being used.
The pipeline already enables / disables services using the Systemd stage, which calls `systemctl`, but on some systems (since Fedora 37), Systemd will reset all enabled / disabled services based on system presets on first boot. This is not a problem for our images in general, since they contain fake machine-id, which makes systemd think that the system is not booting for the first time. This is however not the case when Ignition is being used, since it signals to systemd to treat the first boot as an actual first boot.
Enabling systemd services using `systemctl` is still kept in the pipeline, since the end result will be the same even if services …
> Enable / disable services also using presets for OSTree deployment images if Ignition is used.

- pkg/osbuild/osbuild-exec.go
This will enable the osbuild-composer worker to embed the version of osbuild used to build the image, into the osbuild job result.
> pkg/osbuild: add OSBuildVersion() to get osbuild version

- pkg/distro/fedora/distro.go
- pkg/distro/fedora/package_sets.go
I took the kickstart from Fedora and reimplemented it here. This should fix a lot of issues like missing cloud-init. Since the kickstart for azure is inheriting the kickstart from the base cloud image, I did the same thing in our code to mimic that.
See
https://pagure.io/fedora-kickstarts/blob/58c856ae882a93362f025b4efae143fbd778edc9/f/fedora-cloud-base-azure.ks
> distro/fedora: align the vhd image to the official version

- pkg/disk/partition_table.go
- pkg/distro/fedora/distro.go
- pkg/distro/fedora/images.go
- pkg/distro/fedora/package_sets.go
- pkg/distro/fedora/partition_tables.go
- pkg/distro/image_config.go
- pkg/distro/rhel7/images.go
- pkg/distro/rhel8/edge.go
- pkg/distro/rhel8/images.go
- pkg/distro/rhel8/package_sets.go
- pkg/distro/rhel9/edge.go
- pkg/distro/rhel9/images.go
- pkg/distro/rhel9/package_sets.go
- pkg/platform/aarch64.go
These are some fixes for the minimal image that are needed to fix up a few minor issues.
Signed-off-by: Peter Robinson <pbrobinson@gmail.com>
> System Ready Minimal Images fixes

- pkg/disk/partition_table.go
- pkg/distro/fedora/distro.go
- pkg/distro/fedora/images.go
- pkg/distro/fedora/package_sets.go
- pkg/distro/fedora/partition_tables.go
- pkg/distro/image_config.go
- pkg/distro/rhel7/images.go
- pkg/distro/rhel8/edge.go
- pkg/distro/rhel8/images.go
- pkg/distro/rhel8/package_sets.go
- pkg/distro/rhel9/edge.go
- pkg/distro/rhel9/images.go
- pkg/distro/rhel9/package_sets.go
- pkg/platform/aarch64.go
#137 cherry picked on top of v0.3.0 for RHEL 9.3.0.
> [RHEL 9.3.0] System Ready Minimal Images fixes

- pkg/distro/fedora/distro.go
During rebase of 3d3649014465603f700cfe4191edcc39ddb64514, this change was missed due to 3d8388edf8c5e7f5b62ef0b5f7d1c7314e7eb2ed.
> distro: fix kernel options for Fedora Azure image

- pkg/distro/fedora/partition_tables.go
This PR fixes [#3529](https://github.com/osbuild/osbuild-composer/issues/3529) , and extends the `iotSimplifiedInstallerPartitionTables` `rootlv` to 8GiB.
> simplified-installer/fedora: extend rootlv size

- pkg/distro/rhel9/gce.go
The grub2-tools-efi package is actually contains tools just for booting Linux on x86 EFI Apple Macs, they're three tools that are uesd for the Mac bless process. The actually useful UEFI tools for normal platforms are contained in the minimal and main tools package so ensure we have the right ones in place for GCE images.
> rhel9: GCE: Add correct grub2 tools for UEFI platforms

- pkg/osbuild/osbuild-exec.go
The version string returned by the `OSBuildVersion()` function contained a trailing newline. Ensure that it is removed.
> osbuild.OSBuildVersion: return version without trailing newline

- pkg/distro/rhel8/distro.go
- pkg/distro/rhel8/edge.go
- pkg/distro/rhel8/partition_tables.go
- pkg/distro/rhel9/distro.go
- pkg/distro/rhel9/edge.go
Remove hybrid boot and all the legacy BIOS partitions from Edge images as UEFI is the only supported boot mechanism.
> Edge remove hybrid boot

- cmd/build/main.go
- cmd/gen-manifests/main.go
- internal/environment/azure.go
- internal/environment/ec2.go
- internal/environment/kvm.go
- pkg/blueprint/blueprint.go
- pkg/distro/fedora/distro.go
- pkg/distro/fedora/images.go
- pkg/distro/fedora/imagetype.go
- pkg/image/disk.go
- pkg/manifest/os.go
- test/config-map.json
- test/configs/minimal-pkgs.json
- test/configs/minimal.json
This PR adds a new feature to the build configuration called `minimal` which affects payload packages in two ways:
- It ignores any statically defined packages for an image type (the packages defined on `ImageType.packageSets`).
- It disables weak dependencies for all payload packages.
The option therefore creates a **minimal** image where the packages installed are only the ones required to boot the image and provide basic functionality according to Platform (for firmware and bootloader configuration for example) and the Environment (`cloud-init` for cloud environment for example), removing any packages from an image type that are added purely by policy.
For the qcow2 (and its derivatives), the enabled services have been removed from the base image type configuration and moved to the …
> Minimal image builds

- pkg/distro/fedora/package_sets.go
`sdubby` conflicts with `grubby` and was excluded in fedora-kickstarts for the live image.
> fedora: exclude sdubby

- pkg/osbuild/result.go
- pkg/osbuild/result_test.go
I would find it nicer if the pipeline and stage names would be separated by a colon in the text format of osbuild output, instead of e.g.:
```
Pipeline build
Stage org.osbuild.rpm
Output:
[/usr/lib/tmpfiles.d/journal-nocow.conf:26] Failed to resolve specifier: uninitialized /etc detected, skipping
All rules containing unresolvable specifiers will be skipped.
...
```
In addition, ensure that there is a newline after each stage results are printed, regardless if there were any metadata to print. This change ensures that each stage results are visually separated by one newline.
The text format is now uploaded to Koji builds, therefore I'm trying to make it a bit easier to read.
> OSBuild result: improve readability of the text format

- pkg/distro/rhel8/ubi.go
When insights-client is included, the file exclusion prevents python3-magic being installed, which is a dependency of insights-client.
---
without the file exclude, insights-client (and rhc) install just fine.
> wsl: don't exclude file package

- cmd/osbuild-playground/my-image.go
- pkg/disk/disk_test.go
- pkg/disk/partition_table.go
- pkg/disk/partition_table_test.go
- pkg/distro/distro.go
- pkg/distro/fedora/imagetype.go
- pkg/distro/rhel7/imagetype.go
- pkg/distro/rhel8/imagetype.go
- pkg/distro/rhel9/imagetype.go
- pkg/osbuild/device_test.go
- pkg/osbuild/disk_test.go
This is basically a port of https://github.com/osbuild/osbuild-composer/pull/3222 to images. I *think* this is complete, but I need to clean up the osbuild-composer part first so marking this as a draft for now.
> Partition mode

- test/generators/check-build-coverage
In the check-build-coverage step at the end of the CI pipeline, also collect all the build configurations that were built in the specific pipeline (identified by the CI_COMMIT_SHA) in the build info and print it in the log.
This makes it a tiny bit more convenient to check which images were rebuilt and see if any images weren't rebuilt when they were meant to or were rebuilt when they weren't expected to.
I also considered having Schutzi post the list in the PR, but I think that might get spammy with PRs that get rebased a lot.  Let's rely on the job log for now and see how it goes.
> Print configurations built in CI run

- .gitignore
This will prevent accidental inclusion of static manifest generated for testing.
> Ignore /test/data/manifests directory in git

- .github/workflows/auto-merge-dependabot.yml
Currently, we merge these PRs as the default GitHub Actions bot account.
However, I'm fairly sure that this bot account cannot spawn new actions
as a protection against recursive actions. Thus, the merge train will
fail because no actions will be spawned for it since the train was
created by the default bot.
This commit uses the Schutzbot's token in order to create the merge
train. This should allow GitHub to create the neccessary workflows when
Schutzbot auto-merges the PR.
Since secrets are not available on pull_request workflows, I changed
the trigger to pull_request_target. This shouldn't have any other
effects on the workflow.
> github: Merge dependabot PRs as a proper bot account

- internal/pathpolicy/policies.go
- internal/pathpolicy/policies_test.go
- pkg/distro/fedora/distro_test.go
- pkg/distro/rhel7/distro_test.go
- pkg/distro/rhel8/distro_test.go
- pkg/distro/rhel9/distro_test.go
- Add unit test to test specific mountpoint paths against the mountpoint policy. Replace distro-specific unit tests which were testing basically the same thing, but in which distro. This makes little sense, since all distros use the same mountpoint policy.
- Explicitly disallow mountpoints which can't / shouldn't be on a separate partition.
- Relax the mountpoint policy to allow arbitrary custom mountpoints and adjust the unit test accordingly.
Related to https://issues.redhat.com/browse/COMPOSER-2030
> Support arbitrary custom mountpoints

- .gitlab-ci.yml
- test/scripts/check-build-coverage
- test/scripts/configure-generators
- test/scripts/imgtestlib.py
- test/scripts/upload-results
This PR makes two small changes to the test pipelines:
1. Adds the PR number to the build info when a new image is built.  This number is printed when filtering builds to make it easier to determine why image builds are skipped and it's also used to list images build in all pipelines of a given PR in the `check-build-coverage` jobs.  Eventually, we can use this information to add messages to the PR so it's easier to track what is being built by each pipeline run.
2. Puts the rpmmd and build info cache in the working directory and configures build pipeline generators to share that cache.  This should speed up test generation.  It'll be especially good for speeding up depsolving for manifest generation.
> test: Add PR number to build info and share test caches

- internal/pathpolicy/policies.go
- internal/pathpolicy/policies_test.go
> Deny additional mountpoint paths symlinked to /run

- cmd/osbuild-pipeline/main.go
- pkg/blueprint/customizations.go
- pkg/osbuild/cloud_init_stage_test.go
- pkg/osbuild/dnf_automatic_config_stage_test.go
- pkg/osbuild/dnf_config_stage_test.go
- pkg/osbuild/gcp_guest_agent_conf_stage_test.go
- pkg/osbuild/modprobe_stage_test.go
- pkg/osbuild/oscap_autotailor_stage_test.go
- pkg/osbuild/oscap_remediation_stage_test.go
- pkg/osbuild/sshd_config_stage_test.go
- pkg/osbuild/systemd_journald_stage_test.go
- pkg/osbuild/tar_stage_test.go
- pkg/osbuild/yum_config_stage_test.go
- pkg/osbuild/yum_repos_stage_test.go
- pkg/rpmmd/repository.go
Fix all instances of gosec G601: Implicit memory aliasing in for loop.
(cherry picked from commit 9a445e6af94e209a786695b315cc9adf8f2e383c)
> Fix implicit memory aliasing in for loops

- test/scripts/generate-ostree-build-config
The ostree build tests are currently broken.
This is the same change made for the non-ostree tests in 1dac638e4796da5b7feeda1e87a5b5fef3750a34.  The ostree test config generation was missed in PR #188.
> test: fix script paths for ostree builds

- cmd/gen-manifests/main.go
- test/scripts/generate-ostree-build-config
The gen-manifest accepts an image config map via the `-config` option,
which is good for CI and testing purposes.
However, imagine a situation when:
- you are making changes to code in the repository which affects
generated manifests,
- you want to use a custom image config to test these changes and
generate manifests to build them using osbuild
In this case, one can filter out distro / arch / image type using the
`gen-manifest` CLI options, instead of creating the image config map.
Passing an ad-hoc image config to `gen-manifests` on the CLI to use for
all image types and filtering what gets generated using the CLI options
is IMO much nicer (or easier to use) for development, than the current
approach (which involves basically creating two JSON files and editing
one of them each time one …
> gen-manifest: add a shortcut option for providing single image config

- pkg/manifest/raw_ostree.go
- pkg/osbuild/copy_stage.go
- pkg/osbuild/device.go
- pkg/osbuild/device_test.go
The ability to create arbitrary mountpoints under the filesystem root revealed an issue in the code generating device names for mount options of osbuild stages. Specifically, it would generate the same device name for `/` and `/root` mountpoints. Moreover, other places were making assumptions which should not be relied on, e.g.:
- `GenCopyFSTreeOptions()` could happily replace existing device mount with a different device, but the same name.
- `GenCopyFSTreeOptions()` expected that the mount name for entity with `/` mountpoint will be always called `root`.
- `RawOSTreeImage.serialize()` expected that the mount name for entity with `/` mountpoint will be always called `root`.
Remove these assumptions from the code and explicitly check for device name conflicts.
Rework the function escaping …
> osbuild: rework device mount names handling

- test/scripts/generate-ostree-build-config
Currently the configurations with dependencies are filtered
based on the "depends" field presence only. This makes
configurations from other distros to be processed even
when they are not relevant.
> fix: filter non relevant configurations with dependencies

- test/scripts/generate-ostree-build-config
Following up from #260, this PR also filters the config map on the architecture.
> test: filter on architecture as well when generating config map of dependencies

- test/configs/all-customizations.json
Modify the `all-customization.json` image config to generate testing manifests with more comprehensive list of custom (and arbitrary) mountpoints.
> Test/all-customizations: add more custom mountpoints

- test/scripts/generate-ostree-build-config
Support globs in distro and image filtering.
Currently distro filters like `rhel-8*` or arch
filters like `*64` don't work as expected.
> Support globs in distro and image filtering

- Schutzfile
- pkg/blueprint/customizations.go
- pkg/distro/rhel9/images.go
- pkg/distro/rhel9/imagetype.go
- pkg/image/anaconda_ostree_installer.go
- pkg/image/ostree_disk.go
- pkg/manifest/ostree_deployment.go
- pkg/osbuild/fips.go
- pkg/osbuild/update_crypto_policies_stage.go
- test/config-map.json
- test/configs/edge-ostree-pull-device-fips.json
- test/configs/edge-ostree-pull-fips.json
- test/configs/edge-ostree-pull-user-fips.json
- test/scripts/boot-image
Defines a new `fips` blueprint customization to enable the system FIPS mode on the generated images.
Enables `fips` blueprint customization support for the following images: 
- Edge images based on OSTree deployments:
- `edge-raw-image`
- `edge-simplified-installer`
- `edge-vsphere`
- `edge-ami`
- Edge images based on the Anaconda OSTree installer:
-  `edge-installer`
Depends on osbuild/osbuild/pull/1443
> Enable system FIPS mode for Edge Images

- pkg/distro/rhel9/bare_metal.go
For installers (both Anaconda and CoreOS) on RHEL 9, we define a couple of dracut modules that rely on packages that are pulled in as weak dependencies of other packages in the installer package set.  Let's define these explicitly instead.
For other packages that are required by other modules, let's still rely on package "hard" dependencies that are already defined.
In the future, we should derive the required packages dynamically from the dracut modules defined in the pipeline.
I've verified this works by applying the following patch and building installers:
```diff
diff --git a/pkg/manifest/anaconda_installer.go b/pkg/manifest/anaconda_installer.go
index 0d5c10037..2719d76b6 100644
--- a/pkg/manifest/anaconda_installer.go
+++ b/pkg/manifest/anaconda_installer.go
@@ -149,7 +149,7 @@ func …
```
> RHEL9: Add packages for dracut modules explicitly (don't rely on weak dependencies)

- pkg/image/anaconda_ostree_installer.go
Enable FIPS mode setup for the edge-installer when
booted in legacy BIOS mode.
> feat: enable FIPS for edge-installer with BIOS

- test/configs/edge-ostree-pull-user.json
- test/configs/iot-ostree-pull-user.json
- test/configs/user-customizations.json
The CI key was replaced with a FIPS compliant SSH key.  We need to set it in all the test configs.
> test/configs: update public ssh key

- pkg/arch/arch.go
- pkg/arch/arch_test.go
This is useful to parse architectures stored in the jobqueue.
> pkg/arch: get architecture from string

- test/scripts/upload-results
We've been saving the PR number to the build cache metadata by reading the branch name in GitLab CI, but the branch name is prefixed with `PR-`.  Save it as a plain number so we can use it for links etc.
> Strip PR prefix from PR number in build cache

- pkg/osbuild/ostree_deploy_container_stage_test.go
Follow-up to #272.  Small validator test case refinement (addressing review comments).
> Expected error messages for ostree.deploy.container test

- pkg/osbuild/rpm_stage_test.go
Instead of printing the metadata do some basic precondition checks and stop printing. The (no longer) printed data was:
```
Result: &osbuild.PipelineMetadata{"org.osbuild.rpm":(*osbuild.RPMStageMetadata)(0xc0005b71d0)}
```
> osbuild: remove unneccessary debug print during the test

- internal/assertx/testify_extensions.go
- internal/assertx/testify_extensions_test.go
- pkg/osbuild/skopeo_source.go
- pkg/osbuild/skopeo_source_test.go
When trying to create enough data for a full pipeline run for https://github.com/osbuild/images/pull/287 I struggled a bit because it was not clear which items where faulty.
This commit adds more context to the errors. Sadly I had to implement `assertPanicsWithErrorRegexp` because of https://github.com/stretchr/testify/issues/1304
I can contribute it upstream but for that it needs some tests around it first :)
> osbuild: include context in skopeo error messages

- dnf-json
- pkg/blueprint/repository_customizations.go
- pkg/dnfjson/dnfjson.go
- pkg/dnfjson/dnfjson_test.go
- pkg/osbuild/yum_repos_stage.go
- pkg/rpmmd/repository.go
Adds module_hotfixes flag to all repo types so it can be used during osbuild. This enables users to disable modularity filtering on specific repositories.
relates to: https://github.com/osbuild/osbuild-composer/pull/3821
> rpmmd: add module_hotfixes flag to RepoConfig

- pkg/dnfjson/dnfjson_test.go
- pkg/rpmmd/repository_test.go
This is a regression test for an issue found during the review of PR#284 [0]. The issue was that
```
ModuleHotfixes *bool    `json:"module_hotfixes"`
```
lacked the required `omitempty` which may cause issues with dnfjson.
As a quick and easy way to prevent this in the future this commit adds a small test that ensures that we notice any missing `omitempty`.
Note that the `rpmmd` part is not strictly needed but it feels more correct to do the check in both places that use a repoConfig.
[0] https://github.com/osbuild/images/pull/284#discussion_r1414048979
> pkg: test that "empty" RepoConfig marshal to "empty" json

- pkg/distro/fedora/distro.go
- pkg/distro/fedora/images.go
- pkg/distro/rhel7/distro.go
- pkg/distro/rhel7/images.go
- pkg/distro/rhel8/images.go
- pkg/distro/rhel8/imagetype.go
- pkg/distro/rhel9/images.go
- pkg/distro/rhel9/imagetype.go
- pkg/manifest/os.go
- pkg/osbuild/oscap_autotailor_stage.go
- pkg/osbuild/oscap_autotailor_stage_test.go
- pkg/osbuild/oscap_remediation_stage.go
- pkg/osbuild/oscap_remediation_stage_test.go
The OpenSCAP remediation stage has been reworked to operate in three
stages:
1. Scan the filesystem tree and save results 
2. Generate the remediation script 
3. Run the offline remediation.
Steps one and two both require a data directory for the output that is then used by the next step. This PR creates the necessary config options and enables compression for the results file, since the file could be potentially quite large.
> OpenSCAP results compression

- cmd/osbuild-playground/my-container.go
- cmd/osbuild-playground/my-image.go
- pkg/image/anaconda_live_installer.go
- pkg/image/anaconda_ostree_installer.go
- pkg/image/anaconda_tar_installer.go
- pkg/image/archive.go
- pkg/image/container.go
- pkg/image/disk.go
- pkg/image/export_test.go
- pkg/image/ostree_archive.go
- pkg/image/ostree_container.go
- pkg/image/ostree_disk.go
- pkg/image/ostree_disk_test.go
- pkg/image/ostree_simplified_installer.go
- pkg/manifest/build.go
- pkg/manifest/build_test.go
- pkg/manifest/os_test.go
One objective for bifrost images is that it should be possible to run osbuild inside a container. This can interfere with the selinux policies of the buildroot.
Inside the container everything is labeled
`system_u:object_r:container_files_t`. Labeling /usr/bin/osbuild as `osbuild_exec_t` is not possible in the general case because the host may not have `osbuild-selinux` installed that contains this type. The workaround is that the container labels osbuild itself as `install_exec_t`. This works fine however there is a selinux denial warning when the `{,u}mount` binary is called because the transition from `install_t`->`mount_t` is not allowed. The warning is "harmless" because `install_t` has enough privs to allow the `{,u}mount` binaries to work.
To silence this warning we can label …
> image: add new `ContainerBuildable` flag to OSTreeDiskImage (HMS-3141)

- .gitlab-ci.yml
- pkg/manifest/anaconda_installer.go
- pkg/manifest/anaconda_installer_iso_tree.go
- pkg/osbuild/kickstart_stage.go
Draft PR for some CI goodness.
> `ostreecontainer` for kickstart stage.

- pkg/blueprint/customizations.go
- pkg/customizations/fdo/fdo.go
- pkg/image/ostree_simplified_installer.go
Makes necessary changes for 'fdo.di_mfg_string_type_mac_iface' variable to be passed to manufacturing-client.service when the manufacturing-client is run via the simplified-installer.
> Enables 'fdo.di_mfg_string_type_mac_iface' variable passing

- internal/pathpolicy/policies.go
- internal/pathpolicy/policies_test.go
- pkg/distro/rhel9/distro_test.go
- pkg/distro/rhel9/imagetype.go
- test/config-map.json
- test/configs/ostree-filesystem-customizations.json
- test/scripts/boot-image
This PR enables File system customization for edge-raw-image.
> RHEL 9: Filesystem customizations for edge-raw-image

- pkg/distro/fedora/distro.go
- pkg/distro/fedora/distro_test.go
- pkg/distro/fedora/images.go
- pkg/distro/fedora/imagetype.go
- pkg/distro/rhel8/edge.go
- pkg/distro/rhel8/images.go
- pkg/distro/rhel8/imagetype.go
- pkg/distro/rhel9/images.go
- pkg/image/anaconda_tar_installer.go
- pkg/manifest/os.go
- pkg/osbuild/fips.go
- test/config-map.json
- test/configs/all-with-fips.json
- feat: enable FIPS customization in OS pipeline
- feat: enable FIPS customization in Anaconda tar installer
- feat: Enable FIPS customization for RHEL 9
- feat: Enable FIPS customization for RHEL 8
- feat: Enable FIPS customization for Fedora
> FIPS on Fedora and RHEL 8/9 images

- pkg/osbuild/containers_input.go
I noticed this while working on adding support for build roots from container inputs. It looks like an oversight but I wanted to open it as it's own PR so that it does not get lost in the noise of the followup :)
Draft for now as I want to see the testsuite finish first (locally everything seems fine and AFACIT nothing imports this type but maybe I'm missing something?).
---
This commit removes the unused ContainersInputs and moves the `isStageInputs()` function to `ContainersInput` (not the missing *s* at the end).
The type/function looks like an oversight/leftover, I did a `git grep` and `grep -r` accross our repos and AFAICT the type is not used.
> osbuild: remove unused `ContainersInputs` (note the *s*)

- test/scripts/imgtestlib.py
- test/scripts/upload-results
Default S3 bucket is now a dedicated one for the repo's CI cache called 'images-ci-cache'.
Use the value from the imgtestlib module in the upload-results scripts too.  Now the default bucket name is only specified in one location.
> test: change default S3 bucket

- .github/workflows/tests.yml
- .pylintrc
- Schutzfile
- cmd/build/main.go
- cmd/gen-manifests/main.go
- internal/cmdutil/rand.go
- internal/cmdutil/rand_test.go
- test/scripts/boot-image
- test/scripts/build-image
- test/scripts/check-build-coverage
- test/scripts/generate-build-config
- test/scripts/generate-ostree-build-config
- test/scripts/imgtestlib.py
- test/scripts/test_imgtestlib.py
- test/scripts/upload-results
The primary purpose of this PR is to configure a random seed value in the Schutzfile for CI builds and manifest generation.  The seed is used for deterministic builds in CI using the gen-manifests and build tools while also allowing the tools to generate manifests and images with unique values for UUIDS etc.  It also lets us change the value to manually force a complete rebuild of the cached CI images when we need to.  For example, if we want to change some part of the test scripts or infrastructure that wouldn't generate different manifests but want to make sure everything is rebuilt and tested.  We might also add a scheduled action to trigger rebuilds on a regular basis (e.g., every weekend).
Other changes in this PR:
- pylint configuration.
- pylint GitHub action for test scripts.
- …
> Set RNG seed for tests

- pkg/image/anaconda_container_installer.go
- pkg/manifest/anaconda_installer.go
- pkg/manifest/anaconda_installer_iso_tree.go
Based on: #315
This introduces a new image that installs a bootc bootable container with Anaconda.
> anaconda: container installer

- pkg/osbuild/container_deploy_stage.go
- pkg/osbuild/container_deploy_stage_test.go
This commit adds support for the new `org.osbuild.container-deploy` stage (see https://github.com/osbuild/osbuild/pull/1509).
> osbuild: add new ContainerDeployStage for org.osbuild.container-deploy

- pkg/osbuild/container_deploy_stage.go
- pkg/osbuild/containers_input.go
- pkg/osbuild/ostree_deploy_container_stage.go
[only the second commit is new in this PR]
While writing tests to ensure the that the `ContainerDeployInputs`
generates the correct json I noticed that this was more involved
than I had hoped and it seems there are some indirections in the
code that may not be necessary. I removed them and IMHHO the code
is now a bit more direct and easier to read.
Feedback very welcome!
Build on top of https://github.com/osbuild/images/pull/348 (as I wanted the unit tests from it).
> osbuild: simplify containers_input.go

- pkg/image/bootc_disk.go
- pkg/image/bootc_disk_test.go
- pkg/image/export_test.go
- pkg/image/ostree_disk.go
- pkg/image/ostree_disk_test.go
- pkg/manifest/anaconda_installer.go
- pkg/manifest/anaconda_installer_iso_tree.go
- pkg/manifest/build.go
- pkg/manifest/build_test.go
- pkg/manifest/coi_iso_tree.go
- pkg/manifest/commit.go
- pkg/manifest/commit_server_tree.go
- pkg/manifest/coreos_installer.go
- pkg/manifest/efi_boot_tree.go
- pkg/manifest/iso.go
- pkg/manifest/iso_rootfs.go
- pkg/manifest/oci_container.go
- pkg/manifest/os.go
- pkg/manifest/ostree_deployment.go
- pkg/manifest/ostree_encapsulate.go
- pkg/manifest/ovf.go
- pkg/manifest/pipeline.go
- pkg/manifest/qcow2.go
- pkg/manifest/raw.go
- pkg/manifest/raw_ostree.go
- pkg/manifest/tar.go
- pkg/manifest/vmdk.go
- pkg/manifest/vpc.go
- pkg/manifest/xz.go
This branch prepares for allowing to have build roots from container sources. This is a bit of a shortcut PR that is mainly tailored to `bootc-image-builder`. 
Alternatively we could change `InstantiateManifest()` to not take `repos []rpmmd.RepoConfig` but instead something like: 
```go
type RepoContainerStuff struct {
Repos []rpmmd.RepoConfig
Containers []container.SourceSpec
}
type ImageKind interface {
Name() string
InstantiateManifest(m *manifest.Manifest, repoContainer *RepoContainerStuff, runner runner.Runner, rng *rand.Rand) (*artifact.Artifact, error)
}
```
of course with a more sensible name. Happy to do this if that is the preferred way. I will move this out of draft (or close it) once I get feedback on this (or maybe there is a third option).
Once this is available, bib will …
> manifest,images: add new manifest.NewBuildFromContainerSpec and use in new `BootcDiskImage` (HMS-3318)

- pkg/dnfjson/dnfjson.go
- pkg/dnfjson/dnfjson_test.go
Do not fail if `osbuild-depsolve-dnf` is missing.
It also fixes `dnfjson.go` so that the comment (and I think intention) matches the code :)
> dnfjson: skip TestDepsolver() if no osbuild-depsolve-dnf is installed

- test/scripts/build-image
When building in CI, we need to preserve the environment so that the command 'sudo ./bin/build' inherits the rng seed.  Without it, we always end up building images with a random seed which means that our cache is updated with metadata that will never match a subsequent manifest check.
> Run sudo with -E when building images in CI

- test/scripts/imgtestlib.py
When a manifest has already been built, we would assume it was on a PR and print a link to the PR in the info message.  But new manifests can also appear on the merge queue (from the rebase) so let's handle that case too.  We can't link to it directly because the merge queue branch is deleted after it's merged, but the commit ID is enough info to recreate the build conditions if needed and the name of the merge queue branch includes the PR number if more context is needed.
If the PR field is empty, print an appropriate message too.  This shouldn't happen now, the condition was there while old info existed that is all gone now, but let's keep it in case something unexpected happens with the writing of the build info in the future.
> Print more informational branch info for previous builds

- pkg/manifest/anaconda_installer_iso_tree.go
Using `reqpart` in the kickstart automatically handles the hardware specific partitions that are necessary in UEFI or BIOS environments.
Closes #362.
Note that `reqpart` creates `/boot` as XFS.
@cgwalters we'd need to split off the discussion of the duplicate partition definitions in Anaconda, Go-code, and such; where should we take that?
> anaconda: reqpart for container-installer

- pkg/distro/fedora/images.go
- pkg/image/anaconda_ostree_installer.go
- pkg/manifest/anaconda_installer_iso_tree.go
- pkg/osbuild/kickstart_stage.go
Currently the Fedora IoT installer ISO's are not configured to use the upstream repository and instead use the OStree commit included on the installation ISO.  To use the intended upstream remote, users are currently required to run a few `ostree` commands to make the change.
This PR enables the `--remote` option in the iot-installer kickstart to use the repository listed in the `fedora-iot-config` package. 
Signed-off-by: Paul Whalen <pwhalen@fedoraproject.org>
> Fedora: Enable remote in iot-installer kickstart

- test/README.md
Update test/README:
- Add location of test repositories
- Describe the Schutzfile
- Convert any mention of a file or directory to a link
> Describe test repositories and Schutzfile in test README

- pkg/manifest/build.go
- pkg/manifest/build_test.go
This was an oversight in PR#354. Without the container specs for the source are not always generated.
> manifest: add missing `BuildrootFromContainer.getContainerSpecs()` (HMS-3318)

- pkg/osbuild/bootupd_stage.go
- pkg/osbuild/bootupd_stage_test.go
Add support for the new `org.osbuild.bootupd` stage that got added in https://github.com/osbuild/osbuild/pull/1519
> osbuild: add new bootupd stage (HMS-3318)

- .gitlab-ci.yml
- schutzbot/update_github_status.sh
- test/scripts/imgtestlib.py
Never update the GitHub status at the end of a job.  Instead, let the
job retry and if another failure occurs, when everything is done, the
`fail` job will run in the `finish` stage and update the status
accordingly.
Fixes #368
> Report GitLab job failures globally

- pkg/manifest/os.go
- pkg/manifest/ostree_deployment.go
- pkg/osbuild/grub2_stage.go
This function was replaced with NewGrub2StageOptionsUnified() in early 2022 and nothing in this code, osbuild-composer or bootc-image-builder is using it. I would like to delete it therefore.
[draft for now as I am not sure what our policy for API stability is and what else might import the images library]
> osbuild: remove unused `NewGrub2StageOptions()`

- pkg/image/bootc_disk.go
- pkg/image/bootc_disk_test.go
- pkg/manifest/ostree_deployment.go
- pkg/manifest/qcow2.go
This commit allows to use the qcow2 pipeline outside of a build pipeline. The use-case is the `bootc-image-builder` that will use arbitrary containers as buildroots and we cannot assume that they have `qemu-util` installed. And because `bootc-image-builder` is already a container we can install `qemu-util` there and be confident that it will work.
Note that there is one small drive-by one-ine improvement in one of the panics()s. I had a bit of trouble writing the test and this helped me to pinpoint what is missing. Happy to remove it again (as it's not needed for the PR itself).
> image,manifest: allow using the qcow2 pipeline without a build pipeline (HMS-3318)

- pkg/manifest/ostree_deployment.go
ostree: Fix target imgref
If we haven't been passed an ostree remote, don't use it for
verification; just use `ostree-unverified-image` which matches
https://github.com/containers/bootc/pull/230/commits/20d2d6cdc1bb2ddf7f8a6884ad83efaa708b4c65
---
ostree: Use local name when creating deployment
This will address https://github.com/osbuild/bootc-image-builder/issues/69
(But not marking closes because we need to update the vendor there)
---
> Fix ostree deployment target

- pkg/manifest/iso_rootfs.go
- pkg/manifest/raw_ostree.go
- pkg/osbuild/bootupd_stage.go
- pkg/osbuild/bootupd_stage_test.go
- pkg/osbuild/copy_stage.go
- pkg/osbuild/copy_stage_test.go
- pkg/osbuild/mount.go
- pkg/osbuild/stage.go
- pkg/osbuild/zipl_inst_stage.go
A quick drive-by commit for your consideration. I noticed while writing a test for the bootupd stage that the osbuild.Mounts type is not really helping me and hence wonder if we can do away with it. I did a grep and it seems the type is also not used outside images. Feel free to close this is you disagree or are attached to the type but to me the code feels easier to work with without it (and if you agree with this change I would like to see if `osbuild.Device` might also benefit from this).
--- 
The `osbuild.Mounts` type is just an alias to `[]osbuild.Mount` and it feels like it does not add clarity. From the type it's not clear if it's a slice or a map (like `osbuild.Devices`). While it is nice to abstract things away one needs to know it anyway when constructing the type so this commit …
> osbuild: simplify code by removing `osbuild.Mounts type`

- pkg/manifest/iso_rootfs.go
- pkg/osbuild/bootupd_stage.go
- pkg/osbuild/bootupd_stage_test.go
- pkg/osbuild/clevis_luks_bind_stage.go
- pkg/osbuild/copy_stage.go
- pkg/osbuild/copy_stage_test.go
- pkg/osbuild/device.go
- pkg/osbuild/luks2_format_stage.go
- pkg/osbuild/luks2_remove_key_stage.go
- pkg/osbuild/lvm2_create_stage.go
- pkg/osbuild/lvm2_metadata_stage.go
- pkg/osbuild/mkfs_stages_test.go
- pkg/osbuild/sfdisk_stage.go
- pkg/osbuild/sfdisk_stage_test.go
- pkg/osbuild/sgdisk_stage.go
- pkg/osbuild/sgdisk_stage_test.go
- pkg/osbuild/stage.go
- pkg/osbuild/zipl_inst_stage.go
The same idea as in https://github.com/osbuild/images/pull/373 :-) 
--- 
The osbuild.Devices type is just an alias to map[string]osbuild.Device and it feels like it might be easier to expose the map[string]Device directly. From the type it's not clear if it's a map and when using the type it needs to be used like map it seems easiest to expose it directly.
Another benefit of this is that the pointers used are now clearer (IMHO) i.e. no indirections required for maps.
> osbuild,manifest: simplify `osbuild.Devices`

- internal/testdisk/partition.go
- pkg/image/bootc_disk_test.go
- pkg/osbuild/copy_stage.go
- pkg/osbuild/device.go
- pkg/osbuild/device_test.go
The `org.osbuild.copy` stage requires mounts/devices options when
run. Those will also be required by the coming `bootupd` stage.
To prepare for this the helper is extracted and tests added.
There is a second commit that extracts a common `testdisk.MakeFakePartitionTable("/", "/boot")` helper which is not strictly needed but feels nicer.
This is the first split out of https://github.com/osbuild/images/pull/381
> osbuild: extract `genMountsDevicesFromPt` helper

- pkg/image/bootc_disk.go
- pkg/image/bootc_disk_test.go
- pkg/image/ostree_disk.go
- pkg/image/ostree_simplified_installer.go
- pkg/manifest/ostree_deployment.go
- pkg/manifest/raw_ostree.go
- pkg/osbuild/bootupd_stage.go
This commit enables bootupd for the `image.BootcDiskImage` image type.
> many: use bootupd for image.BootcDiskImage

- test/scripts/check-build-coverage
- test/scripts/imgtestlib.py
Followup to #382.  This partially reverts 366d846fd3f749f448594f1f50fdb78d749cd84b.
Return the output from the aws s3 sync command and print it only when running the filter_builds() function, which syncs a limited set of build info.
When running from check-build-coverage, don't print the output since that will download all files and generates too much output for the job log (and isn't very useful).  Also, fail the job if the sync failed since it doesn't make sense to run anything after it and a failure in that job could be a sign that something's wrong.
In the filter_builds() function, don't fail if the sync failed, just let it run and generate a build config for all the image configurations.
> Test: return and print stdout from aws s3 sync only when filtering

- internal/common/fips.go
- internal/common/fips_test.go
- pkg/distro/distro.go
- pkg/distro/distro_test.go
- pkg/distro/fedora/distro_test.go
- pkg/distro/fedora/imagetype.go
- pkg/distro/rhel7/imagetype.go
- pkg/distro/rhel8/distro_test.go
- pkg/distro/rhel8/imagetype.go
- pkg/distro/rhel9/imagetype.go
Show a warning message when building a FIPS enabled image in a non enabled FIPS host
> Add FIPS enabled image warning

- pkg/image/anaconda_container_installer.go
- pkg/image/anaconda_live_installer.go
- pkg/image/anaconda_ostree_installer.go
- pkg/image/anaconda_tar_installer.go
- pkg/image/ostree_simplified_installer.go
While preparing #388 I noticed that we define the efiboot.img partition table in every anaconda-based pipeline, so I decided to pull that out into a function.
----
Add a small helper function for the efiboot.img partition.  In all pipelines where we create an Anaconda installer, we use the same single partition table with the same size, so let's define it in one place.
Note that the variable was incorrectly named `rootfsPartitionTable` in all cases, but it was in fact the pt for efiboot.img.
> image: unify definition for Anaconda efiboot.img

- pkg/distro/fedora/distro.go
- pkg/distro/fedora/distro_test.go
- pkg/distro/fedora/images.go
- pkg/distro/fedora/package_sets.go
- test/config-map.json
- test/scripts/boot-image
- test/scripts/imgtestlib.py
Add new image type and its image function called "bootc-container".  The image function is very similar to the iot commit but enables the BootContainer flag so it exports a bootable base container instead of a tarball of the ostree repo.
The package set for the container mostly replicates the package selection from centos-bootc [1].  Comments are also retained from the original source files to assist in future decisions for modifications.
The two differences from the centos-bootc package set are:
- Kernel not specified: it is selected automatically along with user package selection.
- The packages specified in the user-experience [2] file aren't added.  We want to keep the image definition minimal, and the existing set is already bigger than minimal.
[1] …
> New image type: Fedora iot-bootable-container

- pkg/manifest/build.go
- pkg/osbuild/container_deploy_stage.go
- pkg/osbuild/container_deploy_stage_test.go
When using bootc based images as buildroots we need to exclude the `/sysroot` to prevent selinux errors.
See https://github.com/osbuild/osbuild/pull/1552
> many: exclude /sysroot in bootc container-deploy stage

- pkg/manifest/build.go
- pkg/manifest/build_test.go
Similar as https://github.com/osbuild/images/pull/287 we need to label `/usr/bin/{mount,umount}` as `install_exec_t` to prevent an selinux denial warning when osbuild runs mount/unmount.
See dea1af48 for more details.
> manifest: label `/usr/bin/{,u}mount` correct (HMS-3318)

- pkg/distro/fedora/imagetype.go
- pkg/distro/rhel7/imagetype.go
- pkg/distro/rhel8/imagetype.go
- pkg/distro/rhel9/imagetype.go
- pkg/policies/policies.go
- pkg/policies/policies_test.go
This will allow them to be used along with the
blueprints.CheckMountpointsPolicy() function outside of images itself.
> Move the actual path policies into a public package 'policies'

- pkg/blueprint/blueprint.go
- pkg/distro/fedora/imagetype.go
- pkg/distro/rhel7/imagetype.go
- pkg/distro/rhel8/imagetype.go
- pkg/distro/rhel9/imagetype.go
The `digest` field was incorrectly exposed in the blueprints via 13bf49a. This PR fixes this by removing the field and fixing the conversion from `blueprint.Container` to `container.SourceSpec`.
> pkg/blueprint: remove the container `digest` field

- pkg/distro/fedora/package_sets.go
- test/scripts/configure-generators
Since we were only testing x86_64 and aarch64, the manifests for ppc64le and s390x were never being generated in CI.
Adding new jobs, generated by the same configure-generators script, that just generate these manifests in a new type of child pipeline: generate-manifests-{distro}-{arch}.
These jobs all run on x86_64, but we separate them per distro-arch so they can run in parallel.  The goal is to ensure that at least the manifest generation works for these architectures and the package sets resolve, even if we don't test that they actually build.
----
Removed the `perl` and `perl-interpreter` exclusions from iot-bootable-container for ppc64le and s390x because `/usr/bin/perl` is required by `powerpc-utils` and `s390utils-base`.
> Generate *all* manifests in CI

- pkg/dnfjson/dnfjson.go
Port of https://github.com/osbuild/osbuild-composer/commit/fb1b27c0efddeff7459220289424852641d2b46a
Required for https://github.com/osbuild/osbuild-composer/pull/3828
Previously, the old dnfjson cache dirs for unsupported distributions were deleted in the osbuild-composer binary on startup. This is no longer possible, since the supported distros are determined by loading available repositories. Loading repositories happens in the Weldr API constructor. Move the cleanup code there.
> Move cleaning up old dnfjson cache dirs from composer to Weldr API

- pkg/distro/rhel9/distro.go
- pkg/distro/rhel9/distro_internal_test.go
- pkg/distrofactory/distrofactory_test.go
- pkg/distroidparser/idparser_test.go
Let's gracefully handle the "old" naming scheme without a dot to separate the major and minor version also for two-digit minor versions. RHEL-9 parser is now consistent with RHEL-8. The motivation behind this change is to not introduce any breaking changes within the RHEL-9 major version.
> distro/rhel9: handle two-digit minor version without the dot

- pkg/osbuild/zipl_stage.go
- pkg/osbuild/zipl_stage_test.go
The function is not used in the code and it is also not needed as it will just be equivalent to `new(ZiplStageOptions)` or `&ZiplStageOption{}`. If we can always reintroduce it if we need it with a more meaningful init of the options.
> osbuild: remove the unused NewZiplStageOptions()

- .github/workflows/test-osbuild-composer-intergation.yml
It would be useful to explicitly test if the code change proposed in the PR integrates cleanly to osbuild-composer or if it will require additional work there. The cheapest way to test it is to try to replace the `osbuild/images` ref in the `osbuild-composer@main` and run Golang lint and unit tests.
These test cases should not be blocking. The intention is to provide feedback in the PR, that the author (or someone else) should also work on integrating the images change to osbuild-composer, since it won't be "for free".
> CI: test integration to osbuild-composer as part of PRs

- pkg/manifest/anaconda_installer_iso_tree.go
Basically anaconda/kickstart lacks support for `--target-image` which we need when installing from a container image embedded in the ISO.  Work around it with an injected `%post`.
Closes: https://github.com/osbuild/images/issues/380
> anaconda/ostree: Ensure we set target image reference

- pkg/osbuild/groups_stage.go
- pkg/osbuild/users_stage.go
- pkg/osbuild/users_stage_test.go
We currently duplicate the code that generates the stage options
for users and groups. AFAICT there is no need for this so this
commit just call the existing functions instead of duplicating them.
If we want to remove New{Group,Users}StageOptions() later (which
a previous commit message indicates) we can still do this by just
unexporting or moving the helper.
> osbuild: use New{Group,Users}StageOptions() in  Gen{Group,Users}Stage()

- pkg/osbuild/loopback_device.go
- pkg/osbuild/loopback_device_test.go
- pkg/osbuild/mount.go
- pkg/osbuild/mount_test.go
A tiny PR that will probably be needed to integrate with https://github.com/osbuild/osbuild/pull/1547  
In the work on `bootc install to-filesystem` so far it expects a view of the entire disk (for bootupd). However in https://github.com/osbuild/images/pull/381 with the standalone bootupd integration it was not needed. We can wait with the merge until the osbuild PR is merged and we test this more meaningfully. OTOH it's tiny and does not hurt to have (as there is a coresponding osbuild feature).
The corresponding osbuild PR is https://github.com/osbuild/osbuild/pull/1501
P.S. I can remove [osbuild: move mount_test.go to osbuild_test pattern](https://github.com/osbuild/images/commit/726c3248681505023a5bee64de2d98a289f952f6) is that is undesired (I'm a fan of this pattern but I get that …
> osbuild: add support for partscan/partition

- pkg/image/disk.go
- pkg/manifest/tar.go
- pkg/osbuild/tar_stage.go
> disk(ova): correct archive order

- pkg/distro/image_config.go
- pkg/distro/image_config_test.go
- pkg/distro/rhel8/edge.go
- pkg/distro/rhel8/images.go
- pkg/distro/rhel9/edge.go
- pkg/distro/rhel9/images.go
- pkg/image/anaconda_ostree_installer.go
- pkg/manifest/anaconda_installer_iso_tree.go
In the context of compatibility with edge-management when creating image ISO artifact. 
When creating an ostree user, the user is created with username and ssh-key without a password, the user has no possibility to manage the system as has no password to enter when using sudo command.
Create a sudoer file at first boot stage.
FIXES: https://issues.redhat.com/browse/THEEDGE-3837
> create ostree user sudoers file

- pkg/container/resolver.go
Most go packages return pointers to structs when using `NewFoo()`. But `NewResolver()` does not and AFAICT there is no deep reason for this. I would prefer to return a pointer here, I got tripped up by this in
https://github.com/osbuild/bootc-image-builder/pull/139#discussion_r1479679146
This will be the first part to fix https://github.com/osbuild/bootc-image-builder/pull/139#discussion_r1479679146
I checked the various uses of container.NewResolver() and this does not even seem to require any code change in the current consumers.
> container: make `container.NewResolver()` return a pointer

- test/scripts/imgtestlib.py
- test/scripts/test_imgtestlib.py
- test/scripts/upload-results
Until now, the following scenario would produce unnecessary rebuilds:
- A PR is opened that updates osbuild in `Schutzfile` to `vNew`.
- A manifest is generated with id `abc123`.
- The build info lookup for `abc123` shows that it was built with `vOld` so it's added to the test matrix.
- The new build info is uploaded showing `abc123` was built with `vNew`.
- A different PR runs CI with `vOld` (before the update PR is merged or before this PR is rebased).
- A manifest is generated with id `abc123` again.
- The build info lookup for `abc123` shows that it was built with `vNew` (in the osbuild update PR) but the currently installed version is `vOld` (`!= vNew`) so it's added to the test matrix.
- The new build info is uploaded showing `abc123` was built with `vOld`.
This doesn't just create …
> Include osbuild NEVRA in build info path for test cache

- pkg/distro/image_config.go
- pkg/distro/image_config_test.go
- pkg/distro/rhel8/edge.go
- pkg/distro/rhel8/images.go
- pkg/distro/rhel9/edge.go
- pkg/distro/rhel9/images.go
- pkg/image/anaconda_ostree_installer.go
- pkg/manifest/anaconda_installer_iso_tree.go
- pkg/osbuild/kickstart_stage.go
In the context of compatibility with edge-management when creating image ISO artifact. 
Add missing kickstart options for edge installer
https://issues.redhat.com/browse/THEEDGE-3836
> anaconda: Add unattended kickstart options for edge installer

- .github/workflows/tests.yml
- test/scripts/boot-image
- test/scripts/imgtestlib.py
- test/scripts/test_imgtestlib.py
Write the [bootc-image-builder](https://quay.io/repository/centos-bootc/bootc-image-builder) container ID that we used to build a disk image and boot test bootable containers.  We use this ID to retest bootable container images when the bib container changes to ensure we maintain compatibility.
> Test: rebuild disks from bootable containers when the BIB container changes

- pkg/manifest/os.go
- pkg/manifest/ostree_deployment.go
Make sure the FIPS files are always added to the build
when needed.
Fixes: #407
> Ensure FIPS files are added to the build

- pkg/osbuild/bootc_install_to_filesystem_stage.go
- pkg/osbuild/bootc_install_to_filesystem_stage_test.go
- pkg/osbuild/bootupd_stage_test.go
This PR adds support for `org.osbuild.bootc.install-to-filesystem` from https://github.com/osbuild/osbuild/pull/1547.
> osbuild: add org.osbuild.bootc.install-to-filesystem support

- pkg/blueprint/customizations.go
- pkg/blueprint/installer_customizations.go
- pkg/distro/fedora/distro_test.go
- pkg/distro/fedora/images.go
- pkg/distro/fedora/imagetype.go
- pkg/distro/image_config.go
- pkg/distro/image_config_test.go
- pkg/distro/rhel8/edge.go
- pkg/distro/rhel8/images.go
- pkg/distro/rhel8/imagetype.go
- pkg/distro/rhel9/edge.go
- pkg/distro/rhel9/images.go
- pkg/distro/rhel9/imagetype.go
- pkg/image/anaconda_container_installer.go
- pkg/image/anaconda_ostree_installer.go
- pkg/image/anaconda_tar_installer.go
- pkg/manifest/anaconda_installer.go
- pkg/manifest/anaconda_installer_iso_tree.go
- pkg/manifest/anaconda_installer_iso_tree_test.go
- pkg/osbuild/kickstart_stage.go
- test/config-map.json
- test/configs/unattended-iso-edge.json
- test/configs/unattended-iso-iot.json
- test/configs/unattended-iso.json
Followup to #417 and #436.
This PR makes the two new installer options configurable in the blueprint. A new section is added called Installer with two options:
- unattended: adds options to the kickstart to make the installation fully unattended.
- wheel-sudo-nopasswd: adds a %post section to the kickstart file that creates a sudoers.d drop-in enabling NOPASSWD for the wheel group.
(I'm open to suggestions on option naming)
These options are required as part of the RHEL Edge service migration.  I enabled the options for all Anaconda-based installers except the Fedora live installer.
Note that in the two previous PRs, the options were enabled by default for Edge installers.  This is a major default image configuration change to be done by default, so we decided it needed to be a …
> Add customizations for building unattended Anaconda installers

- pkg/osbuild/bootc_install_to_filesystem_stage.go
- pkg/osbuild/bootc_install_to_filesystem_stage_test.go
Add the missing inputs to boots.install-to-filesystem - they are required because boots needs to know what container to deploy.
> osbuild: add missing inputs to boots.install-to-filesystem

- pkg/manifest/raw_ostree.go
- pkg/osbuild/bootupd_stage.go
- pkg/osbuild/bootupd_stage_test.go
- pkg/osbuild/device.go
The `bootupd` and `bootc install to-filesystem` stages require a
continous disk so that grub can install the bootloader onto the
disk. This means that the new `partscan` feature from [0] must be
used when generating the disk instead of the current approach that
generates a bunch of loopback devices for each partition.
Note that this version of the code does not implement support
for "container" partition tables like LUKS.
[0] https://github.com/osbuild/osbuild/pull/1501
> osbuild: generate bootupd mounts to span a single disk via  partscan=True

- Schutzfile
- pkg/distro/rhel8/azure.go
- pkg/distro/rhel9/azure.go
- pkg/osbuild/grub2_legacy_stage.go
- pkg/osbuild/grub2_stage.go
Make sure that the RHEL-8 and RHEL-9 Azure images have the following configuration consistent with the official RHEL documentation:
- kernel commandline 
- modules disabled via modprobe configuration
- grub2 configuration in `/etc/default/grub`
Depends on https://github.com/osbuild/osbuild/pull/1601
Related to https://issues.redhat.com/browse/RHEL-19583
> RHEL: fix Azure images configuration according to documentation

- pkg/distro/rhel8/ami.go
- pkg/distro/rhel8/azure.go
- pkg/distro/rhel8/gce.go
- pkg/distro/rhel9/ami.go
- pkg/distro/rhel9/azure.go
- pkg/distro/rhel9/distro.go
- pkg/distro/rhel9/gce.go
Previously, the auto-registration was explicitly enabled in `rhsm.conf` even for non-RHUI cloud images. These are the images that users can build on-prem or in the hosted service (as vanilla or as customized). However, the feature never really worked for these images.
Stop enabling the auto-registration in rhsm.conf (basically stop touching the configuration at all).
Related to https://issues.redhat.com/browse/COMPOSER-2157
> RHEL-8/9: don't touch rhsm.conf on non-RHUI images.

- pkg/distro/rhel8/partition_tables.go
PR#450 [1] reverted the separate `/boot` partition for x86_64 images, since it was causing issues. However, it also removed the `/boot/efi` partition. These images are supposed to support UEFI boot and are marked as such. This is causing failures when booting these images with UEFI in osbuild-composer CI.
Fix this regression by bringing back `/boot/efi`.
[1] https://github.com/osbuild/images/pull/450
> RHEL-8: fix hybrid boot by bringing back /boot/efi

- pkg/distro/fedora/images.go
Anaconda auto-detects the webui being available in recent versions instead of using the kernel arguments. See the codepath in pyanaconda here: https://github.com/rhinstaller/anaconda/blob/8b5f5920d62bcebfadc06285e9b681d4d36f45d1/pyanaconda/anaconda.py#L209
> fedora: remove webui kernel arguments

- internal/common/distro.go
- internal/common/distro_test.go
- pkg/distro/fedora/distro.go
- pkg/distro/fedora/images.go
- pkg/distro/fedora/package_sets.go
- pkg/distro/rhel8/ami.go
- pkg/distro/rhel8/distro.go
- pkg/distro/rhel9/ami.go
- pkg/distro/rhel9/edge.go
- pkg/distro/rhel9/images.go
Two idioms were being used in `fedora/package_sets.go` and there was a mismatch between which version of Fedora enables the webui.
To improve readability and since it's such a common idiom in our codebase I've also introduced `VersionGreaterThanOrEqual` in `common`.
> More consistent and readable version checks.

- pkg/blueprint/customizations.go
- pkg/blueprint/customizations_test.go
- pkg/distro/fedora/images.go
- pkg/distro/image_config.go
- pkg/distro/rhel7/images.go
- pkg/distro/rhel8/images.go
- pkg/distro/rhel9/images.go
- pkg/manifest/os.go
- test/configs/all-customizations.json
In some cases we might want to ensure a service is disabled without installing the package to the image. We can workaround this by masking the service instead of disabling it.
> Enabled masked services customization (HMS-3661)

- pkg/container/client.go
- pkg/container/client_test.go
- pkg/container/resolver.go
- pkg/container/spec.go
[split out from https://github.com/osbuild/images/pull/448 to make it easier to review]
his commit simplifies how local containers are resolved. We can read the
storage-path from system config, which makes it possible to remove the
storage-path argument from the blueprints in a later commit.
---
Minor fix to the local container resolver, using `target.Name()` removes
the container's tag, which is undesirable if we are trying to resolve a
container that is not tagged with `latest`.
> container: simplify resolver

- pkg/distro/fedora/package_sets.go
In Fedora 40+ `passwd` is now provided by `shadow-utils`  ( https://bodhi.fedoraproject.org/updates/FEDORA-2024-e07b775e4e )
`podman-plugins` is no longer included in the new release of [Podman 5](https://src.fedoraproject.org/rpms/podman/c/2ab1bb3d2d6b3e9df18449494a081fcbe8044d4c?branch=rawhide) (F40+ as well) .
This PR updates the affected package-sets.
> Fedora: Update package sets for upstream changes

- pkg/distro/fedora/images.go
I saw some of this code while removing the Fedora 37 version gates and code paths and revisited it today. Turns out we don't need any of it anymore to produce working `image-installer`s.
> fedora: anaconda cleanups

- .github/workflows/gitlab-helper.yml
- .github/workflows/trigger-gitlab.yml
We never used the SKIP_CI logic in this repository.  We intend to ake the GitLab workflow a pretty much empty one that's just there to trigger the chain, but we first need to merge this change so it's in main while the PR that changes the trigger workflow runs.
A follow-up PR will drop the SKIP_CI upload artifact bits once this is merged.
Recreated after #493 from a branch on the main repository to get the new workflows running.
EDIT: That didn't work either: https://github.com/osbuild/images/actions/runs/8146383205/job/22264762905
> Simplify GitHub > GitLab trigger workflow

- .github/workflows/gitlab-helper.yml
- .github/workflows/trigger-gitlab.yml
Part 2 of #494.
**github: do nothing in GitLab workflow**
We never used the SKIP_CI logic in this repository.  Make the GitLab workflow a pretty-much-empty one that's just there to trigger the chain.
> Simplify GitHub > GitLab trigger workflow (part 2)

- pkg/distro/fedora/package_sets.go
This PR adds `bootupd` to the `iot-commit` package set in Fedora 40+.
> fedora: add bootupd to iot-commit

- test/config-map.json
- test/configs/bigiso.json
Move the bigiso regression test from osbuild-composer to this repository [1].  The test makes sure that ISOs larger than 4 GiB are buildable (see [2] for original bug report).
[1] https://github.com/osbuild/osbuild-composer/pull/3988
[2] https://bugzilla.redhat.com/show_bug.cgi?id=2056451
> test: add bigiso test config (HMS-3710)

- pkg/image/bootc_disk.go
In BIB, we intend to export multiple images from the same pipeline and this is the expected filename for the raw images.  Set it so that it's always disk.raw even when we're building a qcow2 or other image type.
> image: always set filename for bootc raw pipeline

- pkg/image/bootc_disk.go
- pkg/image/bootc_disk_test.go
- pkg/manifest/ovf.go
- pkg/manifest/tar.go
- pkg/manifest/vmdk.go
BIB PR using this: https://github.com/osbuild/bootc-image-builder/pull/251
---
We want to support generating VMDK for bootc containers too.
> bootc_disk: Add support for vmdk, ova

- pkg/platform/platform.go
- pkg/platform/platform_test.go
During the development of the image pipeline refactor I noticed that the platform code will panic for unset image types. This is a bug and I added a small test to ensure it won't happen again.
[0] https://github.com/osbuild/images/pull/506
> platform: fix panic() when trying to print an unset ImageFormat

- pkg/blueprint/installer_customizations.go
- pkg/distro/fedora/images.go
- pkg/distro/rhel8/images.go
- pkg/distro/rhel9/images.go
- pkg/image/anaconda_ostree_installer.go
- pkg/image/anaconda_tar_installer.go
- pkg/manifest/anaconda_installer_iso_tree.go
- pkg/manifest/anaconda_installer_iso_tree_test.go
- test/configs/unattended-iso-edge.json
- test/configs/unattended-iso-iot.json
- test/configs/unattended-iso.json
Replace the wheel-sudo-nopasswd (bool) installer customization with sudo-nopasswd ([]string).  Users can now specify a list of users or groups (groups must be prefixed with %).  For each element in the array, the kickstart file will create a file that enables sudo with NOPASSWD for that entry.  Each entry is added as a separate file in the sudoers.d drop-in directory.
> Support user-defined entries for sudo NOPASSWD

- pkg/image/bootc_disk.go
- pkg/image/bootc_disk_test.go
The bootc-disk image manifest now always contains all pipelines needed to generate all image types.  This way we can build any combination of disk images depending on what we need to export without needing to conditionally add or remove pipelines.
The Platform no longer needs to be read, since we're generating all of the formats and the architecture depends on the source container.  However, the Platform is still required for specifying the boot mode (enabling or disabling BIOS boot).
The first return value of the InstantiateManifestFromContainers() function, the artifact, was not used and has been removed now.
> Generate the ALL-MANIFEST for bootc disk images

- .github/workflows/tests.yml
Run unit tests on CentOS Stream 9 and 8.  This will catch scenarios where we use Go features or libraries not supported by those distributions.
I intend to mark these as required in the repo config when this PR is merged.
> github: run unit tests on CentOS Stream 9 and 8

- pkg/manifest/raw.go
BootFiles need to be applied on the raw images as well. See #520, this is blocking Fedora.
This is duplicated code from `manifest/raw_ostree`, let's apply it to all images in a followup and properly abstract it out :)
> manifest/raw: apply BootFiles

- pkg/distro/fedora/partition_tables.go
Add the same offsets used for the Fedora Minimal images to increase IoT hardware support.
> Fedora: add partition offsets to IoT images

- test/scripts/imgtestlib.py
Fixing the test can take a while and we want to unblock other PRs.
> test: temporarily disable boot testing bootable containers

- pkg/distro/fedora/images.go
- pkg/distro/fedora/version.go
- pkg/image/anaconda_container_installer.go
- pkg/image/anaconda_live_installer.go
- pkg/image/anaconda_ostree_installer.go
- pkg/image/anaconda_tar_installer.go
- pkg/manifest/anaconda_installer.go
- pkg/manifest/anaconda_installer_iso_tree_test.go
Don't hardcode the `Final` value being passed to the buildstamp stage as reported in #515. We mark Anaconda based images as `Preview` which is inverted `Final`.
In other build systems this information comes from pungi which passes it on to koji which then writes it correctly into the image. I'd like for us to support the same but that would involve passing it down the API so let's start here with a small duplication of efforts.
I could be convinced to call the property `Final` instead so we don't deal with the inversion but it felt more natural to mark images as preview images than saying they're the "final" artifact.
> anaconda: preview

- test/configs/bigiso.json
Reuse the same test password we have for qcow2, which is already in gitleaks and wont get flagged.
> test: replace bigiso test password with existing from qcow2

- .github/workflows/update-bootc-image-builder.yml
- Schutzfile
- test/scripts/boot-image
- test/scripts/imgtestlib.py
- test/scripts/test_imgtestlib.py
- test/scripts/update-schutzfile-bib
After disabling bootable container boot tests in #526, let's fix them and re-enable.
> test: pin bootc-image-builder ref for testing bootable containers

- pkg/distro/fedora/partition_tables.go
The default package set includes the dracut plugin to create a rescue image which is quite large, with that and more than one kernel we run out of space so lets bump boot so we have more room to move.
> fedora: minimal-raw: bump /boot to 1Gb

- .github/workflows/update-bootc-image-builder.yml
BIB changes fast and it's important to know when we break things, even though it's from the other side.  If it's a BIB bug, we can keep the PR unmerged until it's fixed, but it will still be good to know when it happens.
> github: update the BIB reference daily

- pkg/distro/fedora/distro.go
The org.osbuild.grub2 stage has a default timeout of 0 seconds, but Fedora images set this value to 5 instead. Let's do the same for osbuild images.
> fedora: set grub2 timeout to 5 seconds

- Schutzfile
- pkg/distro/rhel9/distro_test.go
- pkg/distro/rhel9/images.go
- pkg/distro/rhel9/imagetype.go
- pkg/image/ostree_disk.go
- pkg/manifest/ostree_deployment.go
- pkg/osbuild/systemd_unit_create_stage.go
- pkg/osbuild/systemd_unit_create_stage_test.go
- test/config-map.json
- test/configs/ostree-filesystem-customizations-installer.json
- test/configs/ostree-filesystem-customizations.json
Filesystem customization  mountpoints does not persists any upgrade due to the property of ostree which only persists data on /var and /etc. This feature will ingest the filesystem customization and create a unit file which can create the required mountpoints if it doesnot exist.
> rhel9: systemd service to create mountpoints for filesystem customizations for edge images

- pkg/policies/policies.go
This pull request adds the paths /usr/local/bin and /var/local/bin to the CustomFilesPolicies in the policies.go file. This allows the specified directories to be accessed according to the defined policies.
> Add /usr/local/{bin,sbin} to CustomFilesPolicies

- pkg/blueprint/customizations.go
- pkg/blueprint/customizations_test.go
- pkg/customizations/users/users.go
- pkg/osbuild/users_stage.go
The ExpireDate field for the `org.osbuild.users` stage of osbuild has been added in https://github.com/osbuild/osbuild/pull/1648. This PR simply extends osbuild/images to support the new field.
> pkg/osbuild: add ExpireDate to users

- pkg/cloud/awscloud/awscloud.go
Implements
* function to list available AWS buckets and 
* function to check bucket permissions
This is a prerequisite for https://github.com/osbuild/bootc-image-builder/issues/220
…not sure why there is no type similar to `type S3Permission string` defined in the upstream library...
> awscloud: implement retrieval of bucket and permissions (HMS-3099)

- .github/workflows/update-bootc-image-builder.yml
The workflow runs daily and the BIB ref doesn't always get updated.  To avoid having workflow failures for this expected use case, which can make it hard to see actual failures, let's just exit early with success when the diff is empty.
Workflow run on this branch: https://github.com/osbuild/images/actions/runs/8402128400/job/23011182941
> github: don't fail workflow if BIB ref hasn't changed

- pkg/dnfjson/dnfjson.go
- pkg/dnfjson/dnfjson_test.go
- pkg/osbuild/curl_source.go
- pkg/rpmmd/repository.go
Support the mtls secret in curl sources. If the worker sets mtls data on non-rhsm repos, make sure we add the mtls secret.
> support org.osbuild.mtls secret in curl source (HMS-3798)

- cmd/boot-aws/main.go
- test/config-map.json
- test/configs/oscap-generic.json
- test/configs/oscap-rhel8.json
- test/configs/oscap-rhel9.json
- test/scripts/base-host-check.sh
- test/scripts/boot-image
Add oscap test configs for RHEL 8 and RHEL 9 with the appropriate datastream option enabled.
These replicate the test configs from the oscap test in osbuild-composer [1].
To fully replace the test in osbuild-composer, this PR also adds support for running the boot test script with the config file as argument.  When an oscap config is detected, it runs some extra checks on the score of the system.
_NOTE: This is a bit quick and dirty but should soon be replaced with a more comprehensive test of all customizations on images during boot_
[1] https://github.com/osbuild/osbuild-composer/blob/073e304978acade8bfa059f00a005402aa037c99/test/cases/oscap.sh
> test: run oscap checks on images with oscap customizations (HMS-3710)

- pkg/image/bootc_disk.go
- pkg/image/bootc_disk_test.go
- pkg/manifest/build.go
- pkg/manifest/export_test.go
- pkg/manifest/pipeline.go
- pkg/manifest/raw_bootc.go
- pkg/manifest/raw_bootc_export_test.go
- pkg/manifest/raw_bootc_test.go
- pkg/osbuild/bootc_install_to_filesystem_stage.go
- pkg/osbuild/bootc_install_to_filesystem_stage_test.go
- pkg/osbuild/container_deploy_stage.go
- pkg/osbuild/container_deploy_stage_test.go
- pkg/osbuild/selinux_stage.go
There are some more customizations that I would love to see considered:
1. kernel commandline append 
2. non-system users (but I know it's a hard problem)
It also requires changes in bib, those are tracked in https://github.com/osbuild/bootc-image-builder/pull/304 and we need to merge the two in tandem to keep things buildable.
> many: switch to `bootc install to-filesystem` (HMS-3453)

- test/scripts/base-host-check.sh
The `results.xml` file is owned by root, chown the file so we can read the results.
Cherry-picked this commit from #547 into it's own PR. See comments in #546
> test/scripts: chown `results.xml`

- Schutzfile
Commit ID for upstream `main` as of right now.
PR #462 adds the new option we included in `org.osbuild.selinux` to the stage options.  This isn't used in any image definition right now except the one for BIB, which we don't attach to any distros so it's not built here or in osbuild-composer.
Let's update osbuild's commit ID separately here so we're consistent (and it's a good opportunity for a mass rebuild).
> Schutzfile: update osbuild dependency

- test/config-map.json
- test/configs/oscap-rhel8.json
- test/scripts/base-host-check.sh
Added additional tailoring rule for `partition_for_dev_shm` which appears to be the rule causing the issues with the `RHEL8.10` boot tests for OpenSCAP configs.
> test/config-maps: re-enable oscap-rhel8 config

- test/scripts/check-build-coverage
The script would check if `now` was not empty when it should have been checking `pr` when listing PRs.
> test: minor fix in check-build-coverage

- pkg/osbuild/ostree_deployment_mount.go
- pkg/osbuild/ostree_deployment_mount_test.go
Add the "Default" and "Source" options to OSTreeMountDeployment. See
- "default" https://github.com/osbuild/osbuild/pull/1553
- "source"  https://github.com/osbuild/osbuild/pull/1535
> osbuild: add new `osbuild.NewOSTreeDeploymentMountDefault()`

- test/scripts/check-build-coverage
- test/scripts/upload-results
**test/check-build-coverage: fix branch comparison**
The PR number is stored in the build info without the "PR-" prefix that
we set in GitLab CI.  We need to remove the prefix for the comparison.
---
**test/upload-results: use removeprefix() instead of lstrip()**
lstrip() is for stripping a class of characters, not removing a string
of text.
---
> Minor fix in check-build-coverage PR reporting

- .github/workflows/test-osbuild-composer-intergation.yml
- .github/workflows/tests.yml
- go.mod
- pkg/image/bootc_disk_test.go
- tools/prepare-source.sh
Go 1.20 is included in all currently supported distro versions.
> go.mod: update to go v1.20

- pkg/distro/host.go
- pkg/distro/host_test.go
This PR adds a new function`distro.ReadOSReleaseFromTree` that can read an os-release(5) from a given tree. This is needed for https://github.com/osbuild/bootc-image-builder/pull/338
> Add ReadOSReleaseFromTree (HMS-3783)

- test/scripts/configure-generators
We don't build ppc64le and s390x in gitlab CI, we only generate the manifests to ensure there's no issues with manifest generation and package selection.  However, we can also validate them using 'osbuild --inspect' to make sure they're at least valid manifests.
> test: inspect manifests in manifest-only jobs

- .github/workflows/tests.yml
- .gitlab-ci.yml
- Schutzfile
- cmd/build/main.go
- cmd/gen-manifests/main.go
- cmd/osbuild-playground/playground.go
- internal/mocks/rpmrepo/rpmrepo.go
- pkg/distro/distro_test.go
- pkg/dnfjson/dnfjson.go
- pkg/dnfjson/dnfjson_test.go
- pkg/image/bootc_disk_test.go
- pkg/manifest/anaconda_installer.go
- pkg/manifest/anaconda_installer_iso_tree.go
- pkg/manifest/anaconda_installer_iso_tree_test.go
- pkg/manifest/build.go
- pkg/manifest/build_test.go
- pkg/manifest/commit_server_tree.go
- pkg/manifest/coreos_installer.go
- pkg/manifest/empty.go
- pkg/manifest/manifest.go
- pkg/manifest/os.go
- pkg/manifest/os_test.go
- pkg/manifest/ostree_deployment.go
- pkg/manifest/pipeline.go
- pkg/manifest/raw_bootc.go
- pkg/manifest/raw_bootc_export_test.go
- pkg/manifest/raw_bootc_test.go
- test/scripts/generate-gitlab-ci
- test/scripts/imgtestlib.py
Support setting a repos directory on the Solver and add it to the depsolve request when set.
Depends on https://github.com/osbuild/osbuild/pull/1674
> dnfjson: support new osbuild-depsolve-dnf options for loading repositories from a root dir

- pkg/distro/fedora/version.go
In #522 I implemented a naive way to show/not-show pre-releases in installers. Since Fedora 40 is currently building RCs and Finals it should be turned off for 40 now.
> fedora: we're building RCs for F40

- pkg/image/bootc_disk.go
- pkg/image/bootc_disk_test.go
- pkg/manifest/raw_bootc.go
- pkg/manifest/raw_bootc_test.go
- pkg/osbuild/bind_mount.go
- pkg/osbuild/bind_mount_test.go
[draft as this needs https://github.com/osbuild/osbuild/pull/1711 first (and agreement that this is the way to do it]
[draft also because it should have *some* tests at least that the right pipeline is generated]
This commit implements filesystem customizations for images that got generated via `bootc install to-filesystem` via the new `org.osbuild.bind` mechanism.
First the image is written via the `bootc.install-to-fs` stage, then the image is mounted, the ostree.deployment stage is used to get the right deployment and finally the mount is put over the "tree" directory via the bind mount module. This way for the users and selinux stages nothing changes, they work as before on a normal tree (that just happens to be mounted from an image this time).
It also includes a stage to make the …
> many: redo customizations in a `bootc install to-filesystem` world (HMS-3453) 

- pkg/image/bootc_disk.go
- pkg/image/bootc_disk_test.go
- pkg/manifest/raw_bootc.go
- pkg/manifest/raw_bootc_test.go
[build on top of https://github.com/osbuild/images/pull/571, only the last commit is relevant]
When porting custoizations to the new `bootc install to-filesystem`
world initially only users/kernel-options where added. This commit
adds `org.osbuild.groups` now as well.
Needs:
https://github.com/osbuild/osbuild/pull/1726 or 
https://github.com/osbuild/osbuild/pull/1727
> image,manifest: add support for bootc `groups` customizations

- pkg/arch/arch.go
- pkg/container/client.go
- pkg/container/client_test.go
- pkg/container/container_test.go
- pkg/container/resolver.go
- pkg/container/resolver_test.go
- pkg/container/spec.go
This is a different attempt to resolve the issue that the resolver consider the requested architecture more of a "hint". The initial attempt is in https://github.com/osbuild/images/pull/451 but it caused some issues as this seems to be expected behavior of the library in tests at least.
So this commit is more conservative and just includes the the architecture in the `container.Spec` so that the consumer of the library can inspect and error on mismatch of requested arch and resolved arch.
With that in bib we can check the arch, I outlined this in https://github.com/osbuild/bootc-image-builder/compare/main...mvo5:check-resolved-image-arches?expand=1 what we could have to do there (plus some other changes because the image API has changed quite a bit and a go.mod change to make it trivial …
> container: include the architecture of the image in container.Spec

- .gitlab-ci.yml
- test/data/repositories/fedora-40.json
Was removed for CVE-2024-3094.
This reverts commit f8630c4b287a13bd6c7b90b7b25c8c4720b0b729 but with newer snapshots that don't contain the exploited package.
> Re-enable F40 in CI

- pkg/manifest/raw_bootc.go
- pkg/manifest/raw_bootc_test.go
With the new uniform way to handle writing to the bootc image deployment we can now support a custom `/etc/fstab` again. Similar to what we do for users [0] and groups [1] we allow also writing a custom fstab now.
Now that https://github.com/osbuild/osbuild/pull/1727 is merged is ready too.
[0] https://github.com/osbuild/images/pull/571
[1] https://github.com/osbuild/images/pull/593
> manifest: write custom `/etc/fstab` in `RawBootcImage`

- test/scripts/boot-image
- test/scripts/imgtestlib.py
- test/scripts/upload-results
On successful boot of an image type supported by bootc-image-builder (Fedora iot-bootable-container), save the bootc-image-builder image ID as a separate (empty) file so we can save the boot success of multiple images and avoid unnecessary rebuilds.
Fixes #594
> Multi bib cache

- pkg/image/bootc_disk_legacy.go
This commit brings back the pre-PR#462 version of BootcDiskImage as BootcLegacyDiskImage. The rational is that right now we cannot use `bootc install to-filesystem` for cross arch building the FITRIM ioctl is not supported by qemu-user
To fix this is requires any of the following:
1. ensure https://github.com/containers/bootc/pull/462 is available everywhere we care about
2. ensure https://www.mail-archive.com/qemu-devel@nongnu.org/msg1034508.html is available everywhere we care about
3. bind mount /usr/bin/true over /usr/bin/fsfreeze inside the buildroot. This bind mount can be done via `org.osbuild.bind` but it leaks into the manifest and that does not feel great.
So the alternative is to keep using the "old" pipeline that does not yet use `bootc install to-filesystem` to for cross-arch …
> image: bring back the pre-PR#462 `BootcDiskImage`

- pkg/manifest/raw_bootc.go
- pkg/manifest/raw_bootc_test.go
- pkg/osbuild/bootc_install_to_filesystem_stage.go
- pkg/osbuild/bootc_install_to_filesystem_stage_test.go
We currently do not set the `--target-imgref` when using bootc install to-filesystem. This commit fixes this.
(this may be too naive?)
[edit: manual test shows that it seems to work:
```
metadata:
name: host
spec:
image:
image: quay.io/centos-bootc/centos-bootc-dev:stream9
transport: registry
bootOrder: default
status:
staged: null
booted:
image:
image:
image: quay.io/centos-bootc/centos-bootc-dev:stream9
transport: registry
version: stream9.20240411.0
timestamp: null
imageDigest: sha256:1b19a29cb3c93d68f2f8581af94bafc0e58ad57bc941fc2915006823866d7fbc
cachedUpdate: null
incompatible: false
pinned: false
ostree:
checksum: 30ade360312603e3a18d4d43fdbeeaddbc37851b130a8d9c29129da7302fdced
deploySerial: 0
rollback: null
rollbackQueued: false
```
The test in bib is added in …
> manifest,osbuild: support `bootc install to-filesystem --target-imgref`

- Schutzfile
- pkg/distro/rhel/rhel7/ami.go
- pkg/distro/rhel/rhel7/distro.go
- pkg/distro/rhel/rhel7/distro_test.go
- pkg/osbuild/cloud_init_stage.go
- pkg/rpmmd/repository.go
- test/config-map.json
- test/data/repositories/rhel-7.9.json
Add support for building EC2 (RHUI) image on RHEL-7. It is based on the internal KS previously used for building it using ImageFactory.
Depends on https://github.com/osbuild/osbuild/pull/1729
Notable differences:
- Boot entry: the original image used a nice title as the boot entry ID. osbuild grub2.legacy stage instead uses a generic entry ID as the boot entry and then specifies the same "nice" title in grub.cfg in the menuentry.
- Cloud-init default user: the original image modified the main cloud-init config, while in the ported image, we use a drop-in config.
- Dracut config: original image placed config files in `/etc/dracut.conf.d`, while osbuild stage puts it in `/usr/lib/dracut/dracut.conf.d`.
- Firewall config: original image installed firewalld and then uninstalled it in the …
> Distro/RHEL-7: support EC2 (RHUI) image (COMPOSER-2060)

- test/scripts/imgtestlib.py
We can't check if a bootable container was tested with a version of bootc-image-builder if we don't download the files.
> test/imgtestlib: download bib-id files with info files

- test/scripts/base-host-check.sh
Run systemctl status --failed if the is-system-running call fails.  This will print the status output of all failed units, which can save a lot of time troubleshooting when the failure cause isn't obvious.
> test/base-host-check: run systemctl status --failed

- pkg/image/anaconda_container_installer.go
- pkg/manifest/anaconda_installer_iso_tree.go
- pkg/manifest/anaconda_installer_iso_tree_test.go
- pkg/osbuild/kickstart_stage.go
- pkg/osbuild/kickstart_stage_test.go
Support for osbuild for this option landed in https://github.com/osbuild/osbuild/pull/1742
The bib bits are in https://github.com/osbuild/bootc-image-builder/pull/370
> image,manifest,osbuild: support kickstart kernel arguments for the iso container installer

- pkg/distro/rhel/rhel10/ami.go
- pkg/distro/rhel/rhel7/ami.go
- pkg/distro/rhel/rhel8/ami.go
- pkg/distro/rhel/rhel9/ami.go
Current RHEL AMIs have two console parameters 'console=ttyS0,115200n8 console=tty0', which set tty0 as the primary console. As a result, we have less information printed than the RHEL guest image, Amazon Linux and Ubuntu during the boot. To keep this setting consistent with RHEL guest image and make it more useful for boot debug, set the ttyS0 as the primary console.
> Distro/RHEL/AMI: set the ttyS0 as primary console (RHEL-32885)

- pkg/image/anaconda_container_installer.go
- pkg/manifest/anaconda_installer_iso_tree.go
- pkg/manifest/anaconda_installer_iso_tree_test.go
With this and https://github.com/osbuild/bootc-image-builder/pull/368 and https://github.com/osbuild/images/pull/614/commits it seems we have a full iso installer for centos9 (user, networking, kargs).
[Build on top of https://github.com/osbuild/images/pull/614]
> image: add NetworkOnBoot to container installer for bib

- .github/workflows/tests.yml
- Schutzfile
- pkg/dnfjson/dnfjson_test.go
Fedora 40 has been released and the fedora:latest container changed to
F40, breaking our unit tests because the 'setup-osbuild-repo' wasn't
setting up a pinned repository for osbuild on F40.
Let's run unit tests on both F39 and F40.
> Run unit tests on Fedora 40

- .github/workflows/tests.yml
- go.mod
- pkg/container/client.go
- pkg/container/resolver.go
- pkg/container/resolver_test.go
This is a POC to resolve local containers by their ID rather than by their name, the podman desktop team
asked if this was possible since local manifests are not.
> Resolve local container manifests

- .github/workflows/tests.yml
- pkg/container/client.go
- pkg/container/export_test.go
- pkg/container/resolver.go
- pkg/container/resolver_test.go
This is a follow up to #595. Local manifest lists resulted in the `arch` being `unset`. This pr adds
the fix for this as well as a check in the unit test.
> Fix local manifest arch not being set

- pkg/distro/fedora/package_sets.go
In Fedora, there is no 'dnf-yum' package. dnf-yum is provided by yum (which is a subpackage of dnf, confused yet?)
With the dnf5-replacing-dnf transition, dnf5 includes the file /usr/bin/yum and provides and obsoletes 'yum', but it does not provide 'dnf-yum'. In a test of a Kiwi image build using a config which specified 'dnf-yum', this caused a failure, because dnf wanted to pull in 'yum' to satisfy the 'dnf-yum' specification, but it was obsoleted by dnf5 (which it was pulling in as the provider of 'dnf'), so it gave up. I suspect we'd have the same problem with osbuild builds that specify 'dnf-yum'. I think changing it to just 'yum' will solve the problem while remaining compatible across Fedora releases before and after the dnf5 switchover, because in earlier releases, this will pull …
> Change dnf-yum to yum in Fedora package sets

- pkg/distro/rhel/images.go
Our RHEL Edge deployments (ISOs and disk images) had inconsistent osnames set.  The edge-installer used "rhel" while the simplified installer and disk image used "redhat".
For bonus inconsistency, the RHEL Edge ISOs created by the Edge Service modify the kickstart file to set the osname to "rhel-edge".
Meanwhile, Fedora IoT images all set the osname to "fedora-iot".
To make everything consistent and unify the names, let's set all osnames to "rhel-edge".  This aligns better with Fedora (the equivalent to "fedora-iot" in the RHEL world is "rhel-edge") and with what has already been happening in the service.
Practically, the osname sets the deployment path:
/ostree/deploy/$OSNAME
so this will affect new deployments, but will have no effect on existing installations and upgrades.
> distro/rhel: unify osname for edge deployments (HMS-4011)

- pkg/manifest/os.go
Insights-client collection must occur at boot time so that the current ostree commit hash can be reflected after upgrade.  Otherwise, the upgrade shows as failed in the console UI.  Add a drop-in file that enables insights-client.service to run on successful boot.
Drop-in files can normally be created with the `org.osbuild.systemd.unit` stage but the stage doesn't support all the options we need.  This is a temporary workaround until we get the stage updated to support everything we need.
This change was previously part of the Edge Fleet Management service.  The drop-in file was created by a `%post` section in the injected kickstart file.  Creating it in the base ostree-commit is cleaner and should be functionally the same, with the major difference that the drop-in will be removed during …
> manifest: modify insights-client.service for ostree-based systems (HMS-4031)

- test/scripts/setup-osbuild-repo
When testing with "pinned" osbuild commit IDs (defined in the Schutzfile), we set up a repository based on the commit ID that should exist for each commit in osbuild that had a (partially) successful CI run (the RPM jobs should at least run successfully).
When a repository doesn't exist for whatever reason (the CI pipeline failed, the commit ID was copied incorrectly, etc), the setup script wouldn't fail and osbuild would be installed from the system repositories.  This means that we're not testing what we think we are testing.  In the best case our build jobs fail because the osbuild version in the repos isn't new enough to have all the features we're testing, but we might also end up having passing tests that aren't testing what we want, for example a change in osbuild internals that's …
> test/scripts: fail setup-osbuild-repo on bad repo

- .github/workflows/update-bootc-image-builder.yml
With things slowing down a bit, we don't need to have daily updates of the BIB ref here.  Weekly updates should be enough.
I set it to run every Sunday at noon, so CI jobs can run when there's not much other activity and we can deal with failures on Monday.
> github: update bib ref every week

- Schutzfile
- pkg/customizations/bootc/bootc.go
- pkg/distro/fedora/images.go
- pkg/image/ostree_archive.go
- pkg/manifest/os.go
- pkg/osbuild/bootc_install_config_stage.go
Set the preferred root filesystem type for the iot-bootable-container to ext4.
This file is required for the container to work with `bootc install`.
Requires https://github.com/osbuild/osbuild/pull/1747
> Add bootc config to iot-bootable-container

- pkg/osbuild/bootupd_stage.go
- pkg/osbuild/bootupd_stage_test.go
- pkg/osbuild/device.go
- pkg/osbuild/device_test.go
Mount names are just identifiers. They don't have any other real
meaning.
Prior this commit, callers of genOsbuildMount had to supply the mount
name, which led to inconsistencies: genMountsDevicesFromPt used the
name of the leaf device, genMountsForBootupd used synthetic names
constructed from a partition number.
The issue with the genMountsDevicesFromPt's approch is that multiple
mounts can be created from a simple device. This is not currently
used, but it will come with btrfs (single device) and its subvolumes
(multiple mounts). The genMountsForBootupd's approach has a similar
flaw.
This commit implements the mount name generation directly in
genOsbuildMount. The new name is no longer referring to the source,
but it's rather constructed from the mountpoint (by using pathEscape).
This …
> pkg/osbuild: move mount name generation into getOsbuildMount

- pkg/distro/rhel/rhel10/ami.go
The dhcp-client was dropped from RHEL 10.  As a cloud-init dependency, it has been replaced by dhcpcd.
See RHEL-26304
> distro/rhel10: replace dhcp-client with dhcpcd

- pkg/osbuild/bootupd_stage.go
- pkg/osbuild/bootupd_stage_test.go
Instead of the if statement, I switched to switch (pun absolutely intended). Also, I fixed the error message, previously it always printed type <nil>, because mnt is set to nil, if ok == false.
> pkg/osbuild: clean up genMountsForBootupd

- cmd/build/main.go
- cmd/gen-manifests/main.go
- internal/cmdutil/export_test.go
- internal/cmdutil/rand.go
- internal/cmdutil/rand_test.go
To ensure that manifests get random(ish) and stable UUIDs we set the rng seed arg based on the filename.
This should fix the issue discovered in
osbuild/manifest-db#124
that duplicated UUIDs for xfs/btrfs can trigger random(ish) and hard to diagnose errors.
This is the same as
osbuild/osbuild-composer#4124 hopefully for the right place this time.
> cmd: add helper for seed generation

- pkg/manifest/anaconda_installer_iso_tree.go
- pkg/manifest/coi_iso_tree.go
- pkg/osbuild/disk.go
- pkg/osbuild/mkfs_stage.go
- pkg/osbuild/mkfs_stages_test.go
Prior this commit, the implementation was slightly confusing: GenMkfsStages accepted a generic device as the source of the underlying disk image. However, the function could only operate on a loopback, otherwise it panicked. Moreover, the function didn't actually use the given device: it just used the filename from the given loopback device. The actual device for generated stages is created in getDevices.
Let's simplify this: The function now accepts just the filename, since this is actually the only thing that it needs.
Also added tests. The unhappy path still relies on a panic, but this is a huge rabbit hole that I don't want to explore at this point.
> pkg/osbuild: Simplify GenMkfsStages arguments

- go.mod
This directive was added in commit 29f66a251f to workaround an issue with the github.com/containers/image/v5 v5.22 where some misconfiguration/misrelease of go-sqlite caused problems.
This seems to be no longer necessary, I followed the reproducer steps from the original commit and see no errors (anymore).
The reason this is useful is so that we run the gen-manifests command directly via `go run`. Right now it will error with:
```
$ go run github.com/osbuild/images/cmd/gen-manifests@latest
go: github.com/osbuild/images/cmd/gen-manifests@latest (in github.com/osbuild/images@v0.61.0):
The go.mod file for the module providing named packages contains one or
more exclude directives. It must not contain directives that would cause
it to be interpreted differently than if it were the main …
```
> go.mod: remove `exclude github.com/mattn/go-sqlite3`

- pkg/image/anaconda_container_installer.go
Make the use of RHEL lorax templates configurable from the top level image definition so that we can control it in BIB based on the distro being built.
See https://github.com/osbuild/bootc-image-builder/issues/421
> image: make the RHEL lorax template selection configurable

- pkg/distro/rhel/rhel8/ami.go
- pkg/distro/rhel/rhel8/sap.go
**distro/rhel8: rh-amazon-rhui-client-sap-bundle for RHEL 8 "unversioned"**
For RHEL 8.10 SAP, e4s isn't planned, but SAP is supported with the
unversioned RHUI client.
See RHUIOPS-276
---
**distro/rhel8: remove version lock on 8.10 for SAP**
Version lock should not exist on 8.10 for SAP.  It's the last RHEL
release in the 8.* stream.
See COMPOSER-2252
---
> RHEL 8.10: change RHUI client package and remove version lock (COMPOSER-2252)

- pkg/dnfjson/dnfjson.go
**dnfjson: add OptionalMetadata property to depsolve args**
New property on the arguments object that controls the types of metadata
to download for repositories and use when depsolving.
See https://github.com/osbuild/osbuild/pull/1775
---
**dnfjson: enable filelists for older distro versions**
Enable filelists in the optional metadata for EL7, EL8, EL9, and Fedora 39.
When running osbuild-depsolve-dnf with the libdnf version that's
included in these distro versions, this option will have no effect since
it is enabled by default.  However, when depsolving packages for these
distro versions with newer versions of libdnf, the filelists are
disabled and can cause issues with packages that declare dependencies on
filepaths.
The cutoff point is a little fuzzy for CentOS and Fedora.  Depsolving …
> dnfjson: enable loading of optional metadata when needed

- pkg/cloud/awscloud/awscloud.go
The default minimum chunk size of 5MB for s3 upload only allows for an upload of about 50Gi. It is not out of the question for a bootc image to get above this threshhold.
For now, this will increase the chunk size to 64MB making it possible to upload images up to ~640Gi. This could in the future become a dynamic value, but for now, this should at least give some head room.
> Set the chunk size for S3 upload to 64MB

- pkg/distro/rhel/rhel8/azure.go
- test/data/repositories/rhel-8.10.json
Since 8.10 is the last minor release of RHEL8, and it's not E4S one / has unversioned repos, its RHUI client rpm name is different.
See COMPOSER-2254
---
While the [snapshot job](https://github.com/osbuild/rpmrepo/actions/runs/9317155443/job/25646887891) is still running, the repository we need for this is already done, so let's use it here and we'll update the rest of the repo snapshots later.
> distro/rhel8: update RHUI client RPM for Azure SAP 8.10 images (COMPOSER-2254)

- test/scripts/upload-results
The progress output gets very spammy in the CI logs.
See for example https://gitlab.com/redhat/services/products/image-builder/ci/images/-/jobs/6990565006/viewer
> test/upload-results: run aws command with --no-progress

- .github/workflows/tests.yml
- test/scripts/generate-ostree-build-config
Also output the version of pylint being used by the github workflow.
> generate-ostree-build-config: pylint is wrong about used-before-assignment

- internal/common/helpers.go
- internal/common/helpers_test.go
- pkg/manifest/ostree_deployment.go
- pkg/osbuild/systemd_unit_create_stage.go
- pkg/osbuild/systemd_unit_create_stage_test.go
- pkg/policies/policies.go
- test/configs/ostree-filesystem-customizations-installer.json
- test/configs/ostree-filesystem-customizations.json
The original purpose of this PR was to make the DefaultDependencies option an optional property that defaults to 'true'.  The original PR also had a small fix for the mountpoint creation service.  While working on updating the previous PR, I found that the mountpoint creation service for ostree-based images needed more work, including additions to the osbuild stage that creates it.
Replaces #608.
Changes to the systemd unit:
The last item was abandoned because we don't have a clean way of toggling the immutable flag back on without communicating info from the Pre command to the Post command.
This PR also updates the mountpoint policy for ostree-based systems to disallow paths that are top-level symlinks on a booted system.
Requires https://github.com/osbuild/osbuild/pull/1782
> osbuild/systemd-unit-create: fix DefaultDependencies option

- pkg/distro/fedora/partition_tables.go
Currently AArch64 uses a `dos` partition table in Fedora to support the Raspberry Pi, which isn't a target for the `iot-simplified-installer`. 
This PR changes the `iot-simplified-installer` on AArch64 to `gpt` and fixes https://github.com/fedora-iot/iot-distro/issues/48
> Fedora: Change AArch64 iot-simplified-installer to gpt

- .github/workflows/test-osbuild-composer-intergation.yml
We've been ignoring the osbuild-composer integration test failures because we assumed they were due to unresolved incompatibilities but after opening https://github.com/osbuild/osbuild-composer/pull/4198 I realised that the compatibility is fine.  It was actually failing because an option we were using had been removed:
```
Warning: Unexpected input(s) 'skip-pkg-cache', valid inputs are ['version', 'install-mode', 'working-directory', 'github-token', 'only-new-issues', 'skip-cache', 'skip-save-cache', 'problem-matchers', 'args', 'cache-invalidation-interval']
```
The option is no longer needed (see previously linked issue) and has been removed.
> github: remove skip-gpg-cache from go lint job

- pkg/manifest/os.go
org.osbuild.users runs useradd, usermod, passwd, and mkhomedir_helper in the os tree using chroot. Most image types should already have the required packages, but some minimal image types, like 'tar' don't, so let's add them for the stage to run and to enable user management in the image.
Fixes #724
> manifest: add shadow-utils and pam when users are created

- pkg/distro/rhel/rhel9/ami.go
The awscli2 package is included in the upcoming RHEL 9.5.0 release and it would be helpful to include it in AWS AMIs by default.
> manifest: Add awscli2 to RHEL 9 AMI (CLOUDX-913)

- pkg/manifest/raw_bootc.go
- pkg/manifest/raw_bootc_test.go
- pkg/manifest/raw_ostree.go
- pkg/osbuild/bootc_install_to_filesystem_stage.go
- pkg/osbuild/bootc_install_to_filesystem_stage_test.go
- pkg/osbuild/bootupd_stage.go
- pkg/osbuild/bootupd_stage_test.go
Currently, validateBootupdMounts always ensures that `/boot/efi` exists. This requirement is not necessary on non-UEFI platforms such as s390x.
This patch skips the check for `/boot/efi` when UEFIVendor is not set.
This change is required for this issue: https://github.com/osbuild/bootc-image-builder/issues/460
> pkg/osbuild: Skip EFI partition check for non UEFI platforms

- .github/workflows/update-bootc-image-builder.yml
Our bootc containers are incompatible with newer versions of the bootc-image-builder tool because the tool sets options that require composefs, which our images don't support yet.
Temporarily disable the update cronjob until we fix this.
> github: disable the cron scheduled updates of the BIB ref (COMPOSER-2245)

- pkg/customizations/oscap/oscap.go
- pkg/distro/fedora/distro.go
- pkg/distro/fedora/images.go
- pkg/distro/rhel/defaults.go
- pkg/distro/rhel/images.go
- pkg/manifest/os.go
- pkg/osbuild/oscap_autotailor_stage.go
- pkg/osbuild/oscap_autotailor_stage_test.go
- pkg/osbuild/oscap_remediation_stage.go
- test/scripts/base-host-check.sh
This PR is in preparation for a follow up PRs to simplify tailoring to accept an `xml` file.
It's an attempt to simplify the stage creation options using an internal abstraction to create
the options.
This splits up #708, drops the `json` tailoring and the tailoring `overrides`.
> Refactor OpenSCAP stage config (HMS-3826)

- pkg/distro/fedora/package_sets.go
Drop `oscap-anaconda-addon` from `anacondaPackageSet` in Fedora. It's currently breaking the [Fedora IoT Rawhide compose](https://koji.fedoraproject.org/koji/taskinfo?taskID=119644972), and not included in other Fedora ISO's.
> distro/fedora: drop oscap-anaconda-addon from anacondaPackageSet

- cmd/build/main.go
Use the more idomiatic `if err != nil { return err }` instead of the custom `check/fail` helper. This is first step to making this a standalone binary that can potentially be run inside a container.
> cmd/build: tweak and replace `check`/`fail`

- pkg/image/anaconda_container_installer.go
- pkg/image/anaconda_ostree_installer.go
- pkg/image/installer_image_test.go
**image: allow unset kickstart options where possible**
For the AnacondaContainerInstaller, having empty kickstart options when
creating the ImageKind should be possible.  The only option that's
required is the Kickstart.Path, which has a default value we can set.
For the AnacondaOSTreeInstaller, at least the OSTree options are
required, so return an error when they're not set, but also set the
Kickstart.Path to the default when it's not already set from the caller.
---
**image: drop InteractiveDefaultKickstart in AnacondaContainerInstaller**
This isn't used and can cause unnecessary errors when 'img.Kickstart' is
not set.
---
**test: instantiate and serialize anaconda manifests without ks options**
Test that anaconda manifests can be generated without error when
kickstart options are not …
> Make sure the default kickstart path is used when the option is unset

- pkg/manifest/raw_bootc_test.go
- pkg/osbuild/bootc_install_to_filesystem_stage_test.go
- pkg/osbuild/bootupd_stage.go
- pkg/osbuild/bootupd_stage_test.go
I'd like to change bib to just drop the separate `/boot` partition by default because it isn't doing anything useful right now.
A separate `/boot` is only useful with things like LUKS or LVM, but since bib doesn't do those now and it's not in the near term roadmap clearly either, let's just not add the complexity of a separate `/boot` by default.
> bootupd: Don't require /boot mount point

- pkg/image/anaconda_tar_installer.go
- pkg/image/installer_image_test.go
- pkg/osbuild/grub_iso_stage.go
- pkg/osbuild/grub_iso_stage_test.go
Follow-up to #764.
This PR mainly fixes the handling of the kickstart path in AnacondaInstaller.  The fallback logic for unset kickstart paths was a bit buggy, but we never noticed because we never really set the value to anything else.  Tests have now been added and the buggy logic has been fixed.
I also added validation to the grub2.iso stage options, which ensures that certain ISO values are not unset (Product, Version, ISOLabel).
> Fix kickstart path handling in AnacondaInstaller

- internal/testdisk/partition.go
- pkg/disk/btrfs.go
- pkg/disk/btrfs_test.go
- pkg/disk/disk.go
- pkg/disk/disk_test.go
- pkg/disk/partition_table.go
- pkg/disk/partition_table_test.go
- pkg/osbuild/bootupd_stage.go
- pkg/osbuild/bootupd_stage_test.go
- pkg/osbuild/btrfs_mount.go
- pkg/osbuild/btrfs_subvol_stage.go
- pkg/osbuild/copy_stage_test.go
- pkg/osbuild/device.go
- pkg/osbuild/device_test.go
- pkg/osbuild/disk.go
- pkg/osbuild/disk_test.go
- pkg/osbuild/mkfs_stage.go
- pkg/osbuild/mkfs_stages_test.go
- pkg/osbuild/mount_test.go
(This is a revived #422.)
This PR has basically three parts:
1) The first commits fix already existing btrfs code in the library (it was never used before). Just tiny fixes. I tried to add tests where they had been missing before.
2) The "middle section" adds missing parts for btrfs subvolume. The scaffolding was there, but the translation from an abstract partition table to osbuild stages was missing.
3) The final section is the actual addition of a btrfs partitioning mode. When this mode is used, a root partition from the base partition table is converted to a btrfs one with a subvolume. The code for adding more btrfs subvolumes based on blueprint mountpoints was already there.
Weird parts:
- When a btrfs partitioning mode is used, the compression is hard-coded to zstd:1. It would be …
> Add the btrfs partitioning mode

- cmd/otk-gen-partition-table/export_test.go
- cmd/otk-gen-partition-table/main.go
- cmd/otk-gen-partition-table/main_test.go
- cmd/otk-make-partition-mounts-devices/export_test.go
- cmd/otk-make-partition-mounts-devices/main.go
- cmd/otk-make-partition-mounts-devices/main_test.go
- cmd/otk-make-partition-stages/export_test.go
- cmd/otk-make-partition-stages/main.go
- cmd/otk-make-partition-stages/main_test.go
- internal/otk/partition.go
- internal/otkdisk/partition.go
- internal/otkdisk/partition_test.go
- pkg/osbuild/copy_stage.go
- pkg/osbuild/device.go
- pkg/osbuild/device_test.go
This is a joint PR by @mvo5 and me that adds three new commands:
- otk-gen-partition-table: generates a fully resolved partition table from a base description and modifications.  It's an externalised version of the `disk.NewPartitionTable()` function.
- otk-make-partition-stages: generates stages that can be added to a manifest to create a disk image from a fully resolved partition table.  It's an externalised version of the `osbuild.GenImagePrepareStages()` function.
- otk-make-partition-mounts-devices: generates mounts and devices that can be attached to osbuild stages that need to operate on a partitioned image file.  It's an externalised version of the `osbuild.GenMountsDevicesFromPT()` function.
Some tests can still be added and it might be good to test these with otk directly before …
> Partition Table, Stages, Mounts, and Devices generator commands for otk

- pkg/blueprint/customizations.go
- pkg/customizations/oscap/oscap.go
- pkg/distro/fedora/images.go
- pkg/distro/rhel/images.go
- test/config-map.json
- test/configs/oscap-rhel8-with-xml-tailoring.json
- test/configs/oscap-rhel9-with-xml-tailoring.json
If the user supplies an xml tailoring file, we can skip the autotailor
stage - since the autotailor stage just generates the xml file. In this
case we can just set the tailoring config to `nil` and ensure that the
remediation configs have the correct values.
> OpenSCAP XML tailoring (HMS-4386)

- .github/workflows/update-osbuild.yml
- test/scripts/update-schutzfile-osbuild
New job that runs weekly (or on-demand) that updates the osbuild commit ID in the Schutzfile to the latest main commit.  This is used to install the osbuild dependency in gitlab CI to build images.  While we often update this manually when needed, this job will make sure we don't miss any updates when no new features required us to update manually.
The job runs on Sundays at noon (UTC).  When the osbuild commit ID changes, our gitlab CI jobs always rebuild every test image configuration, which can take up to three hours so it is good to do it on a Sunday, when there are much fewer CI jobs running.
> New github action that regularly updates osbuild commit ID

- pkg/distro/rhel/rhel9/azure.go
I failed to bump the size of the boot partition for Azure images in
4aff47dcbed000fded0486061be70bb1dfb14fb2.
This commit fixes that.
> distro/rhel9: match azure boot partition with other cloud images

- pkg/disk/partition_table_internal_test.go
There is currently a bug that occurs when converting a partition table to LVM with a root partition size that is larger than the original partition size (or larger than the partition table).  @croissanne discovered it and we investigated it together yesterday.  We both have ideas for how to fix it properly, but first I decided to write some tests to catch similar issues.
To keep things easier to follow and review, I decided to first introduce a utility function for validating partition table sizes.  Currently this is a test utility function.  If we discover that we need it outside of testing, we can move it to the `partition_table.go` file.
> Test utility function for validating Partition Table sizes

- cmd/otk-gen-partition-table/main_test.go
- pkg/disk/btrfs.go
- pkg/disk/disk.go
- pkg/disk/luks.go
- pkg/disk/lvm.go
- pkg/disk/partition.go
- pkg/disk/partition_table.go
- pkg/disk/partition_table_internal_test.go
This PR is primarily concerned with fixing a bug where partitions that contain sized sub-volumes would not be resized to be able to contain their children.  The bulk of this PR however adds tests for all kinds of partition table resizing scenarios, using the `PartitionTable.relayout()` method.
@croissanne discovered a bug in the `PartitionTable.relayout()` method that would not grow a Partition to fit the sum of the LogicalVolume sizes in an LVM VolumeGroup.  The following example describes a scenario where the bug manifests:
1. Starting with a Partition Table with size `10 GiB` which only has a root partition `9 GiB`.
2. The user adds a `/boot` with size `1 GiB` and sets `/` to `15 GiB`.
3. First, the root partition is grown to `15 GiB`.  This also grows the Partition Table size to fit. …
> Fix the disk relayout function to resize all sizeable containers to fit their contents

- cmd/otk-make-fstab-stage/export_test.go
- cmd/otk-make-fstab-stage/main.go
- cmd/otk-make-fstab-stage/main_test.go
This helper is similar to the `otk-make-partition-stages` but for
the `fstab` generation. It consumes the variables generated by
`otk-gen-partition-table` and produces a fragment to generate
the `org.osbuild.fstab` stage.
The expected usage is something like:
```yaml
otk.define:
filesystem:
otk.external.gen_partition_table:
modifications: ${modifications.filesystem}
properties: ...
partitions: ...
stages:
...
otk.external.make_fstab_stage:
internal: ${filesystem.internal}
```
Build on top of https://github.com/osbuild/images/pull/732 only the last commit is relevant.
> cmd: add `otk-make-fstab-stage` helper

- pkg/blueprint/customizations.go
- pkg/blueprint/customizations_test.go
- pkg/blueprint/rpm_customizations.go
- pkg/distro/fedora/images.go
- pkg/distro/rhel/images.go
- test/config-map.json
- test/configs/import-rpm-gpg-keys-from-tree-fedora.json
- test/configs/import-rpm-gpg-keys-from-tree-rhel.json
As part of https://issues.redhat.com/browse/COMPOSER-2308, I'm moving RHUI client RPMs installation from the image definition to customizations. However, Azure RHUI images import by default RPM GPG keys from the image tree, which are installed by the RHUI client rpm. Which means that the image definition technically still has hard dependency on the RHUI client rpm. Therefore it makes sense to also move the RPM GPG key importing from tree also to the customizations.
Add a BP customization for specifying paths to RPM GPG keys installed in the image, which will be imported to the RPM database during image build.
> Add BP customization for importing RPM GPG keys from the image tree (COMPOSER-2308)

- pkg/disk/filesystem.go
- pkg/disk/partition_table_test.go
When generating UUIDs for filesystems we need to special case the vfat filesystem. It does not actually support UUIDs but instead uses a 32bit hex encoded serial number (volume id). So special case "vfat" and generate a volume-id in this case.
> filesystem: fix Filesystem.GenUUID() for vfat partitions

- pkg/distro/rhel/rhel10/distro_internal_test.go
- pkg/distro/rhel/rhel10/partition_tables.go
Remove /boot partition from RHEL 10/CentOS Stream 10 disk images.
Fixes: COMPOSER-2324
Fixes: COMPOSER-2302
> rhel10: drop `/boot` partition

- pkg/distro/rhel/rhel10/ami.go
- pkg/distro/rhel/rhel10/distro_test.go
- pkg/distro/rhel/rhel10/qcow2.go
- pkg/distro/rhel/rhel10/vmdk.go
Drop net.ifnames=0 from RHEL 10 and Centos10 disk images and add test.
Fixes: COMPOSER-2289
Fixes: COMPOSER-2323
> rhel10: drop `net.ifnames=0` from rhel10/centos10

- pkg/disk/disk.go
- pkg/disk/luks.go
- pkg/disk/partition_table.go
Following up from #809, this PR adds package-level documentation for the disk package and a detailed explanation of how the `NewPartitionTable()` function works.
> Improve documentation of the disk package

- pkg/blueprint/filesystem_customizations.go
The toml tag for customizations.filesystem.minsize was incorrectly set to size.  In osbuild-composer this was already changed to minsize [1]. The blueprint implementation in this repo is used directly in bootc-image-builder, so the tags affect how the config is parsed by that tool.
Our blueprint reference for bootc-image-builder also uses `minsize` [2]. Let's finally unify the config everywhere.
[1] https://github.com/osbuild/osbuild-composer/pull/3783
[2] https://osbuild.org/docs/user-guide/blueprint-reference/#filesystems
> blueprint: fix filesystem minsize toml key

- pkg/manifest/raw_bootc.go
The group stage block was checking for an error after the osbuild.GenGroupStage() call, which doesn't return an error.
> manifest: remove redundant error check

- pkg/dnfjson/dnfjson.go
- pkg/dnfjson/dnfjson_test.go
With the new "dnf5" solver is seems useful to allow the dnfjson code return what solver was actually used in the transaction.
This commit allows an (optional) "solver" field in the json that is returned from the dnfjson helper. It does not do more yet but we should (probably) make it avaialble for the higher layers too so that it can be e.g. logged.
See also https://github.com/osbuild/osbuild/pull/1776
> dnfjson: allow (optional) field `solver` in the dnfjson output

- cmd/otk-make-fstab-stage/main.go
- cmd/otk-make-fstab-stage/main_test.go
- cmd/otk-make-partition-mounts-devices/main.go
- cmd/otk-make-partition-mounts-devices/main_test.go
- cmd/otk-make-partition-stages/main.go
- cmd/otk-make-partition-stages/main_test.go
When otk calls externals it expects them to be wrapped inside a "tree" json key for both the inputs and the outputs. This is important to make the schema extensible. However the existing otk externals in this repo do not respect that.
This commit fixes it and updates the tests.
> cmd/otk-*: fix all otk external to be wrapped in a "tree" json

- pkg/blueprint/customizations.go
- pkg/blueprint/customizations_test.go
- pkg/blueprint/installer_customizations.go
- pkg/customizations/anaconda/anaconda.go
- pkg/distro/fedora/images.go
- pkg/distro/rhel/images.go
- pkg/image/anaconda_container_installer.go
- pkg/image/anaconda_ostree_installer.go
- pkg/image/anaconda_tar_installer.go
- pkg/image/installer_image_test.go
- pkg/manifest/anaconda_installer.go
- pkg/manifest/anaconda_installer_test.go
- pkg/osbuild/anaconda_stage.go
- pkg/osbuild/anaconda_stage_test.go
- test/configs/unattended-iso.json
This PR generalises the solution to the problem we had in BIB (osbuild/bootc-image-builder#547) 
where Anaconda Modules were not enabled for custom kickstarts, making it impossible to use certain kickstart features.  For example, in most Anaconda ISO builds, we only enable the Users module if a user is specified in the blueprint.  A custom kickstart with a user creation command would therefore have no effect, since the Users module would be disabled.  The same is true for many other kickstart commands.
However, enabling certain modules unconditionally is also not desirable.  For example, in the case of ostree payloads, enabling the user module can prevent automated/unattended installation, since Anaconda will block and prompt for an admin user to be created.  Users may not want to create …
> Add Anaconda Module customizations to Blueprint (RHEL-49499)

- pkg/customizations/oscap/oscap.go
- pkg/customizations/oscap/oscap_test.go
- pkg/distro/fedora/images.go
- pkg/distro/rhel/images.go
- pkg/manifest/os.go
- pkg/osbuild/oscap_autotailor_stage.go
- pkg/osbuild/oscap_remediation_stage.go
- pkg/osbuild/oscap_remediation_stage_test.go
The oscap tailoring and remediation configs were too tightly coupled with the osbuild stage implementations. These configs can be refactored further by making the `TailoringConfig` a pointer on the
`RemediationConfig`, reversing the dependency of the configs.
These changes should reduce the complexity of the OpenSCAP stage options and hopefully reduce some of the confusion too.
Thanks to @thozza for the suggestion
> pkg/oscap: refactor & clean up

- pkg/distro/rhel/images.go
- pkg/image/anaconda_container_installer.go
- pkg/image/anaconda_ostree_installer.go
- pkg/image/anaconda_tar_installer.go
- pkg/image/installer_image_test.go
- pkg/manifest/anaconda_installer.go
- pkg/manifest/anaconda_installer_test.go
- pkg/osbuild/anaconda_stage.go
- pkg/osbuild/anaconda_stage_test.go
Add the new Anaconda stage options introduced in https://github.com/osbuild/osbuild/pull/1320 and use the new `activatable-modules` option by default.
The legacy Anaconda config (`kickstart-modules`) is now only used in RHEL 8 installers.
See also https://bugzilla.redhat.com/show_bug.cgi?id=2023855#c10
Fixes #833
> Use new Anaconda config options in RHEL 9+ and Fedora

- pkg/manifest/os.go
org.usbuild.users runs passwd in the os tree using chroot, but this package wasn't guaranteed to be installed
> manifest: add passwd when users are created

- pkg/manifest/ostree_deployment.go
ExceStart/Stop should set `chattr` when ostree does not have composefs enabled. With composefs `chattr` is not required explicitly but tansient rootfs should be enabled to ensure the service can create the required mountpoints.
fixes: #837
> fix-fs-customization:exec start and stop logic

- pkg/distro/rhel/rhel10/distro.go
- pkg/distro/rhel/rhel10/distro_test.go
- pkg/distro/rhel/rhel10/qcow2.go
OpenStack documentation points at the RHEL KVM Guest Image as the
official way to get RHEL up and running on OpenStack.
See https://docs.redhat.com/en/documentation/red_hat_openstack_platform/17.1/html/creating_and_managing_images/assembly_glance-creating-images_osp#proc_using-a-rhel-kvm-instance-image_glance-creating-rhel-kvm-images
osbuild-composer inherited the openstack image type from lorax-composer.
I'm not sure if something was different in the RHEL 7 times, or why
a separate image type was created back then. However nowadays, qcow2
is apparently the official option even for OpenStack, so we don't need
to carry a separate type forward. Thus, this commit drops it.
> distro/rhel10: drop the openstack image type

- pkg/distro/rhel/rhel10/ami.go
- pkg/distro/rhel/rhel9/ami.go
rd.blacklist is actually not processed by anything. The correct option is called rd.driver.blacklist, see
https://man.archlinux.org/man/dracut.8.en
Hovewer, we can actually safely remove it altogether, because we also blacklist nouveau in a /etc/modprobe.d drop-in config. This is actually the recommended way, see
https://access.redhat.com/solutions/41278
Thus, this commit removes the redundant, and actually bogus argument.
> distro/rhel{9,10}: remove bogus rd.blacklist=nouveau kernel (RHEL-53491)

- pkg/disk/disk_test.go
- pkg/disk/partition_table.go
Through the power of code completion, this typo stuck around for over 6 months.
> disk: BtfrsPartitioningMode -> BtrfsPartitioningMode

- pkg/osbuild/bootc_install_to_filesystem_stage.go
bootc install to-filesystem requires a clean root to install, with only the required mountpoints present: /, /boot, and /boot/efi.  Do not mount any user-defined mountpoints when running the bootc install stage.
Content in bootc images cannot be separated across filesystems, therefore there cannot be any content under the custom mountpoints, so this change will not cause any issues of content not being on the correct filesystem.
See also the discussion at https://github.com/osbuild/bootc-image-builder/issues/579
> osbuild: only mount the required mountpoints for bootc install (COMPOSER-2301)

- pkg/blueprint/filesystem_customizations.go
- pkg/blueprint/filesystem_customizations_test.go
- pkg/distro/fedora/distro_test.go
- pkg/distro/rhel/rhel10/distro_test.go
- pkg/distro/rhel/rhel7/distro_test.go
- pkg/distro/rhel/rhel8/distro_test.go
- pkg/distro/rhel/rhel9/distro_test.go
- pkg/pathpolicy/path_policy.go
- pkg/pathpolicy/path_policy_test.go
Trivial tweak for the errors returned from PathPolicies.Check() so that they are a bit more user friendly.
See also https://github.com/osbuild/bootc-image-builder/pull/601
> pathpolicy: tweak error messages and add test

- pkg/osbuild/bootc_install_to_filesystem_stage_test.go
- pkg/osbuild/bootupd_stage_test.go
Small tweak for the tests for `NewBootcInstallToFilesystemStage` so that we also test that only the essential mounts are used in the `org.osbuild.bootc.install-to-filesystem`. This also makes the fake creation for /boot/efi more realistic by moving the fs to `vfat`.
Tiny followup for https://github.com/osbuild/images/pull/846
> osbuild: add test for essential mounts in NewBootcInstallToFilesystemStage

- cmd/otk-make-fstab-stage/main.go
- pkg/disk/btrfs.go
- pkg/disk/btrfs_test.go
- pkg/disk/disk.go
- pkg/disk/filesystem.go
- pkg/disk/filesystem_test.go
- pkg/disk/luks_test.go
- pkg/disk/lvm_test.go
- pkg/disk/partition_table.go
- pkg/disk/partition_test.go
- pkg/manifest/os.go
- pkg/manifest/ostree_deployment.go
- pkg/manifest/raw_bootc.go
- pkg/osbuild/fstab_stage.go
disk: add static checks that interfaces are implemented
This commit adds some static checks that ensure that the disk,
btrfs,filesystem and lvm types implement the expected interfaces.
This is important because when changing e.g. the Mountable
interface by adding an "error" to GetFSTabOptions() without
this change all non-updated types just silently drop implementing
the interface without any error or warning leading to unexpected
test failures.
---
disk: make `GetFSTabOptions()` return an error
The disk package is now used for the `otk` externals. This means
that the inputs we get are much less controlled and instead of
panicing we should return more user-friendly error messages.
This commit starts by making `GetFSTabOptions()` return an error
and then bubbling it up.
Followup to …
> disk,otk-make-fstab-stage: make `GetFSTabOptions()` return an error and remove `recover()` 

- pkg/platform/x86_64.go
I cannot find any places that use this type. Let's just drop it.
> platform: remove unused X86BootLoader type

- pkg/distro/rhel/rhel10/qcow2.go
The package is required for openscap-scanner (OpenSCAP hardening). OpenSCAP package switched to NSS crypto backend in RHEL10.
See: https://issues.redhat.com/browse/RHEL-49502
> distro/rhel10: do not exclude nss package

- pkg/distro/fedora/version.go
41 branched, so Rawhide's associated version number is now 42.
> Bump VERSION_RAWHIDE to 42

- internal/testdisk/partition.go
- pkg/osbuild/bootupd_stage.go
- pkg/osbuild/bootupd_stage_test.go
- pkg/osbuild/lvm2_lv_device.go
- pkg/osbuild/lvm2_lv_device_test.go
This is required for `bootc-image-builder` to support LVM. It works by using the new `vg_partition` option to the `org.osbuild.lvm2.lv` device and use it when generating the bootc/bootupd mounts.
This way all mounts can come from the same underlying loop device and bootc/bootupd can install the bootloader there. See also https://github.com/osbuild/osbuild/pull/1867
> osbuild: add support for `LVM` to `GenBootupdDevicesMounts()`

- cmd/build/main.go
- cmd/gen-manifests/main.go
- cmd/list-images/main.go
- internal/cmdutil/multivalue.go
- test/README.md
- test/scripts/build-image
- test/scripts/imgtestlib.py
These are a couple of changes I've been fiddling with while working on other stuff.
1. I think `--type` is a better name for the image type flag than `--image` for `cmd/build` and the same for the plural form for `cmd/gen-manifests` and `cmd/list-images`.
2. I caught myself doing checkpointing by editing the command or generating manifests and running them separately sometimes when experimenting with builds.  Let's just add a `--checkpoints` flag that gets passed down to osbuild.
We might add an `--osbuild-options` flag instead and use that to pass stuff down to osbuild in the future, but let's keep this short for now.
> Rename image(s) cmd flags to type(s) and add checkpoints to build

- pkg/disk/btrfs.go
- pkg/disk/disk.go
- pkg/disk/filesystem.go
- pkg/disk/luks.go
- pkg/disk/lvm.go
- pkg/disk/partition.go
- pkg/disk/partition_table.go
- pkg/disk/partition_table_internal_test.go
This method is actually only used in tests, and it's actually not
needed as we can just use a type assertion like everywhere else.
> disk: drop Entity.IsContainer()

- pkg/distro/rhel/rhel10/ami.go
- pkg/distro/rhel/rhel10/azure.go
The package was removed from c10s / el10.0 beta. I must add that after the development freeze ¯\_(ツ)_/¯.
See https://issues.redhat.com/browse/CS-2494
> RHEL-10: remove gdisk from pkg sets of all images

- pkg/disk/disk_test.go
- pkg/disk/partition_table.go
The first commit ensures that when converting the root partition to btrfs, the enlarged size from a blueprint mountpoint is carried over to the created btrfs subvolume.
The second commit adds a test to check whether the blueprint customizations are correctly applied to the partition table. It verifies that the correct mountable is created and that all sizeables above the mountable have at least the minimum size specified in the blueprint.
> fix / growth when converting a pt to btrfs and cover it with a test

- pkg/blueprint/customizations.go
Callers of GetUser() do not expect to receive an empty slice, which is causing unexpected condition handling.
https://github.com/osbuild/images/blob/e734c0c716d5d93d6daca1433491eb6e67d74945/pkg/distro/rhel/rhel9/options.go#L106-L107
https://github.com/osbuild/images/blob/e734c0c716d5d93d6daca1433491eb6e67d74945/pkg/distro/rhel/rhel9/options.go#L210-L211
> blueprint: return nil instead of empty user slice in GetUsers()

- cmd/otk-gen-partition-table/main.go
- cmd/otk-gen-partition-table/main_test.go
This is similar to https://github.com/osbuild/images/pull/827 but this time for the `otk-gen-partition-table` which was forgoten in this other PR :(
> cmd/otk-gen-partition-table: fix to be wrapped in a "tree" json

- pkg/blueprint/blueprint_test.go
- pkg/blueprint/filesystem_customizations.go
- pkg/blueprint/filesystem_customizations_test.go
In the filesystem customization, the toml tags clearly sets the `MinSize` field's key to `minsize`, this is also reflected in `bootc-image-builder` docs. However, the custom unmarshallers are actually wrong, they still refer to the old `size` name (see #825).
This PR fixes the unmarshallers, and adds more test coverage.
> blueprint: fix filesystem customization parsing

- internal/cmdutil/rand.go
Printing on stdout interferes with the json output from `otk-gen-partition-table`.
> cmdutil: print rng `TEST MODE...` warning to stderr

- cmd/otk-gen-partition-table/main.go
- cmd/otk-gen-partition-table/main_test.go
We need this to generate bit-by-bit compatible manifests from otk to the ones that `images` generates.
See also https://github.com/osbuild/otk/pull/186
We should probably think about generating this automatically but this unblocks otk for now.
> otk-gen-partition-table: add `part_type` to supported inputs

- pkg/manifest/os.go
- test/config-map.json
- test/configs/edge-ostree-pull-user-minimalenv.json
- test/configs/minimal-environment.json
- test/scripts/generate-ostree-build-config
Installing the `minimal-environment` RPM group implies the installation
of `dracut-config-rescue` which makes `org.osbuild.ostree.preptree` to
fail because `rpm-ostree` detects multiple kernels within the tree
(the usual one and the rescue one). Disabling dracut during the rpm
installation prevents the rescue kernel/initrd to be generated and
makes `rpm-ostree` to finish the compose succesfully.
`rpm-ostree` runs dracut on his own during the compose so this doesn't
seem to affect the final result.
Resolves: #624
> os: disable dracut for ostree based systems on rpm installation

- cmd/otk-gen-partition-table/main.go
- cmd/otk-gen-partition-table/main_test.go
This is needed for the `fedora-40-minimal_raw` image that sets this to "8 MB".
> otk-gen-partition-table: add `start_offset` to allowed values

- pkg/blueprint/blueprint_test.go
- pkg/blueprint/filesystem_customizations_test.go
Small followup for https://github.com/osbuild/images/pull/885
blueprint: extend TestBlueprintParse to make "drift" less
likely
By using the same content encoded in toml/json it is less likely
that there is drift between json/toml when unmarshaling.
---
blueprint: add marshal/unmarshal symetry test
Ensure that marshal/unmarshal are symetric by marshaling and then
unmarshaling to ensure all fields are marshaled/unmarhaled to
the same struct values.
----
blueprint: move test to `blueprint_test` test pattern
> blueprint: some test tweaks

- .github/workflows/tests.yml
CentOS Stream 10 unit tests are currently failing due to an issue with the repositories and we are making it non-essential for merging. However, the fail-fast property defaults to true, which causes the CentOS Stream 9 tests to get cancelled when 10 fails.
Disable fail-fast so that C9S tests keep running when C10S tests fail.
> github: don't fail fast on cs unit tests

- pkg/image/anaconda_live_installer.go
- pkg/manifest/anaconda_installer.go
The live installer build has been installing non-enforcing systems. This is due to a leftover from the image installer setting the system to permissive.
Make it so we apply the contexts and don't write a permissive config for the live installer.
Closes #460 which has been flying under my radar for entirely too long.
> anaconda: enable SELinux for live-installer

- pkg/distro/rhel/images.go
- pkg/manifest/os.go
- pkg/osbuild/rhsm_facts_stage.go
- pkg/osbuild/rhsm_facts_stage_test.go
- pkg/rhsm/facts/facts.go
Allows registered systems to be coupled to existing compliance policies.
---
As it stands this would require composer to fill in these facts in the image options as it does for the api types. For the openscap profile id we could fill it in automatically if an openscap customisation is defined, open to opinions.
> osbuild: add openscap profile and compliance policy id to facts 

- pkg/distro/rhel/rhel10/ami.go
The same has been removed from c10s images.
See https://gitlab.com/redhat/centos-stream/release-engineering/kickstarts/-/merge_requests/50
See https://issues.redhat.com/browse/RHEL-55750?focusedId=25451931&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25451931
> Distro/RHEL-10: remove dracut config for gdisk

- cmd/build/main.go
A quick drive-by commit to tweak the error handling in `cmd/build` to make it more idiomatic go, i.e. use `%w` and drop the `\n` from errors (this should not affect the UX as the fmt.Fprintf() that handles the error adds a `\n`).
> cmd/build: drive-by error handling tweaks

- test/config-map.json
The all-customizations config is limited to RHEL 8 and 9 because a lot of the customizations aren't supported on RHEL 7.  Let's also add RHEL 10 to the mix.
> Test configs for RHEL 10

- pkg/manifest/anaconda_installer_iso_tree.go
In issue #230 it was raised that it is undesirable to automatically reboot when the install is finished. So instead halt the install and show a message to the user.
This is a draft because it changes the existing behavior so users who rely on the auto-reboot (like our tests) will fail [0] - but  if everyone is happy and we consider the old behavior a bug I will undraft it.
Closes: https://github.com/osbuild/bootc-image-builder/issues/230
[0] We can fix this via https://github.com/osbuild/bootc-image-builder/compare/main...mvo5:handle-halt-instead-of-reboot?expand=1
> manifest: wait for user input before rebooting when creating a bootc installer

- .github/workflows/tests.yml
- .gitlab-ci.yml
- test/data/repositories/fedora-41.json
GPG check is disabled for now.  Signature checks are failing.
I will mark the Fedora 41 unit tests job as required once this is merged.
> test: add Fedora 41 repositories

- pkg/image/bootc_disk.go
- pkg/image/bootc_disk_test.go
- pkg/manifest/vpc.go
This will help konflux to build azure/vhd images directly. 
The corresponding `bib` change can be found in https://github.com/osbuild/bootc-image-builder/pull/634.
Closes: https://github.com/osbuild/bootc-image-builder/issues/132
> image: add `vhd`/`vpc` support to `BootcDiskImage`

- pkg/osbuild/rhsm_facts_stage.go
- pkg/osbuild/rhsm_facts_stage_test.go
The name `openscap` should be avoided in favour of compliance where possible.
> pkg/osbuild: replace openscap with compliance in rhsm facts

- pkg/manifest/anaconda_installer_iso_tree.go
This reverts commit 002c25d5b2f664ace182e8f1aefaf1557814a8a3.
We are currently seeing issue with the `bootc-image-builder` iso tests, this maybe the culprit.
[edit: with this revert it seems like the error that we are curerntly seeing goes away so we need to look at this again - but let's first revert to unblock images]
> Revert "manifest: switch to `halt --eject` to avoid auto-reboot"

- cmd/otk-make-fstab-stage/main.go
- cmd/otk-make-fstab-stage/main_test.go
- cmd/otk-make-partition-mounts-devices/main.go
- cmd/otk-make-partition-mounts-devices/main_test.go
- cmd/otk-make-partition-stages/main.go
- cmd/otk-make-partition-stages/main_test.go
- internal/otkdisk/partition.go
- internal/otkdisk/partition_test.go
This commit is a lesson from https://github.com/osbuild/otk/pull/186 as it is right now extremly easy to crash the otk disk externals with bad inputs.
This commit adds basic input validation, it's probably a good idea to also go deeper into the library and make it less trusting about pointers but that is (slightly) orthogonal.
> cmd/otk-*: do basic input validation to avoid crashing too easily

- pkg/distro/rhel/rhel9/edge.go
CIS Level 1 server compliance requires to remove the dnsmasq package.  This is not possible with RHEL for Edge images because it is part of the base image.
THEEDGE-4012
~~DRAFT:~~
- ~~Based on PR #920.~~
- ~~The decision hasn't been finalised yet.~~
> Remove dnsmasq from base package set for edge-commit in RHEL 9.6+ (THEEDGE-4012)

- cmd/otk-make-grub2-inst-stage/export_test.go
- cmd/otk-make-grub2-inst-stage/main.go
- cmd/otk-make-grub2-inst-stage/main_test.go
This external allows us to generate the `org.osbuild.grub2.inst` for `otk`.
E.g. in PR#193 we can now use the following diff:
```yaml
diff --git a/example/centos/centos-9-x86_64-qcow2.yaml b/example/centos/centos-9-x86_64-qcow2.yaml
index 0d6c0cd..b3693d4 100644
--- a/example/centos/centos-9-x86_64-qcow2.yaml
+++ b/example/centos/centos-9-x86_64-qcow2.yaml
@@ -262,20 +262,9 @@ otk.target.osbuild:
${fs_options.devices}
mounts:
${fs_options.mounts}
-              - type: org.osbuild.grub2.inst
-                options:
-                  filename: disk.img
+            - - otk.external.otk-make-grub2-inst-stage:
platform: i386-pc
-                  location: 2048
-                  core:
-                    type: mkimage
-                    partlabel: gpt
-                    filesystem: …
```
> cmd: add new `otk-make-grub2-inst-stage` external

- .github/workflows/tests.yml
Fedora 41 unit tests are currently failing due to an issue with the repositories and are non-essential for merging (which is common for rawhide and early branching periods).
However, the fail-fast property defaults to true, which causes the other Fedora tests to get cancelled when F41 fails.
Disable fail-fast so that F40 tests keep running when F41 tests fail.
This is the same change we made for CS tests
3b81a908327c740b95a86b630d993dfad31fe5cb (#904)
This PR is simple but high priority for unblocking other PRs from merging.
> github: don't fail fast on Fedora unit tests

- pkg/blueprint/customizations.go
- pkg/blueprint/customizations_test.go
- test/configs/all-customizations.json
- test/configs/all-with-fips.json
- test/configs/oscap-generic.json
This is something I've mentioned a few times in the past but never got around to doing.  With the upcoming changes to partitioning (#926), I think this is a good opportunity to start with a proof of concept and the canonical example for customization simplification in images.  The general idea is that blueprints in osbuild-composer are the **canonical, user-facing version of the structure**.  The images counterpart has no obligation to maintain backwards compatibility, or even have the same exact structure as the real blueprints.
Extra considerations:
- We (well, @croissanne) recently (re)introduced the idea of moving blueprints out into its own project, and having a schema for the _actual real_ blueprint format.  I think this is a great idea and takes care of any issues of divergence …
> blueprint: remove the sshkey customization

- cmd/otk-gen-partition-table/main.go
- cmd/otk-gen-partition-table/main_test.go
- pkg/disk/disk.go
- pkg/distro/fedora/partition_tables.go
The existing code to create EFI system partitions was making
assumptions about running on a GPT partition. This is no longer
true with https://github.com/osbuild/otk/pull/199 so this commit
fixes the code to create a valid ESP system partition on a DOS
partition table.
> otk-gen-partition-table: support EFI system on DOS partitions

- pkg/distro/rhel/rhel9/ami.go
- pkg/distro/rhel/rhel9/azure.go
- pkg/distro/rhel/rhel9/distro.go
- pkg/distro/rhel/rhel9/distro_test.go
- pkg/distro/rhel/rhel9/gce.go
Drop the RHSM configuration from RHEL-9 Azure and EC2 image definitions, since it will be applies as a customization in the release configuration.
Additionally, unify the RHUI and non-RHUI image types as much as possible. Internally rename the original "RHUI" image types and functions to "internal", since they no longer have any RHUI-specific bits. However, these are still built only internally in Brew. We actually can't completely drop the RHUI image types, because these are built as compressed files in Brew. We could modify the implementation, but maybe let's just wait for OTK.
Lastly, drop the GCE RHUI image, which was never used and it is not built anywhere (only in osbuild-composer CI, but that can be fixed), even internally. The image could be built by customizing the GCE image …
> [RHEL-9] Drop RHSM and RHUI-specific config from Azure and EC2 images (COMPOSER-2308)

- pkg/distro/fedora/package_sets.go
This PR moves the addition of `bootupd` to the `iot-commit` package set from Fedora 40 to 41. 
The change to include `bootupd` was deferred to Fedora 41 and causes issues with the [bootloader in F40](https://github.com/fedora-iot/iot-distro/issues/58)
> fedora-iot: move bootupd to f41

- pkg/distro/distro.go
- pkg/distro/distro_test.go
- pkg/distro/distro_test_common/distro_test_common.go
- pkg/distro/fedora/imagetype.go
- pkg/distro/rhel/imagetype.go
- pkg/distro/test_distro/distro.go
- pkg/reporegistry/reporegistry.go
- pkg/reporegistry/reporegistry_test.go
- Fix loading of repositories of tested distros in unit tests
- Fix `TestDistro_ManifestFIPSWarning`
- Distro / ImageType: remove `PackageSetsChains()`, because it was not used for anything.
> Various fixes

- cmd/otk-resolve-ostree-commit/export_test.go
- cmd/otk-resolve-ostree-commit/main.go
- cmd/otk-resolve-ostree-commit/main_test.go
- pkg/ostree/ostree.go
New `cmd` for resolving ostree commits for otk.
The resolver is a simple call to ostree.Resolve() which handles resolving ostree input options to an ostree.CommitSpec.
The resolver returns the input as-is when the ref is a commit ID (there is nothing to resolve).  This can happen when a user wants to pull an ostree commit by its ID rather than specifying a ref to resolve.
> Add ostree commit resolver for otk: otk-resolve-ostree-commit (COMPOSER-2349)

- cmd/otk-resolve-containers/export_test.go
- cmd/otk-resolve-containers/main.go
- cmd/otk-resolve-containers/main_test.go
- internal/testregistry/testregistry.go
- pkg/container/client_test.go
- pkg/container/resolver_test.go
New `cmd` for resolving containers for otk.
The resolver is a thin wrapper around the container.Resolver.  It can handle multiple containers for the same architecture in one call.
> Add container resolver for otk: otk-resolve-containers (COMPOSER-2293)

- Schutzfile
- cmd/build/main.go
- cmd/gen-manifests/main.go
- cmd/osbuild-playground/playground.go
- pkg/dnfjson/dnfjson.go
- pkg/dnfjson/dnfjson_test.go
- pkg/sbom/document.go
- pkg/sbom/document_test.go
This PR depends on https://github.com/osbuild/osbuild/pull/1818
- Add a simple `sbom` package for working with SBOM documents.
- Extend the `dnfjson` `Solver.Depsolve()` to support requesting SBOM documents for depsolved transactions.
> Add initial support for generating SPDX SBOM documents (COMPOSER-2274)

- cmd/gen-manifests/main.go
The current code will only generate "0" version numbers for packages and releases. This limits the usefulness of this mock in the tests for otk. Instead generate predictable but (mostly) non-zero numbers based on the modulo of the first and second char of the pkgname.
Useful for e.g. https://github.com/osbuild/otk/pull/196 as it will ensure that the `fragment/grub2.yaml` actually changes depending on the kernel name.
> gen-manifests: create predictable version/release numbers in mockDepsolve

- cmd/gen-manifests/main.go
This commit adds the architecture to the faked packageset that is generated via mockDepsolve() to ensure we catch cross-arch manifest differences.
> gen-manifests: use `archName` in mockDepsolve()

- cmd/gen-manifests/main.go
This commit adds excluded packages to the generated manifest when the `gen-manifests` command is run in the `mockDepsolve()` mode.
This allows us to compare the generated otk and images manifests with more confidence.
> [RFC] gen-manifests: add excluded packages via `exclude:` prefix in mock

- cmd/gen-manifests/main.go
- cmd/otk-resolve-ostree-commit/export_test.go
- cmd/otk-resolve-ostree-commit/main.go
- cmd/otk-resolve-ostree-commit/main_test.go
- internal/cmdutil/mock.go
Read the OTK_UNDER_TEST env var, which we use in otk to enable test mode for our resolvers, and return a mocked checksum.
> cmd/otk-resolve-ostree-commit: support mocking ostree resolve calls

- .github/workflows/tests.yml
This commit removes `-v` from `go test`. The test output is very long (17k lines according to GH) and most is just:
```
...
--- PASS: TestRPMDeduplication (0.00s)
...
```
but when trying to find a failing test (like in PR#945) scrolling through to find the actual failing one becomes a bit cumbersome.
So this commit drops `-v`.
> github: drop `-v` from `go test`

- pkg/dnfjson/dnfjson_test.go
This commit fixes a race in the `TestRunErrorEmptyOutput` test that was observed in PR#945:
```
2024-09-24T08:57:56.6596870Z === RUN   TestRunErrorEmptyOutput
2024-09-24T08:57:56.6597398Z     dnfjson_test.go:857:
2024-09-24T08:57:56.6598067Z         	Error Trace:	/__w/images/images/pkg/dnfjson/dnfjson_test.go:857
2024-09-24T08:57:56.6599180Z         	Error:      	Error message not equal:
2024-09-24T08:57:56.6600232Z         	            	expected: "DNF error occurred: InternalError: dnf-json output was empty"
2024-09-24T08:57:56.6601715Z         	            	actual  : "encoding request for /tmp/TestRunErrorEmptyOutput2675948157/001/dnfjson failed: write |1: broken pipe"
2024-09-24T08:57:56.6602938Z         	Test:       	TestRunErrorEmptyOutput
2024-09-24T08:57:56.6603675Z --- FAIL: …
```
> dnfjson: fix race in TestRunErrorEmptyOutput

- pkg/image/bootc_disk.go
- pkg/image/bootc_disk_test.go
- pkg/manifest/export_test.go
- pkg/manifest/tar.go
- pkg/manifest/tar_test.go
- pkg/osbuild/tar_stage.go
- pkg/osbuild/tar_stage_test.go
There is a request that we provide a new image type that can
be imported directly into GCE. This requires a `tar.gz` with
a `disk.raw` inside and specific tar options.
This commit adds the needed pipeline to generate this.
Note that this will require a way to rename files during
the tar build as we do not want to hardcode the raw image
filename.
This needs https://github.com/osbuild/osbuild/pull/1886 and will be used in https://github.com/osbuild/bootc-image-builder/pull/646
> image: add new `gce` pipeline to `BootcDiskImage`

- cmd/gen-manifests/main.go
This is one possible fix for the issue raised in
https://github.com/osbuild/otk/pull/209/files#r1771119550
I.e. how we can ensure that we have the same repo configuration
between images and otk.
It works by adding a pseudo package for each repo, the resulting
diff in otk looks like this:
```yaml
diff --git a/test/data/images-ref/centos/9/x86_64/qcow2/centos_9-x86_64-qcow2-empty.yaml b/test/data/images-ref/centos/9/x86_64/qcow2/centos_9-x86_64-qcow2-empty.yaml
index b067dd1..7021cba 100644
--- a/test/data/images-ref/centos/9/x86_64/qcow2/centos_9-x86_64-qcow2-empty.yaml
+++ b/test/data/images-ref/centos/9/x86_64/qcow2/centos_9-x86_64-qcow2-empty.yaml
@@ -29,6 +29,9 @@ pipelines:
- id: sha256:93cd8e20fc07f08337cb9d9fa9996274658f6395574e874379c4c4157e922700
- id: …
```
> gen-manifest: include repo as pseudo package

- .github/workflows/test-osbuild-composer-intergation.yml
Due to https://github.com/osbuild/osbuild-composer/commit/7bdd0363 "replace-allow-list" is now already in `.golangci.yml` and should not be added twice or the `golangci-lint` test fails.
> github/workflows/test-osbuild-composer-intergation: fix integration test

- pkg/dnfjson/dnfjson_test.go
The tests are currently failing on fedora 41 (SBOM implementation missing for DNF5)
but that's no reason to really segfault just due to a failed test.
> pkg/dnfjson/dnfjson_test.go: fix crashing on failing test

- cmd/gen-manifests/main.go
This commit adds the manifest name to the mock depsolve URL output so that we can test for it from inside otk. This will help with issues like https://github.com/osbuild/otk/pull/255/files#r1782953752
This will require a re-generate of all otk reference manifests.
> cmd: add "archName" to gen-manifests mock dnf solver URLs

- pkg/manifest/coreos_installer.go
Install only the minimal number of dracut modules required
by the coreos installer to avoid issues during the installation.
Resolves: fedora-iot/iot-distro#5
> coreos-installer: install only the required dracut modules

- cmd/otk-gen-partition-table/main.go
- cmd/otk-gen-partition-table/main_test.go
This commit adds support for "raw" partitions without a "payload",
i.e. no filesystem or LVM volume or similar. This is used for the
PPC64/s390x partition table that looks like this:
```yaml
otk.define:
filesystem:
modifications:
otk.external.otk-gen-partition-table:
modifications:
${filesystem.modifications}
properties:
type: dos
default_size: "10 GiB"
uuid: "0x14fc63d2"
partitions:
- name: ppc-boot
bootable: true
size: "4 MiB"
part_uuid: ""
part_type: "41"
- name: boot
mountpoint: /boot
label: boot
size: "1 GiB"
type: "xfs"
fs_mntops: defaults
part_uuid: ""
- name: root
mountpoint: /
type: "xfs"
size: "2 GiB"
fs_mntops: defaults
part_uuid: ""
```
Thanks to Florian Schüller for the initial implementation/research
here, see also https://github.com/osbuild/images/pull/952 
--- …
> otk-gen-partition-table: add support for ppc64/s390x partition tables

- test/config-map.json
We never had a test configuration where an ostree commit is built as child of another one.  Let's add a simple configuration where an ostree commit is built from an existing one.
The parent commit is the base image with no customizations (empty) and the child commit adds a user (edge-ostree-pull-user).
> test: build edge-commit with parent

- README.md
The section links to the general osbuild team developer guide, but the local developer documentation is also very useful.  The page is already linked from the HACKING.md file, but that could be missed by someone focusing on the README and following the link to osbuild.org.
Sidenote: We need to document the `btrfs-progs-devel` and `device-mapper-devel` dependencies better.  They're not required for building the binaries or running the tests.  They're only needed when using local container storage, which we don't test in our unit tests (or our integration tests, for that matter).  So maybe we should also be testing that here instead of relying on bootc-image-builder and osbuild-composer.
> README: link to docs/developer in Contributing section

- pkg/manifest/os.go
- pkg/manifest/os_test.go
The current code will install python3-toml on fedora and also
on rhel11 (once it comes out) because that is the default for
unhandled distros. With `tomlib` in the stdlib this is no
longer needed.
[draft as it has no test(s)]
> manifest: extract tomlPkgsFor() helper and fix ordering

- cmd/otk/osbuild-make-ostree-source/export_test.go
- cmd/otk/osbuild-make-ostree-source/main.go
- cmd/otk/osbuild-make-ostree-source/main_test.go
- cmd/otk/osbuild-resolve-ostree-commit/main.go
- internal/otkostree/types.go
A new command for otk that creates the org.osbuild.ostree source object based on the resolved ostree commit data generated from the osbuild-resolve-ostree-commit command.
> cmd: New otk external: otk-make-ostree-source

- .github/workflows/comment-integration-failure.yml
The purpose of this new workflow is to run when certain actions are allowed to cause errors without failing but PR authors and reviewers should be notified of issues.  The goal is, instead of having actions that are allowed to fail and are marked as not required, the actions themselves will succeed but will communicate an error message through a shared artifact that this action can read and use to post a comment on the PR.
The action is run as a 'workflow_run' to have access to secrets (Schutzbot's access token).
The action is not finalised in this commit.
The plan is to merge this into `main` as is, so that GitHub will pick up the new workflow and we can iterate on the implementation in a follow-up PR, since GitHub will not run actions defined in workflows that are not part of the main …
> workflow: generate PR comments when non-required tests fail and let the action itself succeed (part 1)

- docs/image-types/rhel8/google-gce.md
- pkg/cloud/gcp/compute.go
We need to update these to match what is being set for the rhel9 and rhel8 images produced by Google (on behalf of Red Hat) today.
Also rework the comments to add context.
```
root@24de7c60b75c:~# gcloud compute images describe-from-family --project rhel-cloud rhel-8
architecture: X86_64
archiveSizeBytes: '9314286336'
creationTimestamp: '2024-09-10T13:40:19.727-07:00'
description: Red Hat, Red Hat Enterprise Linux, 8, x86_64 built on 20240910
diskSizeGb: '20'
enableConfidentialCompute: false
family: rhel-8
guestOsFeatures:
- type: UEFI_COMPATIBLE
- type: VIRTIO_SCSI_MULTIQUEUE
- type: SEV_CAPABLE
- type: SEV_SNP_CAPABLE
- type: SEV_LIVE_MIGRATABLE
- type: SEV_LIVE_MIGRATABLE_V2
- type: GVNIC
- type: IDPF
id: '2720211119037550684'
kind: compute#image
labelFingerprint: 42WmSpB8rSM= …
```
> cloud/gcp: update guest OS features to match prod RHEL images

- pkg/image/bootc_disk.go
Import with `gcloud` cli requires the file to ends with `.tar.gz`, otherwise the command fails
```
gcloud compute images create --help
[...]
--source-uri=SOURCE_URI
The full Cloud Storage URI where the disk image is stored. This file
must be a gzip-compressed tarball whose name ends in .tar.gz. For
more information about Cloud Storage URIs, see
https://cloud.google.com/storage/docs/request-endpoints#json-api.
```
> osbuild: Rename GCE output from .tgz to .tar.gz

- .github/workflows/tests.yml
- .gitignore
- .pre-commit-config.yaml
- .spellcheck-en-custom.txt
- Containerfile
- Makefile
- README.md
Implementing `make test` to be able to run the tests locally
and implements `make gh-action-test` to run github action "unit-tests-fedora" locally
Also changes the github action to just use the implementation in `Makefile`
> Makefile: initial version of makefile, replace GH action

- pkg/distro/fedora/version.go
Fedora is currently building Release Candidates. Since we use the versions to determine if we turn on the preview notice we need to bump the version for branched to remove it.
> distro/fedora: bump branched version

- pkg/reporegistry/error.go
- pkg/reporegistry/reporegistry.go
- pkg/reporegistry/repository.go
Add `NoReposLoadedError` custom error type for the case when any function that is supposed to load repository configs, does not load any. Use it in all functions that are directly loading repositories from configuration files.
I considered `NoReposError` name, but that could be later added for functions such as `RepoRegistry.ReposBy...()`, in case there are no repositories in the RepoRegistry for the given image type / arch.
This is a follow-up to https://github.com/osbuild/osbuild-composer/pull/4378
> reporegistry: add NoReposLoadedError and use it

- cmd/otk/osbuild-resolve-ostree-commit/main.go
- pkg/ostree/ostree.go
- pkg/ostree/ostree_test.go
To complete edge service Pulp migration, we need to be able to resolve and download ostree commits from Pulp running behind `console.redhat.com` proxy which only supports MTLS for authentication. I have found that some MTLS support is already present but it does not make much sense why RHSM is used. I cannot figure out a workflow why ostree repo would be published via RHSM cert. I am not aware of any RH ostree content hosted via RH CDN.
_The patch quite evolved during the review so editing the description so it is more appropriate._
> ostree: configurable MTLS config for ostree resolve

- pkg/manifest/build.go
- pkg/osbuild/container_deploy_stage.go
- pkg/osbuild/container_deploy_stage_test.go
Make `skopeo copy` to remove the signatures of signed containers by default to workaround build failures until containers/image#2599 is implemented.
Depends: osbuild/osbuild#1906
Resolves: osbuild/bootc-image-builder#681
> feat: remove signatures in container deployments by default

- pkg/image/bootc_disk.go
- pkg/image/disk.go
- pkg/image/gce.go
- pkg/image/gce_test.go
This commit extracts a common helper to setup the right tar options for the GCE tar file generation. The options that need to be passed to tar for GCE need to be exactly right so let's make sure we only have a single place where they are set.
> many: extract newGCETarPipelineForImg() helper

- pkg/distro/rhel/rhel8/azure.go
In RHEL 8 and RHEL 9, systemd-resolved is available but provided as a Technology Preview only [1].
systemd-resolved does not need to be enabled in Azure image types [2]. Removing it from the enabled services list leaves it up to the vendor preset to determine the state of the service.  The executable itself is part of the systemd package.  In RHEL 9, it is a separate package and is not installed in any of our images.
[1] https://access.redhat.com/solutions/5647181
[2] See COMPOSER-2380
> rhel8/azure: don't enable systemd-resolved (COMPOSER-2380)

- pkg/disk/disk.go
Add a new enum, FSType, for referring to all supported filesystem types.  This is currently not used but will be part of the new custom partition table generator.
> disk: define FSType enum for all supported types

- pkg/distro/distro.go
- pkg/distro/fedora/imagetype.go
- pkg/distro/rhel/imagetype.go
- pkg/distro/test_distro/distro.go
- pkg/platform/bootmode.go
---
Move the BootMode enum from pkg/distro to pkg/platform.  We want to import BootMode to the disk package, which would create an import loop with distro.
> pkg/{distro,platform}: move BootMode to platform

- pkg/disk/disk.go
- pkg/disk/disk_test.go
- pkg/disk/lvm.go
- pkg/disk/lvm_test.go
- pkg/disk/partition_table.go
---
**disk: refactor LVM Logical Volume name generation**
The VolumeGroup.CreateLogicalVolume() function assumed that the given
name was a mountpoint and would automatically escape it, append 'lv',
and append numbers in case of collisions.  This made it impossible to
use the helper function for LV creation with desired names.
Refactor the function and modify all the calls so that now it uses the
provided name without validating, escaping, or checking for collisions,
and generates a name from the payload's mountpoint when one is not
provided.
The CreateMountpoint() function's functionality is not affected.
---
**disk: helper function for generating unique names**
The new genUniqueString() function follows the …
> Refactor LVM LV name generation and extract unique name generator into helper

- test/scripts/boot-image
- test/scripts/imgtestlib.py
Pylint recently grew a new issue type 'too-many-positional-arguments', which is separate from the more general 'too-many-arguments'.  Our offending functions match both.
> test/scripts: pylint: disable=too-many-positional-arguments

- pkg/reporegistry/repository.go
This commit removes the direct log.Printf() from the repo loading. With the coming daemonless CLI frontend to image building these prints are distracting for our users.
Instead logrus (which is already used in the images library) is used with the appropriate "Debugf()" and "Warnf()" methods.
> reporegistry: move to logrus instead of log.Printf()

- pkg/disk/disk_internal_test.go
- pkg/disk/disk_test.go
- pkg/disk/export_test.go
- pkg/disk/partition_table_internal_test.go
Separate most disk tests into internal and external ones.
- disk_test.go: was internal (package disk) and is now external (package disk_test)
- Function `entityPath()` and method `PartitionTable.findDirectoryEntityPath()` are now exported for tests in export_test.go
- Test partition tables moved to partition_table_internal_test.go and exported.
- Unique string tests moved to new file: disk_internal_test.go
> disk: separate most tests from package

- pkg/disk/disk.go
- pkg/disk/enums_test.go
---
Add a new enum, PartitionTableType, for referring to the two partition table types, "dos" and "gpt".
This is currently not used but will be part of the new custom partition table generator.
> disk: define PartitionTableType enum for partition table types

- pkg/distro/id.go
- pkg/distro/id_test.go
- pkg/distrosort/sort.go
- pkg/distrosort/sort_test.go
[edit: alternative version of https://github.com/osbuild/images/pull/1000 - does not support `-beta` and similar semver features but reuses more of the existing infrastructure]
distrosort: add new `distrosort.Names` helper
This commit adds a new `distrosort.Names()` helper that can be
used sort sort distro names. It will take version numbers of
the distro into account and sort by semantic version. This
is useful in e.g. user-interfaces where we want to present
the version in a nicely sorted way.
Sorting follows the go-version library which supports semantic
versioning [0] so anything supported there will be sorted
correctly including `-beta` suffixes and similar (see the
spec for details).
Note that this is an extra pkg because the `distro` and `distroid`
would be circular imports …
> distrosort: add new `distrosort.Names` helper

- pkg/disk/disk.go
- pkg/disk/partition_table.go
- pkg/disk/partition_table_test.go
- pkg/distro/fedora/partition_tables.go
---
The PR introduces two helper functions, `EnsureRootFilesystem()` and `EnsureBootPartition()`.  These will add, respectively, a root filesystem and a boot partition to a partition table if they don't already exist.
> Partition table helper functions for adding root filesystem and boot partition

- cmd/boot-aws/main.go
- pkg/cloud/awscloud/awscloud.go
We got a request for supporting custom role names, let's start by
adding support for it in the images library.
> awscloud: add import role parameter to AMI registration

- pkg/dnfjson/dnfjson.go
- pkg/dnfjson/dnfjson_test.go
**dnfjson: add Solver string to DepsolveResult**
The solver string is returned from the depsolver with the response and
identifies the solver library that was used.  Currently, it is either
dnf or dnf5.
Returning it with the DepsolveResult can be useful for reproducibility
and troubleshooting.
---
**dnfjson: skip sbom tests with dnf5**
SBOMs are not yet supported when using the dnf5 solver in
osbuild-depsolve-dnf.  Running the test on Fedora 41, which uses dnf5 by
default, makes the test fail.
Sniff the solver used using a quick, simple depsolve to get the result,
and skip any SBOM tests if the solver is dnf5.
---
> dnfjson: skip sbom tests with dnf5

- pkg/distro/rhel/images_test.go
- pkg/distro/rhel/imagetype.go
This commit fixes a crash in when the rhel ImageType.PartitionType() is called, here the BasePartitionTables function pointer is sometimes not initialized (e.g. in the `centos9/edge-commit` image type).
> rhel: fix crash when PartitionType() is requested

- pkg/disk/disk.go
- pkg/disk/partition_table.go
- pkg/disk/partition_table_test.go
---
The PR introduces a helper function, `AddPartitionsForBootMode()`.  The function takes a partition table and boot mode and adds partitions to satisfy the boot mode requirements:
- BIOS/legacy: adds a 1 MiB BIOS boot partition.
- UEFI: adds a 200 MiB EFI system partition.
- Hybrid: adds both.
> disk: AddPartitionsForBootMode() helper function 

- Schutzfile
- pkg/dnfjson/dnfjson_test.go
Remove the code that skips the sbom test with dnf5.  The
osbuild-depsolve-dnf package now depends on python3-dnf in Fedora 41 and
configures it to use it, so as far as images is concerned, the sboms
should always be supported by the depsolver.
This reverts commit https://github.com/osbuild/images/commit/5134c8b620d3ab24174603cfa8c827bb78db7c45 (PR #1017).
> Revert "dnfjson: skip sbom tests with dnf5"

- .github/workflows/test-osbuild-composer-integration.yml
The comments were referring to the merge-base between the PR and main being used to test the base case when in fact the base is the HEAD of main at the time the PR was created or updated.
This commit fixes the comments to reflect reality.
> github: fix the comments in test-osbuild-composer-integration

- pkg/imagefilter/filter.go
- pkg/imagefilter/filter_test.go
- pkg/imagefilter/imagefilter.go
- pkg/imagefilter/imagefilter_test.go
This commit creates a new `imagefilter` package that can be used
to create a filter for the available images that can be build by
the images library.
Support for prefixes and fnmatch style globbing is available.
This will eventually allows us to do:
```
$ image-builder --list-images --filter arch:aarch64 --filter type:qcow*
or
$ image-builder --list-images --filter ami
```
The filtering can be both with or without a prefix, i.e. when doing
a "simple" search all common fields (disro,arch,imageType) are checked
but with a prefix search things can be narrowed down more.
Initially the following prefixes filters are supported:
"distro:" - the distro name, e.g. rhel-9, or fedora*
"arch:" - the architecture, e.g. x86_64
"type": - the image type, e.g. ami, or qcow?
"bootmode": - the bootmode, …
> pkg: add new `imagefilter` package with an `ImageFilter`

- pkg/distro/fedora/package_sets.go
According to the anaconda team we should be using the `anaconda-install-img-deps`
metapackage to install all the boot.iso image dependencies.
Relates: fedora-iot/iot-distro#66
> fix: install anaconda-install-img-deps package in anaconda installers.

- pkg/blueprint/filesystem_customizations.go
- pkg/blueprint/filesystem_customizations_test.go
If an element in the `customizations.filesystem` array is not an object, the existing code would fail the conversion without an error, but would fail on the `d["mountpoint"].(type)` conversion, which produces an error message that isn't very useful:
```
mountpoint must be string, got <nil> of type <nil>
```
The commit catches the conversion error and instead prints a more useful error message.
> blueprint: add map conversion check to fs customization unmarshaller

- pkg/imagefilter/formatter.go
- pkg/imagefilter/formatter_test.go
This commit adds a new `ResultFormatter` interface that supports
outputing the results as text or JSON.
(this is another splitout from https://github.com/osbuild/images/pull/997)
> imagefilter: add `ResultFormatter` type to support flexible  output

- pkg/ostree/ostree.go
Makes sure MTLS is checked for `nil`.
> ostree: skip MTLS on nil

- pkg/ostree/ostree.go
I think proxy might be unset or something, not sure why it does not parse. Ostree jobs with matching Pulp URLs are erroring out with:
```
"details": "error sending request to ostree repository \"https://mtls.xxxx.redhat.com/api/pulp-content/edge-integration-test-2/lzap-rhel9/refs/heads/rhel/9/x86_64/edge\": Get \"https://mtls.xxxx.redhat.com/api/pulp-content/edge-integration-test-2/lzap-rhel9/refs/heads/rhel/9/x86_64/edge\": proxyconnect tcp: dial tcp :0: connect: connection refused"
```
This should at least show what is stored in there.
> worker: parse ostree proxy early

- cmd/gen-manifests/main.go
- cmd/list-images/main.go
- cmd/osbuild-composer-image-definitions/main.go
- pkg/distro/distro_test_common/distro_test_common.go
- pkg/imagefilter/imagefilter_test.go
- pkg/reporegistry/reporegistry.go
- pkg/reporegistry/reporegistry_test.go
- pkg/reporegistry/repository.go
- pkg/rpmmd/repository.go
- test/data/repositories/testrepos.go
This commit is a (hopefully) less controversial version of: https://github.com/osbuild/images/pull/1037
Here only a new helper to load repository information from an `fs.FS` is added and only used for loading the test repositories.
This will help to have a single test repository that can be embedded accross osbuild-composer, image-builder and images.
It also removes the public "NewTestedDefault()" in favor of a new `testrepos.New()` helper so that the `reporegistry` only has non-test API left.
[*maybe* this should be split into two commits actually]
This will allow me to use the test repos in the new `image-builder-cli` repo without the need to copy/import files from another git repo.
> reporegistry: add new `LoadAllRepositoriesFromFS` and use in tests

- pkg/ostree/ostree.go
- pkg/ostree/ostree_test.go
This commit extracts a `httpClientForRef` helper from the `resolveRef()`
function. This helps with readability and testability. It also adds
a test for the proxy setting.
Not ideal as the test knows a bit too much about the implementation details but OTOH realtively straightfoward to add.
[build on top of https://github.com/osbuild/images/pull/1050]
> ostree: extract `httpClientForRef` from resolveRef

- pkg/blueprint/disk_customizations.go
- pkg/blueprint/disk_customizations_test.go
- pkg/blueprint/filesystem_customizations.go
- pkg/blueprint/filesystem_customizations_test.go
- pkg/blueprint/toml_json_bridge.go
- pkg/datasizes/size.go
- pkg/datasizes/size_test.go
This is an alternative implementation of the idea in https://github.com/osbuild/images/pull/1049 based on feedback from @thozza (thanks!). 
---
blueprint: decouple FilesystemCustomization from marshaling
This commit decouples the marshaling representation of the
`FilesystemCustomization` from the actual struct. This means that
we can reuse custom unmarshaling via datasizes.Size and also
have our external represenation "pure".
If we continue using this pattern is also means that we can rename
fields in the marshaling and provide compatbility easily.
Thanks to Thozza, c.f.
https://github.com/osbuild/images/pull/1049#issuecomment-2493261642
and
https://github.com/osbuild/images/pull/983
---
datasizes: add new `Size` type with json/toml decoding
support
This commit adds a new `datasizes.Size` …
> datasize, blueprint: add new datasizes.Size type and use in blueprints

- pkg/blueprint/disk_customizations.go
- pkg/blueprint/disk_customizations_test.go
- pkg/disk/partition_table.go
This commit changes some ordering and var names, very minor, test tweaks, c.f.
* https://github.com/osbuild/images/pull/1041#discussion_r1848242436
* https://github.com/osbuild/images/pull/1041#discussion_r1848251524
* https://github.com/osbuild/images/pull/1041#discussion_r1848277860
* https://github.com/osbuild/images/pull/1041#discussion_r1848288833
* https://github.com/osbuild/images/pull/1041#discussion_r1848401437
* https://github.com/osbuild/images/pull/1041#discussion_r1848403803
* https://github.com/osbuild/images/pull/1041#discussion_r1849936535
* https://github.com/osbuild/images/pull/1041#discussion_r1849952026
> blueprint,disk: tiny style changes

- pkg/disk/export_test.go
- pkg/disk/partition_table.go
This commit extracts a new `maybeAddBootPartition()` helper to
make the `NewCustomPartitionTable()` a little bit more linear
to read.
Followup, c.f.
https://github.com/osbuild/images/pull/1041#discussion_r1848298181
---
disk: unexport `AddBootPartition` and
`AddPartitionsForBootMode`
Those two are not used outside of `disk` so let's unexport them
to keep a smaller API.
Followups, c.f.
https://github.com/osbuild/images/pull/1041#discussion_r1848291704
> disk: extract `maybeAddBootPartition()` helper

- pkg/blueprint/disk_customizations.go
- pkg/blueprint/disk_customizations_test.go
This commit enforces the use of "minsize" for disk customizations. Without this the `disk` code will create zero sized partitions when `minsize` is omited which then later yields a strange error from osbuild:
```
Building manifest-qcow2-raw-vmdk-vhd-gce.json
<stdin> has errors:
.pipelines[1].stages[2].options.volumes[0].size:
'0B' does not match '[1-9][0-9]*[bBsSkKmMgGtTpPeE]?'
2024/11/25 09:35:42 error: cannot run osbuild: running osbuild failed: exit status 2
```
We could also attempt to fix this by making guesses about minsize (which is what the existing filesystem customizations do). But that seems less appropriate here as this is about finer control and an arbitrary size of e.g. `1 GiB` seems unexpected. Another alternative would be to infere from the parent container size and split …
> [RFC] blueprint: make `minsize` required for `disk.Customizations`

- pkg/distro/fedora/distro_test.go
- pkg/distro/fedora/imagetype.go
This commit will run `ValidateLayoutConstraints()` when a `DiskCustomization` is used.
Fwiw, the fact that we have to implement this in every distro (and in bib) and must not forget about it makes me wonder if we shouldn't flip this around. Call it by default but return a distinct error type (ValidateLayoutConstraintsError) when it is violated that clients (like a potential low-level otk partitioner) could choose to ignore. Wdyt?
> distro: run `ValidateLayoutConstraints()` when using PartitionCustomizations

- pkg/osbuild/ostree_source.go
Need this for the newly added `org.osbuild.mtls` secret that is required for Pulp MTLS feature.
> ostree: allow passing any ostree source secrets

- pkg/distro/distro_test.go
- pkg/distro/distro_test_common/distro_test_common.go
- pkg/distro/fedora/imagetype.go
- pkg/distro/rhel/imagetype.go
Modify `checkOptions()` of all distributions to fail if the OSTree image options are provided for the non-OSTree-based image type. Previously, these would be silently ignored. Add a unit test to verify the behavior.
> Distro: fail on OSTree image options being provided for non-OSTree based image types

- pkg/reporegistry/repository.go
- pkg/reporegistry/repository_test.go
After the rework done by PR#1038 [1], the `configFile` changed from the file path string to `fs.File` instance. As a result, logging it makes the output verbose, as it logs the whole content of the loaded file (repo URLs, GPG keys, etc.). Revert to the old behavior by logging `fileEntry.Name()` for the loaded repository.
[1] https://github.com/osbuild/images/pull/1038
> LoadAllRepositoriesFromFS: log only filenames of loaded repositories

- pkg/distro/rhel/rhel10/ami.go
- pkg/distro/rhel/rhel10/azure.go
- pkg/distro/rhel/rhel10/distro.go
- pkg/distro/rhel/rhel10/distro_internal_test.go
- pkg/distro/rhel/rhel10/distro_test.go
- pkg/distro/rhel/rhel10/sap.go
- test/config-map.json
Add the following image types:
- ec2 (x86_64, aarch64)
- ec2-ha (x86_64)
- ec2-sap (x86_64)
- azure-rhui (x86_64, aarch64)
- azure-sap-rhui (x86_64)
These are based on RHEL-9 versions, with one difference for SAP images not including `gtk2` and  `libcanberra-gtk2` packages removed from RHEL-10. The internal team working on SAP is aware of this, and we may need to adjust this eventually, but this is a good starting point.
Related to https://issues.redhat.com/browse/COMPOSER-2357
> [RHEL-10] add internal-only image types (COMPOSER-2357)

- pkg/disk/disk_test.go
Follow-up from #1072
(see https://github.com/osbuild/images/pull/1072#discussion_r1861733611)
>  disk: test ForEachMountable()

- pkg/disk/disk_test.go
- pkg/disk/partition_table.go
- pkg/disk/partition_table_test.go
- pkg/osbuild/fstab_stage_test.go
Follow-up from #1072 (https://github.com/osbuild/images/pull/1072#discussion_r1861786532)
---
Add a case for every entity type in the PartitionTable.features() callback.  More importantly, panic if any entity type is not covered by a case.  This ensures that when a new entity type is added, we need to consider whether it needs to be represented as a feature, added to an existing one, or ignored.
Co-authored-by: Michael Vogt <michael.vogt@gmail.com>
> disk: cover all entities in PartitionTable.features()

- pkg/distro/fedora/distro_test.go
- pkg/distro/fedora/imagetype.go
- pkg/distro/rhel/distro_test.go
- pkg/distro/rhel/images.go
- pkg/distro/rhel/imagetype.go
- pkg/distro/rhel/rhel10/distro_internal_test.go
- pkg/distro/rhel/rhel10/distro_test.go
- pkg/distro/rhel/rhel10/options.go
- pkg/distro/rhel/rhel8/distro_internal_test.go
- pkg/distro/rhel/rhel8/distro_test.go
- pkg/distro/rhel/rhel8/options.go
- pkg/distro/rhel/rhel9/distro_internal_test.go
- pkg/distro/rhel/rhel9/distro_test.go
- pkg/distro/rhel/rhel9/options.go
- test/config-map.json
Enabling the new partitioning customizations for RHEL and CentOS.
I also found some duplication in Fedora that I cleaned up.
> Add support for the new partitioning customizations to RHEL and CentOS

- pkg/distro/fedora/imagetype.go
- pkg/distro/rhel/rhel10/options.go
- pkg/distro/rhel/rhel8/options.go
- pkg/distro/rhel/rhel9/options.go
**distro/fedora: don't return early from FIPS check in checkOptions()**
When the check was first added [1] it was the last in the function and
was written to immediately return.  New checks were added after the
check, without changing the early return, which means invalid
configurations were not caught.
Append to warnings instead of returning.
[1] 665a128f049c62b14285498f753a8c5fdbaa646d
---
**distro/fedora: always return warnings from checkOptions()**
Always return the warnings list from checkOptions() so that future
modifications or reshuffling of the checks doesn't drop any warnings
collected before the return.
---
**distro/rhel: always return warnings from checkOptions()**
Always return the warnings list from checkOptions() so that future
modifications or reshuffling of the checks …
> Minor fixes and changes to warnings handling in option checkers

- pkg/osbuild/bootupd_stage.go
- pkg/osbuild/bootupd_stage_test.go
Trivial commit to allow swap in bootupd.
> osbuild: add support for `swap` in the bootupd stage

- pkg/disk/lvm.go
- pkg/disk/lvm_test.go
This commit adds support for automatic geneation of names for an lv swap devices. This saves the users of advanced blueprints some typing.
> disk: support automatic name generation for swap devices

- cmd/otk/osbuild-resolve-ostree-commit/main_test.go
- pkg/blueprint/ca_customizations.go
- pkg/blueprint/customizations.go
- test/scripts/base-host-check.sh
@avitova found some issues, I am going to address them.
To test the CA generation run this:
```
go run ./cmd/gen-manifests --arches x86_64 --distros fedora-41 --types qcow2 -config ./test/configs/all-customizations.json
```
It creates the following file in `test/data/manifests`:
```
...
{
"type": "org.osbuild.copy",
"inputs": {
"file-4c4e8c734e4ee3a117ca8f9363ba7b706d02bfc8f297c00b02ce02babddef51c": {
"type": "org.osbuild.files",
"origin": "org.osbuild.source",
"references": [
{
"id": "sha256:4c4e8c734e4ee3a117ca8f9363ba7b706d02bfc8f297c00b02ce02babddef51c"
}
]
}
},
"options": {
"paths": [
{
"from": "input://file-4c4e8c734e4ee3a117ca8f9363ba7b706d02bfc8f297c00b02ce02babddef51c/sha256:4c4e8c734e4ee3a117ca8f9363ba7b706d02bfc8f297c00b02ce02babddef51c",
"to": …
```
> blueprint: fix cacerts name for TOML

- pkg/disk/lvm.go
- pkg/disk/lvm_test.go
When creating an LV they need to be aligned up boundaries or lvcreate will fail. When a lv is create via CreateLogicalVolume() this hapens because the size is calculcated with `v.AlignUp()` but when a resize is required via `lv.EnsureSize()` this is not taken into account.
This fixes the failure in bib PR#750
> disk: align logical volumes up in EnsureSize()

- pkg/blueprint/disk_customizations.go
- pkg/blueprint/disk_customizations_test.go
- pkg/disk/partition_table_test.go
When the fs_type field value is invalid, we refer to it as the 'filesystem type'.  Add a parenthetical mention to 'fs_type' as well to make it clear which option the error refers to.
> blueprint: clarify filesystem type customization name

- cmd/otk/osbuild-gen-partition-table/main_test.go
- pkg/blueprint/disk_customizations.go
- pkg/blueprint/disk_customizations_test.go
- pkg/disk/disk.go
- pkg/disk/partition.go
- pkg/disk/partition_table.go
- pkg/disk/partition_table_test.go
- pkg/disk/partition_test.go
- pkg/distro/fedora/partition_tables.go
- pkg/distro/rhel/rhel10/partition_tables.go
- pkg/distro/rhel/rhel8/partition_tables.go
- pkg/distro/rhel/rhel9/partition_tables.go
- pkg/osbuild/sfdisk_stage.go
- pkg/osbuild/sfdisk_stage_test.go
- test/config-map.json
- test/configs/partitioning-dos-lvm.json
Users need to have control over the partition table type in certain cases. Most prominently, they need a dos-style partition table for single-board computers.
Let's add a simple customizations for it.
> Add support for selecting a partition table type

- cmd/otk/osbuild-gen-partition-table/main.go
- cmd/otk/osbuild-gen-partition-table/main_test.go
- pkg/disk/disk.go
- pkg/disk/partition.go
- pkg/disk/partition_table.go
- pkg/disk/partition_table_test.go
- pkg/disk/partition_test.go
- pkg/distro/fedora/partition_tables.go
- pkg/distro/rhel/rhel10/partition_tables.go
- pkg/distro/rhel/rhel8/partition_tables.go
- pkg/distro/rhel/rhel9/partition_tables.go
**disk,otk: use disk.DosLVMTypeID constant**
---
**disk: rename all DOS type ID consts to match GUIDs**
Rename the global constants to follow the same convention as the GPT
GUIDs and UUIDs.
---
> disk: rename all DOS type ID consts to match GUIDs

- test/config-map.json
- test/scripts/base-host-check.sh
> blueprint: fix CA cert testing

- cmd/otk/osbuild-resolve-ostree-commit/main.go
- cmd/otk/osbuild-resolve-ostree-commit/main_test.go
- pkg/ostree/test_mtls_server/http_mtls_server.go
SSIA
this allows resolution of pulp hosted repos
> otk: add mtls into resolve ostree command

- test/scripts/boot-image
- test/scripts/build-image
- test/scripts/imgtestlib.py
- test/scripts/upload-results
- Move `find_image_file()` from boot-image to `imgtestlib` so that a new script generating the image-info report can use it later.
- Define common `{read,write}_build_info()` functions in `imgtestlib` to read/write build `info.json` and use them everywhere.
/jira-epic COMPOSER-2318
JIRA: [HMS-5242](https://issues.redhat.com/browse/HMS-5242)
> Test/scripts: move shared code to `imgtestlib` (HMS-5242)

- pkg/disk/partition_table.go
Tiny drive-by commit to make `ensure{Btrfs,LVM}()` more linear to read. I.e. avoid nested if/else when returning and do error checks early.
Best viewed side-by-side as the diff makes it hard to follow.
[edit: moved to draft as I have not inspected how much testing this function has, I'm pretty confident in the change but would really like to double check the test situation as well]
[edit2: played around a bit more with the tests and it seems it's well covered so moving out of draft again]
> disk: tweak ensure{Btrfs,LVM}() to be more linear

- .github/workflows/tests.yml
- Schutzfile
- test/scripts/setup-osbuild-repo
- test/scripts/update-schutzfile-osbuild
Ensure that we always use well-known osbuild version on CI workers by:
- `update-schutzfile-osbuild` script unconditionally defining the latest osbuild commit for all distros in the `Schutzfile`.
- `setup-osbuild-repo` script failing in case the host distro does not have the osbuild dependency commit defined.
Define the osbuild dependency commit for every distro we run in GH actions or in GitLab CI. Delete repo overrides for F40, since we no longer run F40 workers in GitLab.
/jira-epic COMPOSER-2318
JIRA: [HMS-5248](https://issues.redhat.com/browse/HMS-5248)
> Changes to require pinned osbuild commit for the CI runners (HMS-5248)

- .github/workflows/test-osbuild-composer-integration.yml
The `pr_head` env variable set by the step was always empty, because there was a typo in the source variable "hase" vs. "head" / "base". I was not able to find any actual use of the `pr_head` variable, so let's delete it altogether from the action step.
> GH/test-osbuild-composer-integration: don't set env.pr_head

- pkg/manifest/anaconda_installer_iso_tree.go
Not doing this can silently mask errors.
xref https://github.com/containers/bootc/issues/931
> anaconda: Use erroronfail

- .github/workflows/tests.yml
- pkg/crypt/crypt.go
- pkg/crypt/crypt_impl_non_cgo.go
- pkg/crypt/crypt_test.go
- pkg/upload/koji/koji.go
This PR tweaks the images library to work without "cgo" so that we can cross build. Thanks to @supakeen for raising this!
With the PR we can now do:
```
$ GOARCH=arm64 go build -o ibc-aarch64 -tags "containers_image_openpgp exclude_graphdriver_btrfs exclude_graphdriver_devicemapper" ./cmd/image-builder
```
in the image-builder-cli source tree.
> crypt: provide non-cgo implementation of "crypt()" to be more cross-build friendly 

- pkg/distro/fedora/package_sets.go
Removes the `dnsmasq` package from iot package sets to bring package list in line with current iot package list here: https://pagure.io/fedora-iot/ostree/blob/main/f/fedora-iot-base.yaml
Also see the original PR that removed `dnsmasq` here: https://pagure.io/fedora-iot/ostree/c/176b0add790ece0b16b41337569b9170b0514117?branch=main
> Remove dnsmasq from iot package sets

- pkg/distro/fedora/images.go
- pkg/distro/rhel/images.go
- pkg/image/anaconda_container_installer.go
- pkg/image/anaconda_live_installer.go
- pkg/image/anaconda_ostree_installer.go
- pkg/image/anaconda_tar_installer.go
- pkg/manifest/anaconda_installer_iso_tree.go
- pkg/manifest/anaconda_installer_iso_tree_test.go
- pkg/osbuild/erofs_stage.go
- pkg/osbuild/erofs_stage_test.go
Things that are needed:
* allow zstd compression in org.osbuild.erofs - https://github.com/osbuild/osbuild/pull/1969
* Add block size support to org.osbuild.erofs - also in https://github.com/osbuild/osbuild/pull/1969
* ~~RHEL 10 kernel needs to support erofs and zstd compression~~
> Add erofs support 

- pkg/manifest/anaconda_installer.go
- pkg/manifest/anaconda_installer_iso_tree.go
- pkg/manifest/anaconda_installer_iso_tree_test.go
- pkg/manifest/anaconda_installer_test.go
- pkg/manifest/build.go
- pkg/manifest/build_test.go
- pkg/manifest/commit_server_tree.go
- pkg/manifest/coreos_installer.go
- pkg/manifest/empty.go
- pkg/manifest/manifest.go
- pkg/manifest/os.go
- pkg/manifest/os_test.go
- pkg/manifest/ostree_deployment.go
- pkg/manifest/pipeline.go
- pkg/manifest/raw_bootc.go
- pkg/manifest/raw_bootc_export_test.go
- pkg/manifest/raw_bootc_test.go
The signature of serializeStart() is a bit unwieldy and when adding librepo based sources this prompted for this proposed cleanup. The idea is to just pass a single "Inputs" struct to the serialization so that if we add field we don't need to change the signature all over the place. It also makes the calls easier to read (IMHO).
This contains only mechanical changes so the review shouldbe straightforward.
Unfortunately there will be conflicts with https://github.com/osbuild/images/pull/1095/files but after this is merged the other PR will be a lot smaller
We should merge this relatively soon as pretty much any PR will conflict with this one.
[edit: happy to discuss naming, I think `manifest.Inputs` makes sense in the context and `serializeStart(inputs)` too but open for ideas, some other …
> manifest: change the serializeStart() to take a new `Inputs` arg

- pkg/dnfjson/dnfjson.go
- pkg/dnfjson/dnfjson_test.go
- pkg/manifest/manifest.go
- pkg/rpmmd/repository.go
- pkg/rpmmd/repository_test.go
This commit adds the two new `Path` and `RepoID` fields to the rpmmd.PackageSpec so that librepo can use them as it needs to correlate a package to a repo to generate the right mirror id.
Ideally we would also make sure the inputs to manifest.Serialize() only accepts depsolved packageSets/repoConfigs via static type checking. There is a TODO for this now but it's not done in this commit as it requires some more thinking/discussion. But because of the strict requirement for matching packageSpec.RepoID and repoConfig.Id we should try to make this type safe. The repoConfig.Id is really only guranteed after the depsolve() run.
[split out from https://github.com/osbuild/images/pull/1132 with improved docs/tests]
> rpmmd,dnfjson: add `Path`, `RepoID` to PackageSpec for librepo

- pkg/osbuild/librepo_source.go
- pkg/osbuild/librepo_source_test.go
This commit adds a wrapper for the org.osbuild.librepo source
to download RPMs.
Note that this does not allow customizing the librepo options
MaxParallels, FastestMirror yet. We need to brainstorm this
a bit. The reason is that GenSources() does not currently allow
much control so our (library) users cannot customize it easily.
Split out/cleaned up version of https://github.com/osbuild/images/pull/1132
> osbuild: add org.osbuild.librepo source wrapper

- cmd/build/main.go
- cmd/gen-manifests/main.go
- cmd/osbuild-playground/playground.go
- pkg/distro/distro_test.go
- pkg/image/bootc_disk_test.go
- pkg/image/installer_image_test.go
- pkg/manifest/anaconda_installer.go
- pkg/manifest/anaconda_installer_test.go
- pkg/manifest/build.go
- pkg/manifest/commit_server_tree.go
- pkg/manifest/coreos_installer.go
- pkg/manifest/empty.go
- pkg/manifest/manifest.go
- pkg/manifest/os.go
- pkg/manifest/os_test.go
- pkg/osbuild/curl_source.go
- pkg/osbuild/inline_source.go
- pkg/osbuild/librepo_source.go
- pkg/osbuild/ostree_source.go
- pkg/osbuild/source.go
- pkg/osbuild/source_test.go
This commit enables librepo sources generation via a new
osbuild.RpmDownloader iota that is passed to to
`manifest.Serialize()` and `osbuild.GenSources()`.
We also need to pass the resolved repoConfig to `manifest.Serialize()`.
This is currently not type-safe, ideally we would look into how to do
this in a type-safe way. Serialize should also take less args
ideally.
Superseeds https://github.com/osbuild/images/pull/1132
With that we can enable `--use-librepo` in 
* https://github.com/osbuild/image-builder-cli/pull/51
* https://github.com/osbuild/bootc-image-builder/pull/786
> manifest,sources: add librepo support to Serialize/GenSources

- pkg/distro/fedora/distro.go
- pkg/distro/fedora/images.go
- pkg/distro/rhel/images.go
- pkg/distro/rhel/rhel10/ami.go
- pkg/distro/rhel/rhel10/azure.go
- pkg/distro/rhel/rhel10/distro.go
- pkg/distro/rhel/rhel10/gce.go
- pkg/distro/rhel/rhel10/ubi.go
- pkg/distro/rhel/rhel10/vmdk.go
- pkg/distro/rhel/rhel9/bare_metal.go
- pkg/image/anaconda_container_installer.go
- pkg/image/anaconda_live_installer.go
- pkg/image/anaconda_ostree_installer.go
- pkg/image/anaconda_tar_installer.go
- pkg/image/installer_image_test.go
- pkg/manifest/anaconda_installer.go
- pkg/manifest/anaconda_installer_test.go
This PR primarily
- Sets the timezone for all RHEL 10 images to `UTC`.
- Sets the locale for all RHEL 10 images to `C.UTF-8`.
On top of that, it pushes the definition of locales for installer (Anaconda ISO) image types to the image definition (in each distro).  For image installers, since we build the payload for the ISO, we ensure that the same locale is used for both the image and the ISO itself.  This means that a customized locale for an image (tar) installer will also change the locale for the ISO.
JIRA: [HMS-5342](https://issues.redhat.com/browse/HMS-5342)
> Unify locales and timezones in RHEL 10 disk images (HMS-5342)

- test/scripts/build-image
While working on replacing manifest-db with images build cache, I've run into a situation when the ability to download the image artifact after the downloading of build info metadata would be useful. Specifically when tests are run in batches, when one needs to first determine the full list of test cases and then download image artifacts only for the relevant test cases.
Due to the size of image artifacts, downloading all of them every time is not really feasible as it takes non-trivial amount of time.
The idea is to be able to download image artifact from S3 after build metadata have been already downloaded. The `info.json` already contains almost all information necessary to construct the S3 path to download, except for the runner distro.
Let's add the `runner-distro` property to …
> Test/scripts/build-info: include runner-distro in `info.json` (HMS-5350)

- .github/workflows/gitlab-helper.yml
- .github/workflows/test-osbuild-composer-integration.yml
- .github/workflows/tests.yml
- test/config-map.json
- test/configs/edge-ostree-pull-user.json
- test/scripts/install-dependencies
- test/scripts/test_validate_config_map.py
- test/scripts/validate-config-map
1. Follow-up from #1154 with the same change but for the edge-ami image type.
2. Add a new test script that validates the build configurations in the config map¹.
3. Change the `iot-ami` image type in the config map to `iot-qcow2-image`.  `iot-ami` is not a valid image type name.
¹ Note that the validation script does not catch all issues with the config map.  For
example, the following configuration is considered valid:
```json
{
"./configs/some-config.json": {
"distros": [
"rhel-10*",
],
"image-types": [
"ami",
"invalid-type-name"
]
}
}
```
because it still produces (at least) one valid configuration:
rhel-10.0, ami, any architecture
This is (somewhat) necessary because we also want the following to be
valid:
```json
{
"./configs/some-config.json": {
"distros": [
"rhel-9*",
"fedora*"
], …
```
> Validate config map and fix bad Fedora IoT test config

- test/scripts/dl-image-build-cache
- test/scripts/dl-one-image-build-cache
- test/scripts/imgtestlib.py
Add scripts for downloading image build CI cache to test osbuild behavior when rebuilding manifests in the osbuild repository (so-called manifest tests).
As I worked on using these scripts in the osbuild repo for manifest tests, I realized that there is a need to be able to split the test cases (corresponding to specific manifest) into batches to allow parallelization. For this reason, it is desirable to determine the current CI cache to download (which includes generating relevant manifests to determine their checksum), but don't download any image artifacts. The reason is that these are huge, and if traffic is not an issue, it still takes time to download files, which would not be used at all. Image artifacts are downloaded once test cases for the given batch are determined.
Instead of …
> Test/scripts: add scripts for convenient download of image build CI cache (HMS-5356)

- pkg/dnfjson/dnfjson.go
- pkg/dnfjson/dnfjson_test.go
Since the modularity PR https://github.com/osbuild/osbuild/pull/1933 landed in `osbuild` the depsolve result now contains a `modules` key with data if modules were resolved.
Add the appropriate structures to the depsolve result, without propagating them into rpmmd for now.
Also adds a quick test for the internal `depsolveResult` type deserialization to ensure it understands some JSON serialized data that contains a `modules` key.
This PR will serve as the basis for #1095 where the types will be propagated to rpmmd and the stage will be implemented; but this one is important to unblock our CI as everything now fails on the unexpected field.
---
Note that, as opposed to the nevra field on packages which was a big red herring today; this field is actually *expected* to be added. Hence we …
> depsolve: add `modules` support

- cmd/build/main.go
- cmd/gen-manifests/main.go
- pkg/manifestgen/manifestgen.go
- pkg/manifestgen/manifestgen_test.go
- pkg/osbuild/manifesttest/manifesttest.go
- pkg/osbuild/manifesttest/manifesttest_test.go
This commit adds a new generic `manifestgen` package that can be
used to generate osbuild manifests. It works on a higher level
then the low-level `manifest` package from `images` and provides
plugable resolvers and a streamlined API.
The rational is that we currently have duplicated implementations
of e.g. `depsolve`, `containerResolver`, `ostreeCommitResolver`.
This helper provides default implementations for the common case
but also provide the ability to override the defaults.
This is a cleaned up version of https://github.com/osbuild/image-builder-cli/tree/main/internal/manifestgen
It is used in image-builder-cli like this: https://github.com/osbuild/image-builder-cli/blob/main/cmd/image-builder/manifest.go#L39
I did not include the full port of the "cmd/build" in this PR but I did …
> pkg: add new `manifestgen` package

- pkg/osbuild/containers_input.go
- pkg/osbuild/containers_storage_source.go
- pkg/osbuild/skopeo_index_source.go
- pkg/osbuild/skopeo_source.go
- pkg/osbuild/skopeo_stage.go
- pkg/osbuild/source.go
This is a followup for the suggestion in PR#1142 to not use strings for defining sources but constants. This helps avoiding typos.
Note that this does not change the tests to ensure that we keep the API promises here. I.e. an accidental change of e.g. the `SourceNameSkopeoIndex` const should trigger a test failure.
> osbuild: add consts for more "sources" in sources.go

- pkg/imagefilter/formatter.go
- pkg/imagefilter/formatter_test.go
This should implement the initial idea of a
copy'n'paste ready list of possibilities.
> pkg/imagefilter/formatter: add `shell` output

- docs/image-types/rhel8/google-gce.md
- pkg/imagefilter/formatter.go
- pkg/imagefilter/formatter_test.go
Add `short` output
which looks like
```
rhel-9.5:
ami: [ aarch64, x86_64 ]
azure-rhui: [ aarch64, x86_64 ]
azure-sap-rhui: [ x86_64 ]
ec2: [ aarch64, x86_64 ]
…
rhel-9.6:
ami: [ aarch64, x86_64 ]
azure-rhui: [ aarch64, x86_64 ]
azure-sap-rhui: [ x86_64 ]
ec2: [ aarch64, x86_64 ]
ec2-ha: [ x86_64 ]
ec2-sap: [ x86_64 ]
```
(this is based on #1166 )
> Add short output

- .github/workflows/update-osbuild.yml
- .gitignore
- test/scripts/update-schutzfile-osbuild
Extends the "update dependency PR" commit message to also contain a link to the exact changes for easier review.
e.g. the Message of https://github.com/osbuild/images/pull/1169 would be
```
Updating osbuild dependency commit IDs to current `main`
Changes: https://github.com/osbuild/osbuild/compare/55d53f58fdbe6f328581f12c4548efb80aa5ca19...e4333f87ba14f85ba3d9aa5b070190d82d06a297
```
similar change could be done with `./test/scripts/update-schutzfile-bib` in a separate PR
> .github/workflows/update-osbuild: extend PR commit message

- pkg/imagefilter/formatter.go
- pkg/imagefilter/formatter_test.go
This commit changes the "short" output format so that it is marked as "unstable". There are some open questions about this format and how it relates to e.g.
https://github.com/osbuild/osbuild-composer/pull/4336 which adds very similar API is a slightly different format.
So to prevent users from relying on the API before that is resolved we need to at least make them aware that this may still change.
> imagefilter: make `short` output format as unstable

- pkg/distro/rhel/rhel10/bare_metal.go
This commit adds the @hardware-support group to the anaconda installer packages. This was originally requested for bootc-image-builder in https://github.com/osbuild/bootc-image-builder/issues/807 and implemented in
https://github.com/osbuild/bootc-image-builder/pull/808
But it seems a good idea to be consistent and add it here as well.
Thanks to Tomáš Hozza.
> rhel10: add `@hardware-support` to installed anaconda packages

- pkg/imagefilter/formatter.go
- pkg/imagefilter/formatter_test.go
[build on top of https://github.com/osbuild/images/pull/1173]
This commit uses the `distrosort` package to sort the distro names
by their name/version. This means that the output of centos is sorted
by low to high version like this:
```console
$ ./image-builder list-images --output=short --filter distro:centos*
centos-9:
ami: [ aarch64, x86_64 ]
...
centos-10:
ami: [ aarch64, x86_64 ]
...
```
with the regular "string" search this was:
```console
$ ./image-builder list-images --output=short --filter distro:centos*
centos-10:
ami: [ aarch64, x86_64 ]
...
centos-9:
ami: [ aarch64, x86_64 ]
...
```
(this is also quite visible with rhel).
> imagefilter: use `distrosort` to sort the distro names

- .github/workflows/gitlab-helper.yml
- .github/workflows/tests.yml
- go.mod
- tools/prepare-source.sh
- Update the go.mod to use v1.22
- Update all test workflows to install v1.22
- Edit and run tools/prepare-source.sh
> go.mod: update to go v1.22

- pkg/distro/distro.go
This is a slightly silly commit. Instead of using `time.UnixNano()` its much more sensible to use `rand.Int63` which is automatically seeded since go1.20 [0] and also gives us a wider range of possible seeds than UnixNano (which will always be of a preditable length).
None of this really matters in practise as we just need something "good enough" but using rand.Int63() is the correct thing to do.
[0] https://tip.golang.org/doc/go1.20#mathrandpkgmathrand
> distro: use `rand.Int63` intead of `time.UnixNano()`

- cmd/build/main.go
- pkg/manifestgen/manifestgen.go
- pkg/manifestgen/manifestgen_test.go
Note that I could also create a PR for the first two commits that extend
manifestgen and then do the build.go changes separately (or not
at all if that is preferred). The first two commits will help ibcli as well,
once those are in we can add `--ignore-warnings` (or something)
like this to "image-builder-cli" and also a "--override-repository"
option that works differently from "datadir" (just like we do here).
There is a question in the PR about how to best deal with repos
on the API level (which will affect how this will be done in ibcli).
Individual commits below:
---
This commit moves the `cmd/build` command to the new manifestgen
package to the full extend. Some of the output will slightly
change now but this commit tries to keep the errors/messages
as similar as possible.
--- …
> cmd/build: use the new manifestgen package

- pkg/dnfjson/dnfjson.go
- pkg/dnfjson/dnfjson_test.go
This commit tweaks the dnfjson.Solver to also have a `Stderr` attribute. This is a minimal change to prevent `image-builder-cli` from showing:
```console
image-builder build qcow2 --distro centos-9 --progress=verbose
Manifest generation step
Building manifest for qcow2-centos-9
No match for group package "iwl5150-firmware"
No match for group package "iwl6050-firmware"
No match for group package "firewalld"
No match for group package "iwl7260-firmware"
No match for group package "dracut-config-rescue"
No match for group package "iwl105-firmware"
No match for group package "iwl2000-firmware"
No match for group package "iwl100-firmware"
No match for group package "iwl6000g2a-firmware"
No match for group package "iwl1000-firmware"
No match for group package "iwl3160-firmware"
No match for …
```
> dnfjson: support redirecting dnfjsons `stderr`

- pkg/cloud/awscloud/awscloud.go
- pkg/cloud/awscloud/export_test.go
- pkg/cloud/awscloud/uploader.go
- pkg/cloud/awscloud/uploader_test.go
- pkg/cloud/uploader.go
This commit adds a new `cloud.Uploader` interface that combines the upload and register into a single operation. The rational is that with that we avoid leaking resource if e.g. the upload works but the registration fails
(c.f. https://github.com/osbuild/images/pull/1145). This would replace most of the existing bib uplodaer code so that it is shareable.
This would looks like this:
* https://github.com/osbuild/bootc-image-builder/pull/815
* https://github.com/osbuild/image-builder-cli/compare/main...mvo5:add-upload-cmd?expand=1
After that I would like to look into the following:
- I would like remake the cloud interface for images around something like this
- ~can we remove (most?) of the existing awscloud in images. because osbuild-compser impleents it all too but has now moved to aws-v2 …
> cloud: add new Uploader interface and implement for AWS

- pkg/manifest/ostree_deployment.go
- pkg/manifest/subscription.go
- pkg/manifest/subscription_test.go
- pkg/osbuild/systemd_unit_create_stage.go
- pkg/osbuild/systemd_unit_create_stage_test.go
This PR updates the org.osbuild.systemd.unit.create stage to match the options in osbuild, especially the new sections for mount and socket unit types.
Tests added to cover all validation failures.
> osbuild: update org.osbuild.systemd.unit.create stage

- .github/workflows/tests.yml
- pkg/container/blocking_resolver_test.go
- pkg/container/export_test.go
- pkg/container/resolver.go
- pkg/manifestgen/manifestgen.go
This is a follow-up to #1153 and part of a bigger refactor meant to distribute some of the resolver conveniences from the new `manifestgen` package to the packages that implement the resolvers themselves.
This PR converts the `container.Resolver` from a concrete type to an interface with two implementations:
- `asyncResolver`: the old resolver that resolves container refs asynchronously and blocks on `Finish()`.
- `blockingResolver`: a new resolver that resolves container refs synchronously, blocking on each call to `Add()`.
The blockingResolver implements the Resolver interface but resolves containers synchronously, blocking execution on the resolve process inside the Add() method.  **This will become the only implementation in the near future.**  For now we will support both to make the …
> Add a blocking container resolver

- pkg/distro/rhel/rhel9/edge.go
From Colin:
If the Edge-9.6 setup isn't ready for bootupd then at the current time the package needs to be excluded.
we do this already in fedora indeed...
> distro: rhel9: edge: exclude bootupd

- cmd/build/main.go
- pkg/reporegistry/error.go
- pkg/reporegistry/reporegistry.go
- pkg/reporegistry/repository.go
- pkg/reporegistry/repository_test.go
- test/data/repositories/testrepos.go
This PR changes the API for reporegistry in two incompatible
ways. The important change is that we want to drop the
prepending of `repositories` when loading from confPaths.
Doing this on its own has the disadvantage of breaking
the API without breaking the builds. So this includes a
small tweak to allow adding repos via fs.FS directly
which will mean the code in ibcli will become simpler:
```go
diff --git a/cmd/image-builder/repos.go b/cmd/image-builder/repos.go
index bc238dc..5d16a95 100644
--- a/cmd/image-builder/repos.go
+++ b/cmd/image-builder/repos.go
@@ -2,8 +2,6 @@ package main
import (
"io/fs"
-       "os"
-       "path/filepath"
"github.com/osbuild/images/data/repositories"
"github.com/osbuild/images/pkg/reporegistry"
@@ -27,17 +25,6 @@ var newRepoRegistry = func(dataDir string) …
```
> reporegistry: do not prepend `repositories` in confPaths

- pkg/osbuild/monitor.go
- pkg/osbuild/monitor_test.go
This commit incrases the buffer os the osbuild message scanner to deal with very big messages. The default size of 64kb is too small for the `dracut` stage which will generate 5447 messages that /dev/log is not available and they come so rapidly that osbuild will pick them up in one big chunk.
This is a short term fix, the deeper fix should be to tweak the osbuild monitor to have a smaller buffer size when sending stdout/stderr output from stages to the monitor. This will fix a crash in the bootc-image-builder anaconda builds that is currently breaking the integration test in konflux.
See also https://github.com/osbuild/osbuild/issues/1976
> monitor: increase buffer to deal with very big messages

- pkg/distro/fedora/package_sets.go
The `basesystem` package is being obsoleted by `filesystem` in Rawhide (F43). Change the definition of the `iot-commit` to conditionally include the correct package based on the Fedora version.
> distro: conditionally include basesystem/filesystem

- pkg/imagefilter/filter.go
- pkg/imagefilter/filter_test.go
imagefilter: add `SupportedFilter()` that returns known
prefixes
This commit adds a new `SupportedFilter()` function that returns
the available filter prefixes.
See https://github.com/osbuild/image-builder-cli/issues/104
---
imagefilter: show supported filters when giving one
This commit tweaks the error message for unsupported filter prefixes
to include what is actually supported.
See https://github.com/osbuild/image-builder-cli/issues/104
> imagefilter: improve supported filters discoverability

- go.mod
- pkg/imagefilter/export_test.go
- pkg/imagefilter/formatter.go
- pkg/imagefilter/formatter_test.go
Convenience function for concise help output
(This is based on #1166 and #1167)
The last commit could be split off, it's not directly related to the implementation of `SupportedOutputFormats` just extends the tests
> imagefilter: add SupportedOutputFormats

- go.mod
- go.sum
`github.com/envoyproxy/go-control-plane/envoy@v1.32.3`
has a changed checksum, so we'll just bump to `v1.32.4` to avoid problems.
> go.mod: fix envoyproxy/go-control-plane/envoy version

- pkg/reporegistry/reporegistry.go
- pkg/reporegistry/repository.go
- pkg/reporegistry/repository_test.go
This commit re-export the `LoadAllRepositories` helper. It was unexported (by me) in https://github.com/osbuild/images/pull/1179 but that was a bit premature as it is still required for advanced use-cases like https://github.com/osbuild/image-builder-cli/pull/113
Sorry for this back-and-forth here.
> reporegistry: re-export `LoadAllRepositories`

- pkg/cloud/awscloud/uploader.go
- pkg/cloud/awscloud/uploader_internal_test.go
- pkg/cloud/awscloud/uploader_test.go
Allow setting the boot mode to be used for the uploaded image, instead of defaulting to uefi-preferred. The boot mode is not a required field, so if not explicitly set in the UploaderOptions, don't set it at all.
Extend test coverage for the newly added code.
> cloud/awscloud: extend UploaderOptions with boot mode

- .github/workflows/auto-merge-dependabot.yml
- .github/workflows/create-tag.yml
- .github/workflows/gitlab-helper.yml
- .github/workflows/pr_best_practices.yml
- .github/workflows/release.yml
- .github/workflows/stale-cleanup.yml
- .github/workflows/test-osbuild-composer-integration.yml
- .github/workflows/tests.yml
- .github/workflows/trigger-gitlab.yml
- .github/workflows/update-bootc-image-builder.yml
- .github/workflows/update-osbuild.yml
This replaces ubuntu-latest with ubuntu-24.04 to avoid unexpected changes.
> Pin CI workflows to ubuntu 24.04

- .golangci.yml
The action now runs config validation automatically [1], which fails on our config because 'exclude-dirs' is not a valid top-level key.  Also, we don't have a vendor directory any more so let's just drop it.
golangci-lint --config ./.golangci.yml config verify
jsonschema: "" does not validate with "/additionalProperties": additionalProperties 'exclude-dirs' not allowed
Failed executing command with error: the configuration contains invalid elements
https://github.com/golangci/golangci-lint-action/releases/tag/v6.5.0
> golangci: remove exclude-dirs

- .github/workflows/test-osbuild-composer-integration.yml
Running ./tools/prepare-source.sh in osbuild-composer now requires jq for the version check.
https://github.com/osbuild/osbuild-composer/pull/4600
> github: install jq for the osbuild-composer integration tests

- .gitlab-ci.yml
- test/scripts/generate-gitlab-ci
The job_names are used in metrics (cloudability) to get an overview of run times per "curated_job_name". This "curated_job_name" is deduced by splitting by ":", which exists when using matrix-jobs. e.g. https://github.com/osbuild/osbuild-composer/blob/a237447ca06c3f302e41c710a64e86577cfd2537/.gitlab-ci.yml#L111
As we generate the jobs with the script `generate-gitlab-ci`, this implementation should work to mimic the behavior and have the same names as if they were matrix-jobs.
I'll set to draft to collect enough feedback if this is a good idea…
> test/scripts/generate-gitlab-ci: mimic matrix syntax of jobnames

- cmd/otk/osbuild-gen-partition-table/main_test.go
- cmd/otk/osbuild-make-ostree-source/main_test.go
- pkg/blueprint/blueprint_test.go
Some of our static json strings used in testing had mixed indentation (tabs and spaces).  This commit unifies them all to be indented with 2 spaces.
This does not unify *all* cases of static json strings to be indented with 2 spaces, only the ones found to have mixed indentation.
> Fix static json strings with mixed-indent

- pkg/osbuild/osbuild-exec.go
Adding --checkpoints to the osbuild call has no effect right now unless a previous run of osbuild set the max size already. Since we support passing checkpoint args to the osbuild call, let's also set the cache size to a baseline default value to have those checkpoints actually checkpoint.
> osbuild: set the cache-max-size to 20 G when checkpoints are defined

- pkg/distro/fedora/distro.go
- pkg/distro/fedora/images.go
- pkg/distro/fedora/imagetype.go
- pkg/distro/rhel/images.go
- pkg/distro/rhel/rhel10/bare_metal.go
- pkg/distro/rhel/rhel8/bare_metal.go
- pkg/distro/rhel/rhel8/edge.go
- pkg/distro/rhel/rhel9/bare_metal.go
- pkg/distro/rhel/rhel9/edge.go
- pkg/image/anaconda_container_installer.go
- pkg/image/anaconda_live_installer.go
- pkg/image/anaconda_ostree_installer.go
- pkg/image/anaconda_tar_installer.go
- pkg/image/installer_image_test.go
- pkg/image/ostree_simplified_installer.go
- pkg/image/ostree_simplified_installer_test.go
- pkg/manifest/anaconda_installer.go
- pkg/manifest/anaconda_installer_test.go
- pkg/manifest/coreos_installer.go
- pkg/manifest/coreos_installer_test.go
- test/scripts/generate-ostree-build-config
In RHEL 10 and Fedora 42, the ifcfg module was replaced by net-lib.
This PR removes ifcfg from common anaconda dracut stage modules and adds either ifcfg or net-lib to each installer based on distro version.
> Replace ifcfg with net-lib for EL10 and F42 installers

- pkg/distro/packagesets/fedora/package_sets.yaml
After some discussion [1] Fedora Minimal would like to disable the generation of rescue kernels. This is because historically they weren't included in images (before switching to `image-builder`) and also because the current `/etc/machine-id` implementation of `image-builder` leads to duplicate rescue kernels being generated [2].
---
This also slightly improves build time (by about 10-20 seconds on my system).
[1]: https://github.com/fedora-minimal/distribution-minimal/issues/10
[2]: https://github.com/osbuild/images/issues/1244
> fedora: remove rescue kernels from minimal

- pkg/distro/fedora/images.go
- pkg/distro/fedora/version.go
- pkg/image/disk.go
- pkg/manifest/os.go
- pkg/manifest/os_test.go
- pkg/osbuild/machine_id_stage.go
- pkg/osbuild/machine_id_stage_test.go
Fedora resets the `/etc/machine-id` file for [any disk image](https://pagure.io/fedora-kiwi-descriptions/blob/960270bb861a0e54bc837f7feeb9c3a9b9a18661/f/config.sh#_117); let's do the same here.
Enables `ConditionFirstBoot` which is/was also part of a [request](https://github.com/fedora-minimal/distribution-minimal/issues/3) for Fedora Minimal to support `systemd-firstboot`.
> fedora: reset machine-id for disk images

- pkg/manifest/os.go
- pkg/osbuild/machine_id_stage.go
- pkg/osbuild/machine_id_stage_test.go
Changes the strings used in the `machine-id` stage to be constants with their own type instead. This was requested as a followup.
---
Followup for #1251.
> osbuild: constants for machine-id

- pkg/experimentalflags/experimental.go
This commit improves the docs strings and module documentation for the `experimentalflags` package.
Thanks to Achilleas.
This is a followup for
https://github.com/osbuild/images/pull/1248#pullrequestreview-2637037924 where excellent points are raised.
> experimentalflags: improve doc strings and module docs

- pkg/distro/fedora/distro.go
- pkg/distro/fedora/distro_test.go
xz is super-slow on riscv64, so let's enable the zstd variant on riscv64.
> fedora: enable minimal-raw-zst for riscv64

- cmd/gen-manifests/main.go
Since the packages were extracted into yaml files in #1205, the package list order has become unstable, in particular when packages are added conditionally.  I'm not entirely sure where the instability comes from, but generating manifests with the mock depsolver creates lists with different order for the OS pipeline for the image types that conditionally add "dnsmasq".
Sorting the package lists ensures that manifests don't change from this instability.  It also makes the manifests reproducible when the package lists are reordered internally, which we would prefer to have, since the package order pre-depsolve shouldn't affect the final manifest.
> cmd/gen-manifests: sort package sets in mock depsolver

- pkg/distro/packagesets/fedora/package_sets.yaml
Drops `firewalld` for Fedora Minimal in rawhide for now, see issue [1].
[1]: https://github.com/fedora-minimal/distribution-minimal/issues/1
> fedora: drop `firewalld` for minimal

- pkg/imagefilter/formatter.go
- pkg/imagefilter/formatter_test.go
This is now a short text-only output focused only on a condensed and readable output.
```
centos-10
ami: aarch64, x86_64
gce: x86_64
image-installer: aarch64, x86_64
oci: x86_64
ova: x86_64
qcow2: aarch64, ppc64le, s390x, x86_64
tar: aarch64, ppc64le, s390x, x86_64
vhd: aarch64, x86_64
vmdk: x86_64
wsl: aarch64, x86_64
fedora-40
ami: aarch64, x86_64
container: aarch64, ppc64le, riscv64, s390x, x86_64
image-installer: aarch64, x86_64
iot-bootable-container: aarch64, ppc64le, s390x, x86_64
iot-commit: aarch64, x86_64
iot-container: aarch64, x86_64
…
```
There is an additional suggestion to implement a proper `yaml` output: #1268
> imagefilter: adjust `short` output format

- pkg/manifest/raw_bootc.go
- pkg/manifest/raw_bootc_test.go
Without this the files/dir stages will not have access to the generated container filesystem.
This was found by the integration test in
https://github.com/osbuild/bootc-image-builder/pull/841
P.S. this is now integration tested with https://github.com/osbuild/bootc-image-builder/pull/841 that pulls this in temporarily - the bib integration test now passes locally
[edit: the integration test in bib in https://github.com/osbuild/bootc-image-builder/pull/841 has now passed with this change in CI as well]
> manifest: add devices/mounts to the files/dir stages in bootc

- pkg/distro/fedora/distro.go
- pkg/distro/fedora/images.go
- pkg/distro/fedora/version.go
- pkg/distro/image_config.go
- pkg/distro/rhel/images.go
- pkg/distro/rhel/rhel10/distro.go
- pkg/distro/rhel/rhel7/distro.go
- pkg/distro/rhel/rhel8/distro.go
- pkg/distro/rhel/rhel9/distro.go
- pkg/image/disk.go
- pkg/manifest/os.go
Weak dependency resolution is hardcoded per imagetype. This commit changes it so weak dependency resolution can be turned off per image.
We guard on the Fedora version to ensure we don't accidentally change older images.
This commit also disables weak dependency resolution for Fedora Minimal which I have mentioned [here](https://github.com/fedora-minimal/distribution-minimal/issues/13).
> fedora: allow disabling weak dependencies

- pkg/manifest/build.go
- pkg/manifest/build_test.go
This commit allows to use a container to bootstrap the buildroot via the experimtnal "bootstrap" flag:
```console
$ IMAGE_BUILDER_EXPERIMENTAL=bootstrap=ghcr.io/mvo5/fedora-buildroot:41 \
image-builder manifest --arch=riscv64 minimal-raw --distro=fedora-41
```
and it will use the given container to bootstap the buildroot.
This will allow to do cross-arch building for riscv. The generated manifest can be build with osbuild (as long as qemu-user is installed) and will generate a minimal-raw for riscv64.
Cross-building is useful because qemu-user is a lot faster (and easier to setup) than full riscv system emulation. A minimal raw build on a really fast AWS machine takes about 100 minutes. A full minimal-raw build on my (moderate) PC takes about 20min - which is fast enough so that we can …
> manifest: use experimentalflags.String("bootstrap")

- pkg/distro/fedora/distro.go
In [1] I removed the package for `firewalld` conditionally. However, the service enabling wasn't made conditional leading to build failures as the service file does not exist.
[1]: https://github.com/osbuild/images/pull/1269
> fedora: disable firewalld for minimal >= 43

- internal/testdisk/partition.go
- pkg/disk/disk_test.go
- pkg/disk/partition_table_test.go
- pkg/osbuild/fstab_stage_test.go
Move the static TestPartitionTables into a function.  Having them in a mutable, package-global, public map makes any modification in one test affect subsequent ones.
> testdisk: move TestPartitionTables to a function

- pkg/distro/packagesets/export_test.go
- pkg/distro/packagesets/loader.go
- pkg/distro/packagesets/loader_test.go
This commit allows packagesets to be conditional on the distribution name. This is useful when we define packagesets for RHEL/Centos where we only want to pull in certain packages like "subscription-manager" when building images for RHEL.
Cleaned up split out of https://github.com/osbuild/images/pull/1283/commits
> packagesets: add distro_name condition

- pkg/distro/fedora/distro.go
- pkg/distro/fedora/images.go
- pkg/distro/image_config.go
- pkg/image/disk.go
- pkg/manifest/os.go
- pkg/manifest/os_test.go
- pkg/osbuild/machine_id_stage.go
This moves the machine id handling from specific to Fedora to the image config.
---
Had a chat with @achilleas-k and @thozza today who pointed out that they'd prefer this to live in the image config. Is this the right approach?
>  many: move machine id first boot to image config

- pkg/manifest/manifest.go
AFAICT this is no longer used and even if it is used we have a `arch` package that should be used instead. This one also lacks `riscv64`.
> manifest: remove unused `manifest.Arch`

- pkg/distro/fedora/distro.go
- pkg/distro/fedora/package_sets.go
- pkg/distro/packagesets/loader.go
- pkg/distro/packagesets/loader_test.go
The current `packagesets.Loader()` takes a single imagetype argument to determine what packagesets to load from YAML.
This generally works great but its a challenge for image types like the anaconda installer where we need a different package set for the iso and the os. In fedora we workaround this by re-using the minimal-raw package set for the anaconda installers "os" package set. However in Centos/RHEL this is less straightforward so having the ability to "override" the pkgset name is required.
Another trivial split out from https://github.com/osbuild/images/pull/1283
> distro: tweak the packagesets.Loader() interface

- internal/workload/custom.go
- internal/workload/workload.go
- pkg/blueprint/blueprint.go
- pkg/blueprint/blueprint_test.go
- pkg/distro/fedora/imagetype.go
- pkg/distro/rhel/imagetype.go
- pkg/dnfjson/dnfjson.go
- pkg/manifest/os.go
- pkg/manifest/os_test.go
- pkg/osbuild/dnf_module_config_stage.go
- pkg/rpmmd/repository.go
- test/config-map.json
- test/configs/modularity-enabled-modules.json
- test/configs/modularity-in-packages.json
- test/scripts/base-host-check.sh
Adds modularity support to `images`. Needs tests.
JIRA: [HMS-5533](https://issues.redhat.com/browse/HMS-5533)
> modularity support (HMS-5533)

- pkg/distro/fedora/distro.go
- pkg/distro/fedora/images.go
- pkg/distro/image_config.go
- pkg/manifest/os.go
- pkg/manifest/os_test.go
In preparation for first-boot support [1] there are some changes that can already be PR'ed to reduce the size of that PR.
This PR makes the injection of stages conditional so no files are created when the image configs are explicitly set to none.
[1]: https://github.com/osbuild/images/pull/1264
> os: conditional stages

- tools/gen-manifests-diff
gen-manifests-diff is a helper to diff the generated manifests against what the current "main" of the images library would do.
Alternatively a revision can be given as the first argument and with that the diff is calculated against that. All images types and architectures are used by default. It is still very fast (typically 3s).
Example output:
```diff
calculating diff against d285ec65bac83fad1b36e88b50cecd5f5a5612f9
found differences between /tmp/tmpbjhime7p/new and reference manifests:
diff -uNr /tmp/tmpbjhime7p/ref/centos_9-aarch64-edge_ami-edge_ostree_pull_user.json /tmp/tmpbjhime7p/new/centos_9-aarch64-edge_ami-edge_ostree_pull_user.json
--- /tmp/tmpbjhime7p/ref/centos_9-aarch64-edge_ami-edge_ostree_pull_user.json   2025-03-10 20:55:20.736477268 +0100
+++ …
```
> tools: add new "gen-manifests-diff" tool

- cmd/gen-manifests/main.go
This is a better version of https://github.com/osbuild/images/pull/1312 that moves the de-duplication of packages into the package depsolver of gen-manifests. This is similar to how osbuild-depsolve-dnf works that also will present a de-duplicated result.
Thanks to thozza for the suggestion to do it this way.
> gen-manifests: de-duplicate packages on the depsolve level

- pkg/distro/fedora/images.go
- pkg/distro/rhel/images.go
- pkg/image/anaconda_container_installer.go
- pkg/image/anaconda_live_installer.go
- pkg/image/anaconda_ostree_installer.go
- pkg/image/anaconda_tar_installer.go
- pkg/image/ostree_simplified_installer.go
- pkg/manifest/anaconda_installer_iso_tree.go
- pkg/manifest/anaconda_installer_iso_tree_test.go
- pkg/manifest/iso.go
- pkg/manifest/iso_test.go
- pkg/osbuild/grub2_inst_stage.go
- pkg/osbuild/grub2_inst_stage_test.go
- pkg/osbuild/grub2_iso_legacy_stage.go
- pkg/osbuild/grub2_iso_legacy_stage_test.go
- pkg/osbuild/xorrisofs_stage.go
This adds support for using grub2 instead of syslinux (which is no longer updated) when booting an iso on BIOS systems. This matches how Lorax creates the boot.iso and live media images. This applies to BIOS bootin on the x86 architecture for all of the anaconda live install images created by osbuild-composer. It does not change how the ostree simplified image boots (it still uses syslinux) and it does not change how the coreos iso boots since it uses it's own self-contained stage.
> Use grub2 for BIOS iso booting

- tools/gen-manifests-diff
As suggested by thozza this adds a note about the limits of `gen-manifests-diff`.
Thanks to thozza.
> tools: add note/warning about limits of gen-manifests-diff

- README.md
- pkg/distro/packagesets/loader.go
- pkg/distro/packagesets/loader_test.go
This commit adds a new `IMAGE_BUILDER_EXPERIMENTAL=yamldir=...`
experimental flag to force setting the datadir for the yaml
directory to override e.g. packagesets.
Ideally we would pass this all the way down the stack via a
search path but this will require a bunch of more refactoring.
So to give people the ability to tweak packagesets today, start
here.
Thanks to Ondrej for the suggestion, see also https://github.com/osbuild/images/pull/1283 where this will become immediately useful when the centos folks start hacking on our package lists.
> packagesets: introduce  `IMAGE_BUILDER_EXPERIMENTAL=yamldir=...`

- pkg/distro/packagesets/fedora/package_sets.yaml
- pkg/distro/packagesets/loader.go
- pkg/distro/packagesets/loader_test.go
[this is my personal winner in the race for best-yaml-for-shareing-pkgsets, based on a new idea of @ondrejbudai (thanks!), see also https://github.com/osbuild/images/pull/1294 and https://github.com/osbuild/images/pull/1296 and https://github.com/osbuild/images/pull/1295]
This commit adds a basic imagetype yaml to support merging of package sets  This is a useful feature so that we can e.g. avoid duplicating the `cloud_base` or `anaconda` package sets.
It works by adding new toplevels "image_types" in the package_sets.yaml and then using anchors/refs to refer to them in the image_type yaml. To allow sharing yaml that is not part of an image_type it also introduces a top-level `.common` that can have `any` yaml in it.
It allows us to write:
```yaml
.common:
base: &base_pkgset
include: …
```
> packagesets: add basic imagetype yaml to merge pkgSets

- pkg/blueprint/disk_customizations.go
- pkg/blueprint/disk_customizations_test.go
- pkg/disk/partition_table.go
- pkg/disk/partition_table_test.go
Introduce the ability to specify custom partition types/GUIDs for both DOS and GPT partition types.
For DOS partitions, the field is technically called type, but this is already a taken field, so I went with GUID from the GPT vocabulary for the new field name.
> Add support for custom partition types/GUIDs in blueprints

- docs/developer/cmds.md
Tiny addition to the doc to document the basic usage of `gen-manifests-diff`.
> docs: document `gen-manifests-diff` workflow

- pkg/distro/fedora/distro.go
- pkg/distro/packagesets/fedora/package_sets.yaml
- pkg/distro/packagesets/rhel-10/package_sets.yaml
- pkg/distro/rhel/rhel10/ubi.go
- pkg/distro/rhel/rhel8/ubi.go
- pkg/distro/rhel/rhel9/ubi.go
- pkg/osbuild/cloud_init_stage.go
- pkg/osbuild/cloud_init_stage_test.go
This mirrors the Ubuntu images in the MS store. The WSL datasource looks for userdata on the Windows host.
---
also see https://cloudinit.readthedocs.io/en/latest/reference/datasources/wsl.html
> Add cloud init options to WSL images

- pkg/distro/packagesets/rhel-8/package_sets.yaml
- pkg/distro/rhel/rhel8/ami.go
- pkg/distro/rhel/rhel8/azure.go
- pkg/distro/rhel/rhel8/bare_metal.go
- pkg/distro/rhel/rhel8/edge.go
- pkg/distro/rhel/rhel8/gce.go
- pkg/distro/rhel/rhel8/package_sets.go
- pkg/distro/rhel/rhel8/qcow2.go
- pkg/distro/rhel/rhel8/sap.go
- pkg/distro/rhel/rhel8/ubi.go
- pkg/distro/rhel/rhel8/vmdk.go
Move the rhel8 packages into yaml. Similar to e.g. PR#1300. The existing structure in code was tried to be preserved.
Tested via:
```console
$ ./tools/gen-manifests-diff
no diff found to main
```
Build on top of https://github.com/osbuild/images/pull/1300
> rhel8: extract package sets into a single YAML file

- .github/workflows/tests.yml
- .pylintrc
- LICENSE
- README.md
- action.yml
- check-spec-deps.py
- requirements.txt
Add a composite action, which can be used by projects that depend on `osbuild/images` and are packaged as RPM, to check that the dependencies in their SPEC file specify the minimum versions as required by `osbuild/images`.
For now, only `osbuild` dependency is checked.
The goal is to use this action in `osbuild-composer` and `image-builder-cli` repositories to check the SPEC files.
> Add check-spec-deps-action action

- pkg/distro/packagesets/rhel-7/package_sets.yaml
- pkg/distro/rhel/rhel7/ami.go
- pkg/distro/rhel/rhel7/azure.go
- pkg/distro/rhel/rhel7/package_sets.go
- pkg/distro/rhel/rhel7/qcow2.go
rhel7: extract package sets into a single YAML file
Move hte rhel7 packages into yaml.
This was validate by running `./tools/gen-manifest-diff`.
> rhel7: extract package sets into a single YAML file

- pkg/distro/packagesets/rhel-9/package_sets.yaml
- pkg/distro/rhel/imagetype.go
- pkg/distro/rhel/rhel10/bare_metal.go
- pkg/distro/rhel/rhel10/package_sets.go
- pkg/distro/rhel/rhel7/package_sets.go
- pkg/distro/rhel/rhel8/bare_metal.go
- pkg/distro/rhel/rhel8/edge.go
- pkg/distro/rhel/rhel8/package_sets.go
- pkg/distro/rhel/rhel9/bare_metal.go
- pkg/distro/rhel/rhel9/edge.go
- pkg/distro/rhel/rhel9/package_sets.go
Some small tweak now that the bulk of the package set yaml is merged (thanks for the reviews!)
----
rhel: add error return in PackageSetFunc
This is a small cleanup/tweak to return an error if the rhel
PackageSetFunc fails. This avoid us having to panic and we
can just bubble the error up.
---
rhel9: fix two leftover hardcoded packagesets
This commit fixes two leftover package sets that were hardcoded
and are now defined in YAML. Sorry for overlooking them in my
previous commit.
> distro: tweaks to the pacakgeset loader

- pkg/distro/fedora/partition_tables.go
Adds `ro` to FSTabOptions for Fedora IoT raw disk images.
Fixes https://github.com/fedora-iot/iot-distro/issues/81
> Add ro to FSTabOptions for IoT raw disk

- .github/workflows/tests.yml
Do not run our unit tests with `-v` as the signal to noise ratio on failure is really bad. In my case [0] it produced 22607(!) lines and the failure is in line 192.
If there is a deeper reason to run with with `-v` please let me know and I will change this to add a comment why we need it :)
[0] https://github.com/osbuild/images/actions/runs/14057755420/job/39360970265?pr=1355
> workflow: do not run unit test with -v

- docs/developer/cmds.md
Add some details about the kinds of changes and behaviours that are not caught by gen-manifests-diff.
> docs/developer: details for changes not caught by gen-manifests-diff

- cmd/otk/osbuild-gen-partition-table/main_test.go
- pkg/disk/disk.go
- pkg/disk/filesystem.go
- pkg/disk/partition.go
- pkg/disk/partition_table.go
- pkg/disk/partition_table_test.go
- pkg/disk/partition_table_yaml_test.go
- pkg/disk/unmarshal.go
Split out of https://github.com/osbuild/images/pull/1339 to make this PR more reviewable.
With partition tables moving into the distro YAML we need a way to write them in a "nice"
way. Yaml offers some helper with anchors and aliases here (shown as part of the tests)
but we still need to add json tags to all our (internal) disk structs. This of course means that
when we change our disk data structure we need to update the yaml. As long as we maintain
the distro YAML in our repo this should be fine. The alternative would be to use the advanced
partitioning but it is currently not able to express what we need and my worry is that tweaking
it to deal with what we need inside #1339 is going to slow us down significantly (but I'm open
to discuss this of course).
---
This commit adds a new …
> disk: add new unmarshalYAMLviaJSON helper

- pkg/distro/fedora/partition_tables.go
Followup for https://github.com/osbuild/images/pull/1346 where we only added `ro` to the x86_64 partition table.
This commit also adds the same change to the `aarch64` partition table.
> fedora: add ro to FSTabOptions for IoT raw disk (aarch64)

- pkg/osbuild/systemd_unit_create_stage.go
- pkg/osbuild/systemd_unit_create_stage_test.go
Create .mount and .swap units, which replace /etc/fstab, under /etc/systemd instead of /usr/lib/systemd.
This is needed for ostree-based images.
It's also probably more correct to put the files in /etc in general.
> osbuild: create .mount and .swap units in /etc/systemd

- pkg/customizations/subscription/subscription.go
- pkg/distro/rhel/images.go
- pkg/manifest/os.go
- pkg/manifest/os_test.go
- pkg/osbuild/insights_client_config_stage.go
- pkg/osbuild/insights_client_config_stage_test.go
Supports adding the insights-client config stage. Feedback and help much appreciated :)
stage added to osbuild here: https://github.com/osbuild/osbuild/pull/2030
JIRA: [HMS-5670](https://issues.redhat.com/browse/HMS-5670)
> osbuild: add insights-client config stage (HMS-5670)

- pkg/distro/fedora/distro.go
- pkg/distro/fedora/images.go
- pkg/distro/image_config.go
- pkg/distro/image_config_test.go
- pkg/distro/rhel/images.go
- pkg/distro/rhel/rhel10/ami.go
- pkg/distro/rhel/rhel10/azure.go
- pkg/distro/rhel/rhel10/distro.go
- pkg/distro/rhel/rhel10/gce.go
- pkg/distro/rhel/rhel10/ubi.go
- pkg/distro/rhel/rhel7/ami.go
- pkg/distro/rhel/rhel7/azure.go
- pkg/distro/rhel/rhel7/distro.go
- pkg/distro/rhel/rhel7/qcow2.go
- pkg/distro/rhel/rhel8/ami.go
- pkg/distro/rhel/rhel8/azure.go
- pkg/distro/rhel/rhel8/distro.go
- pkg/distro/rhel/rhel8/gce.go
- pkg/distro/rhel/rhel8/ubi.go
- pkg/distro/rhel/rhel9/ami.go
- pkg/distro/rhel/rhel9/azure.go
- pkg/distro/rhel/rhel9/distro.go
- pkg/distro/rhel/rhel9/gce.go
- pkg/distro/rhel/rhel9/ubi.go
In PR#1337 the desire was expressed to move all direct `osbuild` reference out of `distro.ImageConfig` to make it a more high level abstraction. This commit is the first step to show how this could be done with the simple `osbuild.WSLConfStageOptions`.
However doing this with the more complex ones will be quite a bit of busywork and reviewing. I am not sure we should do this before we do the yamlification as I'm worried converting the other ~26 structs that needs similar converstion will take some time.
The other concern with this is that we currently have json schema information for all osbuild options. So validating the yaml against the json-schema of osbuild seems feasible. If add this conversion stage we will need to also duplicate the json schema.
---
distro: move …
> Imageconfig no osbuild

- cmd/otk/osbuild-gen-partition-table/main_test.go
- pkg/disk/btrfs.go
- pkg/disk/disk.go
- pkg/disk/enums_test.go
- pkg/disk/filesystem.go
- pkg/disk/luks.go
- pkg/disk/lvm.go
- pkg/disk/partition.go
- pkg/disk/partition_table.go
This commit adds missing keys for to our disk structures. This is
useful for https://github.com/osbuild/image-builder-cli/pull/183
> disk: add missing json/yaml keys for disk structs

- pkg/distro/defs/fedora/distro.yaml
- pkg/distro/defs/loader.go
- pkg/distro/defs/loader_test.go
- pkg/distro/defs/rhel-10/distro.yaml
- pkg/distro/defs/rhel-7/distro.yaml
- pkg/distro/defs/rhel-8/distro.yaml
- pkg/distro/defs/rhel-9/distro.yaml
- pkg/distro/fedora/distro.go
- pkg/distro/image_config.go
- pkg/distro/rhel/rhel10/distro.go
- pkg/distro/rhel/rhel7/distro.go
- pkg/distro/rhel/rhel8/distro.go
- pkg/distro/rhel/rhel9/distro.go
- pkg/osbuild/sysconfig_stage.go
Now that all the package sets are part of the YAML this moves
the default distro.ImageConfiguration into YAML.
Note that the individual imageType ImageConfiguration are not moved yet and that will (probably) still take a while.
> distro/fedora: move defaultImageConfig into YAML

- tools/gen-manifests-diff
Improved version of #1325 that addresses https://github.com/osbuild/images/pull/1325#discussion_r1995375323
This commit tweak `gen-manifests-diff` to run against the merge base of the upstream branch instead of whatever is upstream@main. This avoids potentially confusing output when upstream/main has moved forward since the branching and the diff would include unrelated upstream changes.
Thanks to Achilleas for suggesting this.
Closes: osbuild#1322
> tools: make gen-manifests-diff run against the merge base

- cmd/osbuild-playground/my-container.go
- cmd/osbuild-playground/my-image.go
- pkg/image/disk.go
- pkg/image/ostree_archive.go
- pkg/manifest/os.go
- pkg/manifest/os_test.go
This commit is very mechanical, it stops embedding the `manifest.OSCustomizations` directly inside `manifest.OS`.
This makes it more explicit what comes from a OSCustomization and what is just part of OS which makes it easier to refactor `ImageConfig` and `OSCustomizations` as there is currently much manual copying.
> manifest,image: stop embedding `OSCustomizations` in `manifest.OS`

- pkg/distro/defs/loader.go
- pkg/distro/defs/loader_test.go
- pkg/distro/defs/rhel-10/distro.yaml
- pkg/distro/defs/rhel-7/distro.yaml
- pkg/distro/rhel/rhel10/partition_tables.go
- pkg/distro/rhel/rhel7/partition_tables.go
This commit moves the partition tables for RHEL-10,7 (and by implication
Centos-10) into YAML.
> rhel{7,10}: move partition table into yaml

- pkg/manifest/export_test.go
- pkg/manifest/os.go
- pkg/manifest/os_test.go
- pkg/manifest/ostree_deployment.go
- pkg/manifest/ostree_deployment_test.go
- pkg/osbuild/fips.go
- pkg/osbuild/pki_update_ca_trust_stage.go
- test/data/manifest-checksums.txt
The new addInlineDataAndStages() method of the OS and OSTreeDeployment pipeline generators appends file creation, chmod, and chown stages to the pipeline and also adds the inline data to the inlineData property.  The inlineData list is used to return inline data that was collected during manifest generation.
Previously, we used the OSCustomizations.Files list in two ways:
- To define files to be created externally, during the initialisation of OSCustomizations (e.g. from a blueprint).
- To collect files that needed to be created under certain conditions or for certain stages while generating the pipeline.
This lead to inconsistencies.  The handling of the Files list was meant to always be near the end of the pipeline, before the selinux stage.  However, files were being added to the list …
> manifest: addInlineDataAndStages() helper method for the OS and OSTreeDeployment pipelines

- pkg/dnfjson/dnfjson.go
- pkg/dnfjson/dnfjson_test.go
- pkg/rhsm/secrets.go
This commit tweaks the way error from subscription are handled in dnfjson. Current any error details are ignored when trying to load a subscription. But this is problematic as it makes diagnosing issues like:
https://github.com/osbuild/image-builder-collection/issues/3 more difficult.
So this commit includes the error details of trying to load the subscriptions in the error message of dnfjson.
I also added a XXX in the rhsm subscription loader, I wonder if we should already error when there are no cosumer keys found? That would give cleaner errors but if its really option to have consumer keys the warning is valid of course (but AIUI the consumer keys are needed for subscriptions, no?)
> dnfjson: provide details if subscription cannot be found

- test/config-map.json
- test/configs/rhel-azure-rhui-cdn.json
- test/configs/rhel-azure-rhui.json
- test/data/manifest-checksums.txt
- test/data/repositories/rhel-9.6.json
In Brew, we build the Azure images with some configuration for RHUI packages and RPM key imports.  Let's replicate those configurations here so that we test them on PRs.
We should keep these up to date with any changes in the downstream build configurations.
Closes #1410
Note: The blueprint change in https://github.com/osbuild/blueprint/pull/13 will be used to disable the `auto_enable_yum_plugins` option in subscription-manager (https://github.com/osbuild/images/issues/1407#issuecomment-2789286062).  This change should be included in these configs when it's ready.
> test: add configs for Azure that match official builds

- test/scripts/build-image
Tiny copy/paste error fix in the build-image argparse description.
> test: fix description of `build-image`

- pkg/osbuild/manifesttest/manifesttest.go
- pkg/osbuild/manifesttest/manifesttest_test.go
This adds a new manifesttest.StagesForPipeline() that can help extract the names of the stages for a pipeline. This will help with
https://github.com/osbuild/image-builder-cli/pull/201/files#r2037909740
> manifesttest: add helper to find stages in a pipeline

- .github/workflows/gobump.yml
- docs/developer/README.md
Please review carefully, I did not test this locally as I have no idea how to do that. My assumption is we would merge this and then test it by manually triggering it?
To get more info about `gobump` please read: https://github.com/lzap/gobump
I can either move the project into osbuild GH org or give maintainer permissions to anyone interested just in case. My account is 2FA protected.
> ci: dependency updater via gobump

- .github/workflows/gobump.yml
A typo in the new gobump workflow.
https://github.com/osbuild/images/pull/1385
> ci: dependency updater gobump typo

- .github/workflows/gobump.yml
Haven't realized I must use Go from Fedora when Fedora container is in use.
https://github.com/osbuild/images/pull/1439
> ci: dependency updater gobump golang fix

- .github/workflows/gobump.yml
Getting back to where I left it off before holidays - I have found out that the `git config --unset-all` was exiting with 5 code. I blindly copy-pasted it from the other action, this is not necessary in a clean Fedora container, so removed. Also added shell command echo to see where it exactly fails.
It should work now (TM).
> ci: remove unnecessary git config command

- .github/workflows/gobump.yml
This is embarrassing but I am almost there. The `gh` tool was not installed in the container, also the env variable the tool expects should be named `GH_TOKEN` (from the man page). Hopefully env vars do carry over into containers, I could not find any documentation proof about that, so crossing my fingers.
> ci: add missing gh tool to gobump action

- internal/workload/custom.go
- internal/workload/workload.go
- pkg/distro/fedora/imagetype.go
- pkg/distro/rhel/imagetype.go
- pkg/manifest/os.go
- test/data/manifest-checksums.txt
Masked services were not propagated through the workload onto images, meaning they never ended up in the manifest. Let's set them on the workload, and take them from the workload in the `os` pipeline.
> many: propagate masked services

- .github/workflows/gobump.yml
And it did not work because I deleted `GITHUB_TOKEN` which is still needed for `git`. So the action needs both this one and `GH_TOKEN` for `gh` tool.
```
git push -f https://@github.com/schutzbot/images.git
fatal: could not read Password for 'https://github.com/': No such device or address
```
https://github.com/osbuild/images/pull/1452
> ci: keep GITHUB_TOKEN in gobump action

- pkg/distro/defs/rhel-10/distro.yaml
- test/data/manifest-checksums.txt
It turns out that 'cloud-init' is not able to resize the root partition on our GCE RHEL-10 images, because there is no "resizer" tool available. Install 'cloud-utils-growpart' by default, which provides the 'growpart' tool.
> RHEL-10/gce: install cloud-utils-growpart by default

- pkg/distro/fedora/images.go
- pkg/distro/image_config.go
- pkg/distro/image_config_test.go
- pkg/distro/rhel/images.go
- pkg/distro/rhel/rhel10/sap.go
- pkg/distro/rhel/rhel8/sap.go
- pkg/distro/rhel/rhel9/sap.go
This commit adds a new `DNFSetReleaseVerVar` to
`ImageConfig` and a new `DNFConfigOptions() helper.
The rational is that `DNFConfigStageOptions` current gets the `osVersion` passed in directly. When we move to a YAML based ImageConfig this will be problematic as we do not have access to variables like this. By making this new declarative option we sidestep the problem.
This option is used in the rhel sap images.
Its slightly unfortunate that we need to change two places (images.go in rhel/fedora) to use the new
helper (pr#1387 would fix this) but with more YAML work eventually this should converge.
Thanks to thozza for suggesting this simplified approach.
JIRA: HMS-5284
> distro: add DNFSetReleaseVerVar to ImageConfig

- pkg/distro/fedora/distro.go
- pkg/distro/fedora/images.go
- pkg/distro/fedora/imagetype.go
- pkg/distro/image_config.go
- pkg/distro/rhel/images.go
- pkg/distro/rhel/imagetype.go
- pkg/distro/rhel/rhel10/ami.go
- pkg/distro/rhel/rhel10/azure.go
- pkg/distro/rhel/rhel10/distro_test.go
- pkg/distro/rhel/rhel10/gce.go
- pkg/distro/rhel/rhel10/qcow2.go
- pkg/distro/rhel/rhel10/vmdk.go
- pkg/distro/rhel/rhel7/ami.go
- pkg/distro/rhel/rhel7/azure.go
- pkg/distro/rhel/rhel7/qcow2.go
- pkg/distro/rhel/rhel8/ami.go
- pkg/distro/rhel/rhel8/azure.go
- pkg/distro/rhel/rhel8/edge.go
- pkg/distro/rhel/rhel8/gce.go
- pkg/distro/rhel/rhel8/qcow2.go
- pkg/distro/rhel/rhel8/vmdk.go
- pkg/distro/rhel/rhel9/ami.go
- pkg/distro/rhel/rhel9/azure.go
- pkg/distro/rhel/rhel9/edge.go
- pkg/distro/rhel/rhel9/gce.go
- pkg/distro/rhel/rhel9/qcow2.go
- pkg/distro/rhel/rhel9/vmdk.go
[draft until https://github.com/osbuild/images/pull/1472 is merged to not cause conflicts there]
This commit moves the `imageType.kernelOptions` option into `distro.ImageConfig`. The rational is that when we move to YAML we will need to be able to override the kernel options based on various conditions.
Here is an example from mkMinimalRawImgType():
```go
if common.VersionGreaterThanOrEqual(d.osVersion, "43") {
it.kernelOptions = []string{"rw"}
}
```
The conditions will be implemented on the imageConfig but having conditions when defining image types would be a bit stange. The easiest fix is to move kernelOptions into ImageConfig. Fwiw, I think conceptually it also makes sense there so this is probably a worthwhile chage on its own but it will make the YAML work in …
> distro: move `kernelOptions` into `ImageConfig`

- pkg/customizations/subscription/subscription.go
- pkg/manifest/subscription.go
- pkg/manifest/subscription_test.go
Supports registering with a content template on bootup
For RHEL 9.6 and 10, the rhc connect command can be used with the template to register. For RHEL 8, a curl command is used to associate the system to the template through the patch API
JIRA: [HMS-5994](https://issues.redhat.com/browse/HMS-5994)
> manifest: register insights to template on boot (HMS-5994)

- internal/common/unmarshal.go
- pkg/disk/disk.go
- pkg/disk/luks.go
- pkg/disk/lvm.go
- pkg/disk/partition.go
- pkg/disk/unmarshal.go
- pkg/osbuild/modprobe_stage.go
- pkg/osbuild/modprobe_stage_test.go
- pkg/osbuild/sshd_config_stage.go
- pkg/osbuild/sshd_config_stage_test.go
- pkg/platform/platform.go
- pkg/platform/platform_test.go
This PR adds custom unmarshalers to various parts of osbuild and platform. We will need to be able to unmarshal osbuild options that are used in the ImageConfig. And we will need to be able to set platform information for image types in YAML too so the platform.ImageFormat also needs to be handed.
Split out from https://github.com/osbuild/images/pull/1462
> many: add custom unmarshalers for osbuild, platform

- .github/workflows/validate-checksums.yml
On the merge queue, the validate checksum fails because we use the base branch to start checking.  We could check if the checksums changed from the rebase, but that wouldn't be useful since the check isn't required anyway.
For now, let's make the check run only on PRs.  This might result in inconsistencies in main, but we're still experimenting with this test anyway, so it'll be interesting to see how often that happens and how confusing it might be.
> github: don't run manifest checksum validation on the merge queue

- pkg/distro/rhel/images.go
- pkg/manifest/os_test.go
- pkg/osbuild/insights_client_config_stage.go
- pkg/osbuild/insights_client_config_stage_test.go
Fixes a bug because the insights_client_config stage expects the options to be nested under a config object.
> osbuild: Add config to InsightsClientConfigStageOptions

- pkg/manifest/os.go
Instead of appending the directories that are necessary to the OS customizations we create them immediately.
Punting the directories into the customizations means that the `mkdir` stage for these is inserted later in the process. Since the copy stages for the files are created immediately and the directories are deferred it's possible for image types that don't have the directory pre-created to fail to build as the copy fails.
---
`p.addInlineDataAndStages` creates the `copy` stages immediately. The directories are created much later in the manifest. This can fail.
> manifest/os: immediately create directories (HMS-6043)

- .github/dependabot.yml
We recently added a new action for Go dependency updates called gobump. The new action handles dependency updates but only if they don't require go version bumps, which dependabot seems to struggle with, creating broken PRs daily.
I'm inclined to disable dependabot's gomod action completely, but we instead decided to let it run weekly to review what it's proposing, on a lower frequency, while we also evaluate the new gobump action.
> github: run dependabot gomod action weekly

- pkg/customizations/fsnode/fsnode_test.go
The error behavior of the golang json decoding changed in 1.24, this should fix it.
> fsnode: fix go-1.24 errors 

- pkg/disk/filesystem.go
- pkg/image/bootc_disk.go
- pkg/image/bootc_disk_test.go
- pkg/manifest/build.go
- pkg/manifest/build_test.go
- pkg/osbuild/mkfs_ext4_stage.go
- pkg/osbuild/mkfs_stage.go
- pkg/osbuild/mkfs_stages_test.go
This is some initial work for supporting bootc in the automotive projects. It includes the following:
* Support for selinux policies other than "targeted"
* Support for using a different container for the "build" pipeline (because we want a minimal target image without e.g. mkfs.ext4)
* Always enable the "verity" ext4 filesystem in mkfs.ext4, which allows us to use validated composefs support
> Initial automotive work: custom selinux policy, separate build container for bootc, and ext4 verity

- pkg/distro/distro_test.go
- pkg/manifest/os.go
Run TestImageTypePipelineNames and
TestOSTreeOptionsErrorForNonOSTreeImgTypes in parallel. Saves about 20s on my local machine.
> test: Run more distro tests in parallel

- pkg/distro/rhel/rhel8/options.go
- pkg/distro/rhel/rhel9/options.go
A long time ago, we decided that user and group creation for ostree-based images should happen in the deployment (disk image creation or via an installer).  The plan was to deprecate the feature of user and group creation in ostree commits (the base, immutable part of the system) for a few minor versions and then remove the feature completely.
Normally, this kind of thing would make sense to change in a major release (RHEL 10), but with the move to bootc and image mode in RHEL 10, we're not deprecating any features but the whole thing is changing.
The decision has changed now: There will be no removal of the feature in edge for the lifetime of RHEL 9.
See comment on [THEEDGE-4235](https://issues.redhat.com/browse/THEEDGE-4235)
See also …
> distro/rhel: remove the user/group warnings for edge-commits

- pkg/blueprint/disk_customizations.go
- pkg/blueprint/disk_customizations_test.go
- pkg/disk/partition.go
- pkg/disk/partition_table.go
- pkg/disk/partition_table_test.go
- pkg/osbuild/disk.go
As discussed in https://github.com/bootc-dev/bootc/issues/926, we want to be able to set more GPT partition details in the customization.
> Add support for setting partition uuid and label

- pkg/disk/filesystem.go
- pkg/disk/filesystem_test.go
This is a small followup for https://github.com/osbuild/images/pull/1526 - I was too late with my review (but also don't want to burden Alex with chores like the marshal/unmarshal tests). 
The first commit just add tests, the second has a tiny change that should be useful (unless I miss something and the ToString() was deliberately chosen to avoid the automatic convertion via `%s` - if so I'm happy to just change it to an explicit test that tests that this does not work and a commit message with the rational why we selected it this way).
---
disk: rename `MkfsOption.ToString` to `MkfsOption.String`
This commit renames `MkfsOption.ToString` to `MkfsOption.String`
and expands the test to cover that too.
In go its much more common to just have `String()` methods
to convert a type to a …
> disk: tiny tweaks for the new MkfsOptions support

- .github/workflows/tests.yml
- Makefile
- pkg/blueprint/blueprint.go
- pkg/osbuild/sysconfig_stage.go
- pkg/osbuild/yum_repos_stage.go
This commit adds a new tags-equal vet checker that ensures our json/yaml/toml tags are consistent. This is a followup for https://github.com/osbuild/blueprint/pull/18 where this caused problems.
> Makefile: add vet command to check for consistent struct tags

- pkg/distro/defs/fedora/distro.yaml
- pkg/distro/fedora/images.go
- pkg/distro/fedora/version.go
- pkg/distro/image_config.go
- pkg/manifest/anaconda_installer_iso_tree.go
- pkg/manifest/anaconda_installer_iso_tree_test.go
fedora: implement setting of the RootfsType via YAML
This commit moves the setting of the rootfs type into the
ImageConfig and by implication into pure YAML.
The relevant image defintions are now also updated. This
also means that one can define `iso_rootfs_type: "erofs"`
trivially now per image type.
Note that this also shows an inconsistency with the old
code, some of the iso images have been moved to the new
SquashfsRootfs but other have not. We should probably
look into this too but for now this PR opts to not change
the behavior just moves the place how the RootfsType for
the iso is set.
---
manifest: make `RootfsType` marshallable via JSON/YAML
This commit makes the `manifest.RootfsType` marshallable via
JSON/YAML so that we can use it in the image defintions.
This will be useful …
> fedora: implement setting of the RootfsType via YAML

- pkg/distro/defs/fedora/distro.yaml
- pkg/distro/fedora/distro_test.go
- pkg/distro/fedora/images.go
- pkg/distro/fedora/package_sets.go
- test/data/manifest-checksums.txt
In newer versions of WSL there's a new out-of-the-box experience. This is packaged in Fedora under `wsl-setup`. Let's include the package.
> fedora/wsl: include `wsl-setup` (HMS-8573)

- .github/workflows/tests.yml
- Schutzfile
This is probably too early and I am very likely doing it incorrectly, but F42 is ahead of us and F40 is the last with Go 1.22, this will enable us to bump Go to 1.23.
https://github.com/osbuild/images/pull/1433
> tests: bump fedora versions to 41

- pkg/image/anaconda_container_installer.go
- pkg/manifest/anaconda_installer_iso_tree.go
- pkg/manifest/anaconda_installer_iso_tree_test.go
Contributes towards: https://github.com/osbuild/bootc-image-builder/issues/924
Allow passing in the root filesystem format when generating an ISO.
Follow-up: https://github.com/osbuild/bootc-image-builder/pull/935
> bootc: Make installed rootfs configurable

- pkg/datasizes/parse.go
- pkg/datasizes/parse_test.go
- pkg/disk/btrfs.go
- pkg/disk/btrfs_test.go
- pkg/disk/lvm.go
- pkg/disk/lvm_test.go
- pkg/disk/partition.go
- pkg/disk/partition_table.go
- pkg/disk/partition_table_test.go
- pkg/disk/partition_table_yaml_test.go
- pkg/disk/partition_test.go
- pkg/distro/defs/fedora/distro.yaml
- pkg/distro/defs/rhel-10/distro.yaml
- pkg/distro/defs/rhel-7/distro.yaml
- pkg/distro/defs/rhel-8/distro.yaml
- pkg/distro/defs/rhel-9/distro.yaml
With the move of image definitions to YAML, we lost the ability to use units to define various byte-sized properties of partitioning. This PR adds a helper function `datasizes.ParseSizeInJSONMapping()` for parsing strings with units and converting them to bytes in JSON objects. The helper function is then used in a struct-specific custom unmarshaler.
I've also adjusted the existing distro definitions in YAML to use strings with units, instead of integers.
Notes:
- I acknowledge that the `ParseSizeInJSONMapping()` function can be extended to process multiple byte-sized fields in the same JSON object, instead of calling it multiple times. I'd address this in a follow-up that should happen after the YAMLification converges (see other points).
- There are additional byte-sized fields in the …
> Many: support using string with unit for byte-sized partitioning fields in YAML distro definitions

- pkg/distro/defs/fedora/distro.yaml
- pkg/distro/generic/images.go
- pkg/image/archive.go
- test/data/manifest-checksums.txt
This PR builds on top of #1581 which now allows selecting the compression for the tar stage. It extends the archive image type to have a compression field which is set based on the value in the image type YAML.
I'm not entirely happy with the situation in `archive.go`, it is consistent with the handling in `disk.go`.
I've spoken with @achilleas-k and @mvo5 about this and it would maybe be possible to introduce a common subset enum of compression supported between both the disk, and archive, image types. However; they already deviate (archive supports gzip, disk does not) so this will require additional stages and pipelines to support gzip on disk images as well.
We can discuss this (or better) approaches in this PR.
> fedora/wsl: xz compression (HMS-8573)

- pkg/distro/defs/rhel-10/distro.yaml
- pkg/distro/rhel/rhel10/distro.go
- pkg/distro/rhel/rhel10/distro_test.go
- pkg/distro/rhel/rhel10/vagrant.go
- test/config-map.json
- test/data/manifest-checksums.txt
This image type was previously updated and improved for Fedora. I wanted to hold out for the full YAML changes but have now decided to land these faster.
Image was manually tested, might need refinement in followup(s) it is currently similar to the QCOW2 image type.
> distro/rhel-10: new `vagrant-libvirt` image type (HMS-6116)

- pkg/distro/rhel/rhel9/azure.go
- test/data/manifest-checksums.txt
This commit tweaks the conditions in defaultAzureKernelOptions and defaultAzureImageConfig so that when we check if a version is greater than 9.6 we also check if its centos. Centos versions are always just "9" so any greater-than version compare will yield false but for centos we want the same behavior as on the latest rhel.
This is not ideal for almakitten but this problem fixes itself once we move to image-config in YAML (c.f. https://github.com/osbuild/images/pull/1616) where the minor verison is automatically taken into account in the version compare (i.e. 9-stream is > 9.x).
> rhel9: enable latest azure changes on centos-9 too

- pkg/distro/rhel/rhel9/azure.go
- test/data/manifest-checksums.txt
All other Azure image types are xz compressed because the disk size is very big and mostly empty.  Let's compress the CVM image for convenience and consistency.
> distro/rhel9: xz compress azure-cvm image type [HMS-8587]

- pkg/rhsm/facts/facts.go
Images built by ibcli currently do not set any API type, so they do not show up in any Insights metrics. Let's add a new type for ibcli and the use it in it when generating manifests.
> RHSM/facts: add 'image-builder CLI' API type

- pkg/manifest/subscription.go
- pkg/manifest/subscription_test.go
Fixes rhc command to support registering to content templates with or without spaces in the template name
Jira: [HMS-8657](https://issues.redhat.com/browse/HMS-8657)
> manifest: handle content template name with spaces

- pkg/distro/generic/images.go
- pkg/distro/image_config.go
- pkg/distro/rhel/images.go
- pkg/image/anaconda_live_installer.go
- pkg/image/bootc_disk.go
- pkg/image/bootc_disk_legacy.go
- pkg/image/bootc_disk_test.go
- pkg/manifest/anaconda_installer.go
- pkg/manifest/os.go
image: make BootcDiskImage use `OSCustomizations` explicitly
This commit makes the OSCustomizations in BootcDiskImage
explicit instead of embedding them. This is similar to
PR#1386.
(this will require some mechanical change in bib but it allows us to re-use the osCustomizations() helper in pkg/distro/generic later)
---
pkg: rename `SElinux` -> `SELinux` for conistency
This commit changes `SElinux` -> `SELinux` for conistency, we
almost everywhere spell it SELinux so lets do it really everywhere.
> many: start converging images and bootc-image-builder

- pkg/distro/defs/fedora/distro.yaml
- pkg/distro/defs/loader.go
- pkg/distro/generic/imagetype.go
This commit adds support for supported_partitioning_modes via YAML so that the RHEL-8 constraints for "edge-raw-image" and "edge-simplified-installer" can be expressed.
Note that the rhel code is using `unsupportedPartitionModes` but the downside of that approach is that every time a new mode is added there is a risk of forgeting to update the list of unsupported modes (this happend e.g. when we added btrfs partitioning and the unsupported partition modes list was not updated for rhel8).
We also add the new `supported_partitioning_types` mode into the fedora YAML distro definitions and drop the custom code to validate/mutate the partitioning for rpm_ostree from the go code, the discussion from
https://github.com/osbuild/images/pull/1654 is that we can drop the mutation entirely and just …
> distro: add support for `supported_partitioning_modes`

- pkg/distro/defs/distros.yaml
- pkg/distro/defs/loader.go
- pkg/distro/defs/loader_test.go
- pkg/distro/generic/distro.go
This commit adds the ability to skip image types bases on conditions on the distro level. This solves two problems:
1. At the rhel distro level we now define that some image types like "ec2" are only relevant for rhel and all derrived distros use this.
2. When we move rhel8 to the generic distro we will be able to express that certain image types like "azure-eap7-rhui" are only availalbe after version 8.6 or "vhd" for arm64 is only available after 8.6 [0]
As part of the commit the ignore_image_types list is moved to rhel then and a `not_distro_name` in the condition is added so that we can express:
```yaml
conditions:
"some image types are rhel-only":
when:
not_distro_name: "rhel"
ignore_image_types:
- azure-cvm
```
Extracted and cleaned up from PR#1643
[0] See …
> distro: add conditionals when ignoring image_types for a distro

- cmd/build/main.go
- cmd/gen-manifests/main.go
- internal/buildconfig/buildconfig.go
- internal/buildconfig/buildconfig_test.go
This commit adds support for `-buildconfig-allow-unknown` that
allows to turn off stict unmarshal mode in json for the configs
in test/ - this is useful in `gen-manifests-diff` where we always
run the "old" gen-manifests against the new branch. If the new
code contains unknown (to the old code) fields it errors. With
this new addition we can run the "old" gen-manifest with
`-buildconfig-allow-unknown` and the new one without.
This allows us to diff manifests even if the build config changes,
like in PR#1656 where `distro.ImageOptions` grows a new
`Bootc` option (similar to OSTree).
---
buildconfig: add option to allow unknown fields
This commit adds an option to allow unknown fields when reading the
build config. This is important for "gen-manifests-diff" when it
needs to read configs …
> manifest-gen: add `-buildconfig-allow-unknown` flag

- pkg/distro/defs/distros.yaml
- pkg/distro/generic/distro_test.go
This commit re-adds the `bootstrap_containers` for rhel{7,10}.
> defs: add missing `bootstrap_containers`

- pkg/distro/defs/distros.yaml
- pkg/distro/defs/id.go
- pkg/distro/defs/id_test.go
- pkg/distro/generic/fedora_test.go
- pkg/distro/generic/rhel7_test.go
- pkg/distro/generic/rhel8_test.go
- pkg/distro/generic/rhel9_test.go
distro: simplify `matchAndNormalize()`
Trivial change to drop the explicit handling of an incomplete
case in `matchAndNormalize()`. It was added mostly for
symetry but then the `default:` is already covering it and
a comment is good enough to show that `case 2:` was considered.
Thanks to Achilleas for suggesting this.
---
distro: make `matchAndNormalize` more robust and add test
This commit adds a test for the matchAndNormalize() helper
that checks for invalid/missing capture group names. This
uncovered a crash in the code that is also fixed.
Thanks to Thozza and Achilleas for suggesting this.
---
distro: make the regex for the `rhel7,fedora` stricter
This commit makes the regexp for the rhel7 and fedora
distro stricter. It also updates/moves the tests so
that the stricter conditions are …
> distro: small followups for PR#1682

- pkg/distro/distro.go
- pkg/distro/generic/imagetype.go
This reverts commit 05490a26c11dc198e54de800b91a4f81642a81b4.
This broke image-builder-cli who uses this feature in `describe`.
Thanks to Brian for reporting.
> Revert "distro: drop `ImageType.BasePartitionTable()`"

- .github/workflows/tests.yml
- pkg/distro/defs/distros.yaml
- pkg/distro/defs/rhel-8/distro.yaml
- pkg/distro/defs/rhel-9/distro.yaml
**distro/rhel9: remove duplicate anchors from yaml definitions**
I've been using `yq` a lot to get a flattened view of our yaml
definitions, with all references resolved.  While `yamllint` doesn't
seem to mind duplicated anchors, `yq` fails when they are found.
Duplicate anchors create ambiguity.  Remove them.
- platform_override_conditions_ami: never referenced, so it is
unnecessary.
- default_partition_table_part_boot_payload: defined three times with
the same body.  Convert the two extra anchors to references.
---
**distro/rhel8: remove duplicate anchors from yaml definitions**
platform_override_conditions_ami is never referenced, so it is
unnecessary.
---
**distro/defs: fix up issues in distros.yaml**
Fix issues caught by yamllint on distros.yaml:
- Document start marker (---).
- …
> distro: fix issues with yaml distro definitions and enable yaml checks

- pkg/distro/defs/loader.go
- pkg/distro/defs/loader_test.go
This fixes a bug that when a distro is not found via the `match` mechanism but with an exact `name` match the variables where not substituted. This caused an error in image-builder-clis build.
We also need a reverse dependency test for ibcli in images but that should be its own commit.
> distro: fix bug in variable substitution for static distros

- .github/workflows/test-ibcli-integration.yml
This commit adds a minimal workflow to run the
image-builder-cli unit tests against the images library that is PRed.
This is inspired by the osbuild-composer integration but starts initially much simpler to avoid duplicating too much code, it would be nice to extract a common helper workflow.
This should give as a (non-required) test failure if we break ibcli accidentally. 
[edit: this will fail until https://github.com/osbuild/images/pull/1710 is merged]
> github: add minimal reverse dependency test for ibcli

- pkg/distro/generic/export_test.go
- pkg/distro/generic/options_test.go
Add tests for the checkOptions() image type function.  This is done in
preparation for a new way of declaring supported and required
customizations and options alongside the image definitions.
The tests themselves contain notes highlighting incorrect behaviour.  I
am leaving these unfixed intentionally.  Corrections to the config
validation will happen alongside the new definitions.
---
This commit was spun-off from and related to #1216.
It is meant to serve as a reference for the current behaviour of the image-type-based config validation (however incorrect), so that changes in the functionality of the validator get reflected in the testing as well.
The tests are not meant to cover each individual image type.  My goal was to cover each error condition, so for cases where the same rules …
> distro/generic: test checkOptions() functions

- pkg/distro/defs/loader.go
- pkg/distro/defs/loader_test.go
- pkg/distro/generic/distro.go
- pkg/distro/generic/images.go
- pkg/distro/generic/imagetype.go
distro: set `distro.ID` in `DistroYAML` by loader
By setting the parsed distro.ID into DistroYAML we can
simplify a lot of the cases where we currently use
`nameVer string` for the various helpers. By using the
id we avoid re-parsing the name and potentially raising
error. This will simplify the code in the comming commits.
---
distro: add/use `DistroYAML.ID` consistently
We use(d) `distroNameVer` a lot when accessing YAML
data because that is what we had when transitioning
from fedora/rhel distro abstraction to the generic
distro. But now that everything is a generic distro
we can actually use `distro.ID` everywhere which
simplifies a lot of code and avoids (re)parsing
the `distroNameVer`.
> distro: set `distro.ID` in `DistroYAML` by loader

- pkg/distro/generic/distro.go
- pkg/distro/generic/distro_test.go
- pkg/distro/generic/imagetype.go
This commit adds a bit more type safety around the usage of the architecture. It currently uses strings in many places where its more appropriate to use our `arch.Arch` abstraction.
> distro: use `arch.Arch` instead of `archStr`

- pkg/blueprint/disk_customizations.go
- pkg/blueprint/disk_customizations_test.go
- pkg/disk/partition_table.go
- pkg/disk/partition_table_test.go
This pull-request  adds the capability to create raw (unformatted) partitions, for custom boot setups that require partitions with specific GPT types but without a filesystem (e.g: ukiboot).
It also adds the specific GPT type UUIDs for UKIBoot (UKIBootPartitionUUID) and the UKIBoot control (UKIBootCtlPartitionUUID) partition types. And the logic to properly map these types with the UKIBoot partitions, based on their labels.
Having this support will allow bootc-image-builder to embedded customization files to generate images that can be booted using UKIBoot.
> disk: Add support for raw partitions,  custom types and UKIBoot partition layout

- data/distrodefs/README.md
[build on top of https://github.com/osbuild/images/pull/1692]
This commit expands the README.md to cover more
keys and pattern with the new YAML based image
definitions.
> distrodefs: expand README.md

- data/distrodefs/fedora/imagetypes.yaml
- data/distrodefs/rhel-10/imagetypes.yaml
- data/distrodefs/rhel-8/imagetypes.yaml
- data/distrodefs/rhel-9/imagetypes.yaml
- pkg/distro/distro.go
- pkg/distro/generic/imagetype.go
- pkg/distro/test_distro/distro.go
- pkg/imagefilter/filter.go
- pkg/imagefilter/filter_test.go
Since we support aliases for image definitions, we can add the image
types used in `image-builder-crc` to the alias of the corresponding
image type in the distro definitions.
> Add crc image types as image aliases (HMS-8730)

- data/distrodefs/distros.yaml
Updated based on
https://github.com/osbuild/image-builder-crc/tree/8311bea5e2fc331ac27fc79c50349a381a006696/distributions, which uses the oscap tooling to fetch a list of supported profiles per distro.
> rhel: fix openscap profile allowlists (HMS-9095)

- data/distrodefs/fedora/imagetypes.yaml
- pkg/distro/generic/imagetype.go
The blueprint contains a few fields that are essentially metadata and not configuration / customizations. These should always be implicitly supported by all image types.
~~Draft: Based on #1216~~
> distro/generic: implicitly support blueprint metadata fields

- internal/testdisk/partition.go
- pkg/bib/osinfo/osinfo.go
- pkg/bib/osinfo/osinfo_test.go
- pkg/disk/raw.go
- pkg/disk/raw_test.go
- pkg/osbuild/bootupd_stage.go
- pkg/osbuild/device.go
- pkg/osbuild/mkfs_stage.go
- pkg/osbuild/mkfs_stages_test.go
- pkg/osbuild/write_device_stage.go
This adds required features for making bootc-image-builder support aboot images. 
The two features are:
Add support for Osinfo to find the kernel dir (/usr/lib/moduler/*) in the target container, and check if it contains an aboot.img. This will be used by bootc-image-builder to trigger the "aboot mode" for the image. This is similar to what was done for `bootc install` in https://github.com/bootc-dev/bootc/pull/1532.
Support adding a "disk.Raw" payload, that specifies a file from an earlier pipeline and writes it to a device. This uses the new org.ostree.write-device stage (added in v154).
The intent is that bootc-image-builder will detect that there is an aboot.img in the target image, and then find the correct partition in the partition table and add a disk.Raw  payload to the raw boot …
> Basic support for aboot support in bootc-image-builder

- pkg/distro/generic/images.go
- pkg/image/anaconda_container_installer.go
- pkg/image/anaconda_live_installer.go
- pkg/image/anaconda_net_installer.go
- pkg/image/anaconda_ostree_installer.go
- pkg/image/anaconda_tar_installer.go
- pkg/image/archive.go
- pkg/image/bootc_disk.go
- pkg/image/bootc_disk_legacy.go
- pkg/image/bootc_disk_test.go
- pkg/image/container.go
- pkg/image/disk.go
- pkg/image/image.go
- pkg/image/installer_image_test.go
- pkg/image/ostree_archive.go
- pkg/image/ostree_container.go
- pkg/image/ostree_disk.go
- pkg/image/ostree_disk_test.go
- pkg/image/ostree_simplified_installer.go
- pkg/image/ostree_simplified_installer_test.go
image: add platform/filename to image.New*()
We require a platform and a filename for all images we create
so instead of setting it as the first thing after New*() make
it required. This ensures that its not missed.
---
image: make platform/filename part of image.Base and unexport
Every image we use has a platform and a filename so make it
part of `image.Base` instead of duplicating it everywhere.
> image: add platform/filename to image.New*()

- pkg/container/client.go
- pkg/distro/bootc/bootc.go
- pkg/distro/bootc/bootc_test.go
- pkg/distro/bootc/export_test.go
- pkg/distro/bootc/image_test.go
- pkg/distro/bootc/partition.go
- pkg/distro/bootc/partition_tables.go
- pkg/distro/bootc/util.go
- pkg/distrofactory/distrofactory.go
- pkg/manifestgen/manifestgen.go
- pkg/manifestgen/manifestgen_test.go
This is a first step towards moving bootc images into the "images" library. 
Eventually we want to move bootc image types into YAML too (like https://github.com/osbuild/images/pull/1656) is doing. But with this first step its a lot easier to move.
90% of this is moving code from bib (with tiny adjustments) into images.
Thanks to Achilleas and Simon for suggesting this simplified strategy. 
The functional/end-to-end tests are running in https://github.com/osbuild/bootc-image-builder/pull/1014 as part of the bib test-suite (all end-to-end tests work there)
/jira-epic HMS-8839
JIRA: [HMS-9176](https://issues.redhat.com/browse/HMS-9176)
> distro: add a bootc distro (HMS-9176)

- data/distrodefs/fedora/imagetypes.yaml
- pkg/distro/generic/images.go
- pkg/image/anaconda_container_installer.go
- pkg/image/anaconda_live_installer.go
- pkg/image/anaconda_net_installer.go
- pkg/image/anaconda_ostree_installer.go
- pkg/image/anaconda_tar_installer.go
- pkg/image/installer_image_test.go
- pkg/manifest/anaconda_installer.go
- pkg/manifest/anaconda_installer_iso_tree.go
- pkg/manifest/anaconda_installer_iso_tree_test.go
- pkg/manifest/anaconda_installer_test.go
- pkg/manifest/installer.go
Some pretty mechanical refactor to avoid some duplication. Originally I planned multiple PRs but maybe this is straightforward enough for a single PR(?). In any case, happy to split it up if desired.
---
distro: move variant for live installer into YAML
We have a lot of duplicated extraction to get the installer product, isoLabel etc. This commit consolidates it into the InstallerCustomizations.
---
image,manifest: pass InstallerCustomizations in NewAnaconda*
By passing the InstallerCustomiations into the various
image.NewAnaconda*() function we can simplify the code by
only passing a single struct (that is part of the anaconda
structs anyway).
This also means we can use the product/preview etc values
from the customizations and don't need to carry an extra
copy. So this is dropped too.
> image,manifest: move installer metadata into InstallerCustomiaztions

- test/scripts/boot-image
Booting aarch64 isn't supported yet.
> test/scripts/boot-image: skip boot for non-x86_64 azure vhds

- pkg/distro/bootc/partition_tables.go
This adds the partition table from
https://github.com/osbuild/bootc-image-builder/pull/963/files
The architecure support does no longer need to be explicit as arch/uefi vendor will come from the container/sourceinfo.
> distro: add bootc riscv partition table

- .github/workflows/tests.yml
- cmd/gen-manifests/main.go
- pkg/distro/bootc/bootc.go
- tools/gen-bootc-diff
This is meant as a temporary measure to ensure that we
produce identical manifests from the bootc integration of
images. We need it because we have no manifest checksums
for bootc based images (yet).
So the idea is:
1. have this tool validate that the manifests are identical
2. create manifests checksums for bootc images (just like we
do for regular images)
3. merge bib PR#1014 that switches disk generation to images
4. drop using the tool
5. add something like `test-integration-bib` that runs the bib tests with the latest images
Keep the tool in the backpocket because we will need it for
the ISO move to images too (c.f. https://github.com/osbuild/images/pull/1804)
> test: ensure manifest from bib/images are identical

- pkg/bib/osinfo/osinfo.go
- pkg/bib/osinfo/osinfo_test.go
- pkg/distro/bootc/export_test.go
- pkg/distro/bootc/image_test.go
- pkg/distro/bootc/partition.go
Once we do this we need to consider this part of the YAML
an API. This should be fine as its pretty stable already
(and we need a test that has all possible YAML values ideally
as a regression test).
Ideally also this would be used by anaconda/bootc install to-disk
itself as it contains important information about the image
and ideally it would just need to encoded in a single place
in the bootc container.
---
osinfo: add support for /u/l/bootc-image-builder/disk.yaml
This commit implements reading of a custom per-container
partition table in `/usr/lib/bootc-image-builder/disk.yaml`.
The format is:
```yaml
partition_table:
type: "gpt"
partitions:
- &bios_boot_partition
size: "1 MiB"
bootable: true
type: *bios_boot_partition_guid
payload:
type: raw
source: /usr/lib/firwmware/some-file.bin …
```
> bootc: add support for /usr/lib/bootc-image-builder/disk.yaml

- .github/workflows/tests.yml
We don't have test runners yet to build RPMs for Fedora 43 and 44. Disable the unit tests until we get these.
> github: disable unit tests on distros without osbuild rpms

- pkg/disk/partition.go
- pkg/disk/partition_test.go
- pkg/distro/defs/loader_test.go
- pkg/osbuild/disk.go
- pkg/osbuild/sfdisk_stage.go
- pkg/osbuild/sfdisk_stage_test.go
- pkg/osbuild/sgdisk_stage.go
- pkg/osbuild/sgdisk_stage_test.go
This is going to be necessary for automotive to set up aboot partitions.
> Add support to set partition GPT attributes in yaml format

- cmd/gen-manifests/main.go
- pkg/distro/bootc/bootc.go
- tools/gen-bootc-diff
This fixes two things:
1) If SetBuildContainer() is not called, buildImgRef is nil
2) If it is called, buildImgRef is properly set to the value passed.
Without this, when using a build container, I got errors about a missing "target" pipeline when using https://github.com/osbuild/bootc-image-builder/pull/1014
> distro: Fix build container use in bootc distro

- .github/workflows/validate-checksums.yml
When testing the head of the merge queue for manifest checksum changes, use 'git status --porcelain' instead of 'git diff --exit-code'.  Using diff does not exit with an error if there are untracked files in the tree, which we want to catch.
The "Validate manifest checksums for every commit in the PR" will still not catch file additions, because the rebase is not interrupted when untracked files introduced in the tree.  To make sure we don't fail on the merge queue when the PR is green, lets also run the "Validate manifest checksums (HEAD)" check (which uses 'git status') on PRs.
Noticed in #1802 that we merged #1812 without the manifests being added, because the addition of files was not caught.
> github: use git status to verify checksum changes

- pkg/osbuild/osbuild-exec.go
- pkg/osbuild/osbuild.go
- pkg/osbuild/osbuild_test.go
- pkg/osbuild/stage.go
Allow for calling `osbuild --inspect`, returning a deserialized manifest which has `ID`'s filled in stages and a helper method on the pipeline to get its last stage ID; which is the same as the pipeline ID.
> osbuild: inspect wrapper (HMS-8973)

- internal/testdisk/partition.go
- pkg/disk/partition_table.go
- pkg/disk/raw.go
- pkg/image/bootc_disk.go
- pkg/manifest/anaconda_installer_iso_tree.go
- pkg/manifest/coi_iso_tree.go
- pkg/manifest/raw.go
- pkg/manifest/raw_bootc.go
- pkg/manifest/raw_ostree.go
- pkg/osbuild/disk.go
- pkg/osbuild/disk_test.go
- pkg/osbuild/mkfs_stage.go
- pkg/osbuild/mkfs_stages_test.go
Primarily, this removes the SourcePipeline option in the Raw payload type, and instead always uses whatever is a "natural" source for the type of image being built. This makes a lot more sense, because the pipeline names is an internally generated thing and the user shouldn't need to know what to use here.
We also add Raw handling to Partition.partitionTableFeatures() to avoid this causing a panic.
> Support raw payloads in yaml partition info

- data/distrodefs/fedora/imagetypes.yaml
- pkg/distro/distro_test.go
- pkg/distro/generic/fedora_test.go
Adding more supported blueprint options for some Fedora image types based on tests in osbuild-composer.
---
**distrodefs/fedora: support iot-commit options in iot-bootable-container**
In osbuild-composer, we were already testing the iot-bootable-container
with the same blueprint options as the iot-commit and iot-container.
---
**distrodefs/fedora: support customizations in container types**
Add support for customizations in container types (container and wsl).
These are tested in osbuild-composer.
These types also support embedding containers.
---
> Update supported blueprint options for Fedora image types

- data/distrodefs/fedora/imagetypes.yaml
`shim-ia32` no longer exists on Fedora Rawhide, see [1]. Let's drop it from Fedora 44 and up.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=2391723
> defs/fedora: drop shim ia32

- .github/workflows/test-osbuild-composer-integration.yml
The verbosity makes it hard to pinpoint failures when needed.
> github: run go test without verbose in integration tests

- pkg/manifest/anaconda_installer.go
- pkg/manifest/anaconda_installer_iso_tree.go
- pkg/manifest/anaconda_installer_iso_tree_test.go
- pkg/manifest/anaconda_installer_test.go
- pkg/manifest/build.go
- pkg/manifest/build_test.go
- pkg/manifest/commit_server_tree.go
- pkg/manifest/coreos_installer.go
- pkg/manifest/coreos_installer_test.go
- pkg/manifest/empty.go
- pkg/manifest/export_test.go
- pkg/manifest/manifest.go
- pkg/manifest/os.go
- pkg/manifest/os_test.go
- pkg/manifest/ostree_deployment.go
- pkg/manifest/ostree_deployment_test.go
- pkg/manifest/pipeline.go
- pkg/manifest/raw_bootc.go
- pkg/manifest/raw_bootc_export_test.go
- pkg/manifest/raw_bootc_test.go
- pkg/rpmmd/repository.go
- pkg/rpmmd/repository_test.go
Simplify the `rpmmd` implementation and reduce code that will need to be ported as part of the `rpmmd` data structures consolidation by deleting the `GetVerStrFromPackageSpecList*()` functions. Let's use `rpmmd.GetPackage()` everywhere and let the caller do whatever it needs with the returned `rpmmd.PackageSpec` instance.
I also used this opportunity to reduce the amount of `panic()` calls.
/jira-epic HMS-8910
JIRA: [HMS-9310](https://issues.redhat.com/browse/HMS-9310)
> pkg/rpmmd: simplify package search in depsolved package list and `panic()` less (HMS-9310)

- cmd/build/main.go
- pkg/distro/bootc/integration_test.go
- pkg/imagefilter/formatter.go
- pkg/imagefilter/formatter_test.go
- pkg/imagefilter/imagefilter.go
- pkg/imagefilter/imagefilter_test.go
- pkg/manifestgen/manifestgen.go
- pkg/manifestgen/manifestgen_test.go
manifestgen: return manifest via Generator.Generate()
Simplify the way to use manifestgen to just return the
osbuild manifest bytes from `manifestgen.Generator.Generate()`
instead of the previous (indirect) way via `Options.Output`.
The previous way way was a bit too indirect and cumbersome
and this approach is more inline with what the existing
Serialize() is doing.
This will require updates in bib/ibcli.
---
manifestgen: simplify Generate() to only take imageType
We used to require to pass distro,arch as well but that
is entirely unnecessary (and actually arguably dangerous)
as the image type that is already passed has references
to its architecture and distro already.
---
imagefilter: simplify result and just return imageType
The imagefilter was returning the tuple …
> manifestgen,imagefilter: simplify the API

- pkg/manifest/anaconda_installer.go
- pkg/manifest/anaconda_installer_iso_tree.go
- pkg/manifest/anaconda_installer_iso_tree_test.go
- pkg/manifest/common.go
- pkg/manifest/manifest.go
- pkg/manifest/os.go
- pkg/manifest/pipeline.go
With https://github.com/osbuild/images/pull/1882 we can not return errors in more places and need to panic less. This PR contains some followups to eliminate more panics. With it merged we go from 95 panics() in pkg/manifest to just 20 (most in serializeEnd, the rest in things like `getBuildPackages()` which can be caused by unsupported architecutures, see https://github.com/osbuild/images/blob/v0.193.0/pkg/manifest/anaconda_installer.go#L127)
> manifest: remove most panics()

- pkg/distro/validator.go
- pkg/distro/validator_test.go
Configs (Blueprints) can have initialised empty slices.  This can happen if a user specifies the field but doesn't add any elements.  It can also happen if an API is generating a request and initialises empty slices even when they're not used, or serialises a request without (the equivalent of) `omitempty` on a slice.  We should treat empty slices as unset to avoid causing issues in such cases.
This can cause issues in the service, which creates blueprints with empty slices.  Building an iot-simplified installer in the Fedora service is now blocked, because the request always contains an empty packages slice.
> distro/validator: treat empty slices as unset [HMS-9437]

- pkg/distro/test_distro/distro.go
- pkg/distro/test_distro/distro_test.go
- pkg/manifest/empty.go
In the past, each image type has been defining a static list of its build and payload pipelines. This is now handled dynamically on the `Manifest` type level by iterating over all pipelines and picking the ones based on their type.
This however didn't work properly for the test_distro image types, which were returning a `Manifest` instance with two pipelines (build and os), but the build pipeline was not a proper `manifest.Build` type. Thus the Manifest.BuildPipelines() returned an empty list, while Manifest.PayloadPipelines() returned both pipelines.
To fix this, a new manifest.ContentTestBuild pipeline is added, which provides the means to create a testing build pipeline implementing the `manifest.Build` interface. Note that the manifest.ContentTest can't implement the `manifest.Build` …
> pkg/distro/test_distro: ensure Manifest.*Pipeline() works as expected

- pkg/distro/bootc/bootc.go
Currently we hard code the boot mode to LEGACY. This means that both a BIOSBOOT and an ESP partition are required/created when missing. On aarch64 this is always wrong and the BIOSBOOT should *not* be there.
This is a quick bandaid. In the future we want to share more and move this into the same idiom as is being used for generic partitions.
---
This fixes the immediate issue reason for which #1923 was created. We can discuss there if the blueprint customization is still necessary after this merges.
> bootc: UEFI for aarch64

- data/distrodefs/distros.yaml
Enable the BSI OpenSCAP profile for RHEL-9 images
> distrodefs: enable bsi oscap profile for RHEL-9 (HMS-9459)

- data/distrodefs/fedora/imagetypes.yaml
- data/distrodefs/rhel-10/imagetypes.yaml
- data/distrodefs/rhel-7/imagetypes.yaml
- data/distrodefs/rhel-8/imagetypes.yaml
- data/distrodefs/rhel-9/imagetypes.yaml
- pkg/datasizes/size.go
- pkg/datasizes/size_test.go
- pkg/distro/defs/loader.go
- pkg/distro/defs/loader_test.go
- pkg/distro/generic/imagetype.go
distro: add support for `default_size` to be a string
Make `default_size` a datasizes.Size type which means
it can be written as `size: 1234` or `size: 1 Kb` etc.
This also converts all existing image types to use
the simpler string format for the default_size.
Closes: https://github.com/osbuild/images/issues/1920
---
datasizes: add support for YAML unmarshal of datasizes
Add support to unmarshal YAML based datasizes just like we
support TOML and JSON. This is extremly simple and just
reuses the existing `common.UnmarshalYAMLviaJSON()`.
> distro: add support for `default_size` to be a string

- data/distrodefs/fedora/imagetypes.yaml
When the initial RISC-V enablement was done several packages were missing from the comps groups for the RISC-V repositories. These packages have subsequently been added to Fedora 42 and up [1].
Change the condition to apply both so we can drop it once Fedora 41 goes end of life.
[1]: http://fedora.riscv.rocks:3000/davidlt/fedora-comps/src/branch/main-riscv64-v2
> fedora/minimal: riscv comps groups
